### ISSUE TITLE
Localization support

### ISSUE THREAD

**Issue by ghost** [estevez-dev/ha_client#190]
Good feature request is add support multilanguage. More user want support translation. I want add polish translation.
Also translation menu app, status devices and also all info...

**Comment by pepeEL** [comment]
Hi
When you plan implement multilanguage ? I want help with polish lang. You write that in 0.4.0.... but first version dont have multilang....

**Comment by estevez-dev** [comment]
It is now moved on after first stable release

**Comment by pepeEL** [comment]
ok.... no good

**Comment by estevez-dev** [comment]
No good we have only 24 hours in one day =(

**Comment by pepeEL** [comment]
Ok ok :) please remember i want help in Polish if you implement it :)

**Comment by estevez-dev** [comment]
HA Client was discontinued
