### ISSUE TITLE
Odd scroll behavior in almost empty tabs

### ISSUE THREAD

**Issue by Kvasenok** [estevez-dev/ha_client#194]
When you switch to a tab with just a few entities, it still can be scrolled down "behind" the header (see screenshots). It seems like an odd behavior considering there is no actual point in scrolling such tabs. 
It doesn't affect the functionality in any way, just looks a bit strange. I think that the whole process/animation of hiding the header should end on screenshot 2 with this kind of tabs.
Screenshot 1
![screenshot_20181118-164542](https://user-images.githubusercontent.com/44749170/48673515-3f343880-eb53-11e8-9299-aa37afb0b607.jpg)

Screenshot 2
![screenshot_20181118-164551](https://user-images.githubusercontent.com/44749170/48673516-3f343880-eb53-11e8-890f-1733291c9233.jpg)

Screenshot 3
![screenshot_20181118-164558](https://user-images.githubusercontent.com/44749170/48673517-3f343880-eb53-11e8-830c-ab312ef1a06b.jpg)

**Comment by estevez-dev** [comment]
HA Client was discontinued
