### ISSUE TITLE
Long entity name issue

### ISSUE THREAD

**Issue by pepeEL** [estevez-dev/ha_client#195]
In version 0.3.9 still is a problem with long name devices... Some width will be resolved but some still is too long and not show. Maybe good option will be add text which is hide move to next line ?

**Comment by estevez-dev** [comment]
Please provide a screenshot

**Comment by pepeEL** [comment]
![screenshot_20181118-154817](https://user-images.githubusercontent.com/16692223/48674309-f8424500-eb4a-11e8-9fe0-1a9fc19de932.jpg)

**Comment by pepeEL** [comment]
![screenshot_20181118-160019](https://user-images.githubusercontent.com/16692223/48674317-1445e680-eb4b-11e8-8e49-91adc5f4c9e4.jpg)

**Comment by pepeEL** [comment]
Very nice app

**Comment by estevez-dev** [comment]
Fixed by some other improvements. Will be released in 0.3.10
