### ISSUE TITLE
No slider for input number

### ISSUE THREAD

**Issue by Kvasenok** [estevez-dev/ha_client#200]
When using input number with Lovelace UI there is no slider in entity. If you click on a input number entity the slider is still there, it's just missing from the frontend. 
As far as I remember it used to work fine and sliders used to be present, so I guess the problem is with the latest 0.3.9 update. Probably has something to do with the long entity name fix.
![screenshot_20181119-013201](https://user-images.githubusercontent.com/44749170/48679072-af1ae100-eb9c-11e8-9e0f-d6dcf37172e9.jpg)
![screenshot_20181119-013212](https://user-images.githubusercontent.com/44749170/48679073-af1ae100-eb9c-11e8-8aba-e0e1fc0648b8.jpg)

**Comment by estevez-dev** [comment]
This was a planned change. That small slider was almost unusable. Maybe I'll add it back in form of popup, like for input_datetime.

**Comment by Kvasenok** [comment]
Oh, didn't think if that)
Great idea about the pop-up.

**Comment by estevez-dev** [comment]
HA Client was discontinued
