### ISSUE TITLE
Sensor Card support

### ISSUE THREAD

**Issue by estevez-dev** [estevez-dev/ha_client#220]

**Comment by pepeEL** [comment]
in web view show header of group name: UPS APC Synology but in app android not show. Some deviveces type sensor in app show double name as header and as name ex: Napięcie sieciowe, Nominana moc UPS
![ups](https://user-images.githubusercontent.com/16692223/49096977-11927200-f26c-11e8-8096-bacac9a9aead.jpg)

in app
![screenshot_20181127-173644](https://user-images.githubusercontent.com/16692223/49097075-50c0c300-f26c-11e8-9608-e196a9907e63.jpg)



This is my config lovelace
`##### URZĄDZENIA SIECIOWE #####
  - title: Urządzenia sieciowe
    icon: mdi:lan
    cards:
      - type: entities
        title: Prędkość Internetu
        entities:
          - entity: sensor.speedtest_download
            name: Download
          - entity: sensor.speedtest_upload
            name: Upload
          - entity: sensor.speedtest_ping
            name: Ping

      - type: entities
        title: Synology NAS
        entities:
          - entity: sensor.cpu_load_total
            name: Użycie CPU
          - entity: sensor.memory_usage_real
            name: Użycie pamięci RAM
          - entity: sensor.network_down
            name: LAN Download
          - entity: sensor.network_up
            name: LAN Upload
          - entity: sensor.status_smart_sda
            name: Status SMART HDD1
          - entity: sensor.status_smart_sdb
            name: Status SMART HDD2
          - entity: sensor.temperature_sda
            name: Temperatura HDD1
          - entity: sensor.temperature_sdb
            name: Temperatura HDD1

      - type: custom:vertical-stack-in-card
        title: UPS APC Synology
        cards:
          - type: entities
            show_header_toggle: false
            entities:
              - entity: sensor.ups_status
                name: Status UPSa
              - entity: sensor.ups_battery_charge
                name: Stan naładowania baterii
              - entity: sensor.ups_battery_runtime
                name: Czas potrzymania
          - type: gauge
            title: Obciążenie
            entity: sensor.ups_load
            severity:
              green: 0
              yellow: 40
              red: 70
          - type: sensor
            title: Napięcie sieci
            entity: sensor.ups_input_voltage
            line_color: '#FF6384'
            accuracy: 25
          - type: sensor
            title: Nominalna moc UPS
            entity: sensor.ups_nominal_real_power
            line_color: '#4BC0C0'
            accuracy: 25
`

**Comment by estevez-dev** [comment]
HA Client was discontinued
