### ISSUE TITLE
Thermostat Card support

### ISSUE THREAD

**Issue by estevez-dev** [estevez-dev/ha_client#221]

**Comment by klejejs** [comment]
Hi! I really appreciate your work and I know it takes a lot of time to build this app, but do you have an estimation, when the release 4.0 will be out?

**Comment by estevez-dev** [comment]
No, unfortunately there is no any estimation as I'm working on this app on my spare time, but my spare time is not stable )
I'm using thermostats too and want to implement this cards as soon as possible. It is not necessary it will be released with 4.0. It can be implemented earlier. Milestone 4.0 is a container of all issues that need to be implemented prior first stable release.

**Comment by klejejs** [comment]
Ok, thank you. Keep up the great work!

**Comment by estevez-dev** [comment]
HA Client was discontinued
