### ISSUE TITLE
Icons in the glance card

### ISSUE THREAD

**Issue by sgttrs** [estevez-dev/ha_client#223]
Icon size in the glance card is larger than in entities card
![screenshot_2018-11-19-19-25-58-1](https://user-images.githubusercontent.com/33804747/48710306-0e770080-ec32-11e8-9b23-c3c4c71b8f95.png)

**Comment by estevez-dev** [comment]
As designed. Why not?

**Comment by sgttrs** [comment]
It seems to me that icons of the same size will look better

**Comment by estevez-dev** [comment]
I'll try. But on the web glance card icons looks too small for me.

**Comment by sgttrs** [comment]
Ultimately, you decide. Thank you
