### ISSUE TITLE
Lovelace gauge wrong show

### ISSUE THREAD

**Issue by pepeEL** [estevez-dev/ha_client#229]
Hi
I have configure in my HA on interface Lovelace CPU use and ex temp CPU by type card Gauge. But in App show as header title from lovelace but for device show friendly name from custom. Yaml from old interface. 
![screenshot_20181123-105401](https://user-images.githubusercontent.com/16692223/48982611-298bb980-f0e5-11e8-8bc0-03635c9dd2a6.jpg)

This is my config lovelace:
`##### SYSTEM #####
  - title: System
    icon: mdi:gauge-low
    cards:
      - type: entities
        entities: 
          - entity: sensor.date__time
            name: Data i godzina
          - entity: sensor.sunrise
            name: Wschód słońca
            icon: mdi:weather-sunset-up
          - entity: sensor.sunset
            name: Zachód słońca
            icon: mdi:weather-sunset-down
          - type: divider
          - entity: sensor.wersja_home_assistant
            name: Wersja Home Assistant
          - entity: sensor.czas_pracy
            name: Czas pracy systemu
          - entity: sensor.last_boot
            name: Ostatnie uruchomienie systemu
      - type: horizontal-stack
        cards:
          - type: gauge
            title: Użycie procesora
            entity: sensor.processor_use
            severity:
              green: 0
              yellow: 40
              red: 70
          - type: gauge
            title: Temp. procesora
            entity: sensor.raspberry_cpu_temp
            severity:
              green: 0
              yellow: 45
              red: 80
          - type: gauge
            title: Użycie dysku SSD
            entity: sensor.disk_use_percent_
      - type: horizontal-stack
        cards:
          - type: gauge
            title: Użycie pamięci RAM
            entity: sensor.memory_use_percent
          - type: gauge
            title: Wolna pamięć RAM
            entity: sensor.memory_free
`

And config from custom.yaml old interface:
`sensor.disk_use_percent_:
  friendly_name: Użycie dysku
sensor.memory_free:
  friendly_name: Wolna pamięć
sensor.memory_use_percent:
  friendly_name: Użycie pamięci
sensor.raspberry_cpu_temp:
  friendly_name: Temperatura CPU RPi3
sensor.processor_use:
  friendly_name: Użycie procesora

`

**Comment by estevez-dev** [comment]
#208

**Comment by gpbipin** [comment]
Sorry to revive this, but is this reaolved? Im seeing the problem still. HA ver 0.95.4
Thanks.

**Comment by estevez-dev** [comment]
It is not supported yet, but planned in #208
