### ISSUE TITLE
Entity picture is missing

### ISSUE THREAD

**Issue by pepeEL** [estevez-dev/ha_client#234]
When media player is off icon is show correct. But when media player is on and example show playing icon for media player is not show. Is hidden.

**Comment by pepeEL** [comment]
![screenshot_20181129-195408](https://user-images.githubusercontent.com/16692223/49244790-e7c68000-f410-11e8-963d-34a1898060da.jpg)
![screenshot_20181129-195353](https://user-images.githubusercontent.com/16692223/49244794-ebf29d80-f410-11e8-8cc8-c4773356517c.jpg)

**Comment by estevez-dev** [comment]
Could you please show how it looks like on web UI while playing

**Comment by estevez-dev** [comment]
And what is a platform of this device?

**Comment by pepeEL** [comment]
Denon avr x2100w

**Comment by estevez-dev** [comment]
Ok, but I steel need a screenshots. One is the same as your first one, but when "Denon Salon" is playing. The second - a list of attributes for this entity, if it is possible. You can found it in the app when tapping on player, on the bottom part of entity page right under state history. Thanks a lot.

**Comment by pepeEL** [comment]
![screenshot_20190211-064528](https://user-images.githubusercontent.com/16692223/52548444-09a79000-2dce-11e9-8ffc-dc17f9a5541d.jpg)
![screenshot_20190211-064516](https://user-images.githubusercontent.com/16692223/52548450-0d3b1700-2dce-11e9-8b55-eb14f4f3934e.jpg)
![screenshot_20190211-064458](https://user-images.githubusercontent.com/16692223/52548455-11ffcb00-2dce-11e9-8410-d1f411aee678.jpg)
![screenshot_20190211-064449](https://user-images.githubusercontent.com/16692223/52548459-162be880-2dce-11e9-8962-228f2135fee2.jpg)
![screenshot_20190211-064323](https://user-images.githubusercontent.com/16692223/52548462-1af09c80-2dce-11e9-999f-1f31975b1bd5.jpg)
![screenshot_20190211-064257](https://user-images.githubusercontent.com/16692223/52548466-20e67d80-2dce-11e9-8f4c-702d46e38199.jpg)

**Comment by estevez-dev** [comment]
So it is not always missing right?
![screenshot-github com-2019 02 11-10-21-09](https://user-images.githubusercontent.com/1819786/52551839-c9a0d700-2de6-11e9-9426-c53c48148f76.png)

**Comment by pepeEL** [comment]
Always... look
![52548466-20e67d80-2dce-11e9-8f4c-702d46e38199](https://user-images.githubusercontent.com/16692223/52552099-55166a00-2ddf-11e9-942f-f1dcbb0e048d.jpg)

**Comment by estevez-dev** [comment]
Ah, so it is missed on the card, but presented when opening entity controls?

**Comment by pepeEL** [comment]
Yes.

**Comment by estevez-dev** [comment]
Looks like this issue is not relates to media player. It is related to entity picture. Sometimes it is not displayed. I saw this issue  sometime ago with camera entity.
