### ISSUE TITLE
Slider lovelace for cover and other

### ISSUE THREAD

**Issue by pepeEL** [estevez-dev/ha_client#238]
I use slider for cover from this link:
https://github.com/thomasloven/lovelace-slider-entity-row

But when i configure it in web view slider looks ok:
![49374363-61a48500-f701-11e8-8374-0857ad1a6d6b](https://user-images.githubusercontent.com/16692223/49374538-ed1e1600-f701-11e8-93bc-96365d9e4553.jpg)

but in app no looks good because show it as double (clone) devices.... Look:
![screenshot_20181203-134405](https://user-images.githubusercontent.com/16692223/49374573-1048c580-f702-11e8-9825-e332153ee038.jpg)

**Comment by estevez-dev** [comment]
Custom UI components is not supported at all

**Comment by pepeEL** [comment]
But you are planing suppoort it ? Many user use custom UI components...

**Comment by estevez-dev** [comment]
Maybe in future I will support most popular of them
