### ISSUE TITLE
Local CA is skipped

### ISSUE THREAD

**Issue by LukasQ** [estevez-dev/ha_client#240]
I proxy everything through an NGINEX instance to use default ports plus a local CA.

When I try to connect, I get a ‘CERTIFICATE_VERIFY_FAILED’ exception.
Local root CA is installed in the phones cert store, so I assume the client does not check this.
https://host.tld works in Android Chrome without cert warning. As I understand, not related to #181, as it's working without CA warn in Android Chrome

**Comment by estevez-dev** [comment]
It is related to #180 and Flutter framework self-signet certificates issues. Still not resolved =(

**Comment by LukasQ** [comment]
So the workarround for now ist to downgrade to http, right?

**Comment by estevez-dev** [comment]
Right

**Comment by pstaubs** [comment]
Any updates on this issue? No HTTPS support is a deal killer.

**Comment by estevez-dev** [comment]
I'll take this issue to investigation. May be there is already some solution for Flutter apps. Stay tuned ;-)

**Comment by estevez-dev** [comment]
Merging this issue with #180
