### ISSUE TITLE
Error in 0.84.1 (tap_action and hold_action parsing issue)

### ISSUE THREAD

**Issue by Klagio** [estevez-dev/ha_client#248]
That's the log

1213 20:53:22 [Debug] :  <!!!> Creating new HomeAssistant instance
1213 20:53:22 [Debug] :  AppLifecycleState.inactive
1213 20:53:22 [Debug] :  AppLifecycleState.resumed
1213 20:53:22 [Debug] :  Use lovelace is true
1213 20:53:22 [Debug] :  Socket connecting...
1213 20:53:22 [Error] :  Invalid argument(s): 56.0
1213 20:53:22 [Error] :  NoSuchMethodError: The getter 'scrollOffsetCorrection' was called on null.
Receiver: null
Tried calling: scrollOffsetCorrection
1213 20:53:22 [Error] :  NoSuchMethodError: The getter 'visible' was called on null.
Receiver: null
Tried calling: visible
1213 20:53:22 [Debug] :  [Sending] ==> auth request
1213 20:53:22 [Debug] :  [Sending] ==> {"id": 1, "type": "subscribe_events", "event_type": "state_changed"}
1213 20:53:22 [Debug] :  [Sending] ==> {"id": 2, "type": "get_states"}
1213 20:53:22 [Debug] :  [Sending] ==> {"id": 3, "type": "lovelace/config"}
1213 20:53:22 [Debug] :  [Sending] ==> {"id": 4, "type": "get_config"}
1213 20:53:22 [Debug] :  [Sending] ==> {"id": 5, "type": "get_services"}
1213 20:53:22 [Debug] :  [Sending] ==> {"id": 6, "type": "auth/current_user"}
1213 20:53:22 [Debug] :  [Received] <== id:1, error
1213 20:53:22 [Debug] :  [Received] <== id:2, error
1213 20:53:22 [Debug] :  [Received] <== id:4, success
1213 20:53:22 [Debug] :  [Received] <== id:5, success
1213 20:53:22 [Debug] :  [Received] <== id:6, error
1213 20:53:22 [Warning] :  There was an error getting current user: {id: 6, type: result, success: false, error: {code: no_user, message: Not authenticated as a user}}
1213 20:53:22 [Debug] :  [Received] <== id:3, success
1213 20:53:32 [Debug] :  Settings was not changed
1213 20:53:35 [Debug] :  Use lovelace is true
1213 20:53:35 [Debug] :  [Sending] ==> {"id": 7, "type": "get_states"}
1213 20:53:35 [Debug] :  [Sending] ==> {"id": 8, "type": "lovelace/config"}
1213 20:53:35 [Debug] :  [Sending] ==> {"id": 9, "type": "get_config"}
1213 20:53:35 [Debug] :  [Sending] ==> {"id": 10, "type": "get_services"}
1213 20:53:35 [Debug] :  [Sending] ==> {"id": 11, "type": "auth/current_user"}
1213 20:53:35 [Debug] :  [Received] <== id:7, error
1213 20:53:35 [Debug] :  [Received] <== id:9, success
1213 20:53:35 [Debug] :  [Received] <== id:11, error
1213 20:53:35 [Warning] :  There was an error getting current user: {id: 11, type: result, success: false, error: {code: no_user, message: Not authenticated as a user}}
1213 20:53:35 [Debug] :  [Received] <== id:10, success
1213 20:53:35 [Debug] :  [Received] <== id:8, success

**Comment by estevez-dev** [comment]
Looks like an issue with authentication that is not handled properly. Do you use legacy password or acess token?

**Comment by Klagio** [comment]
I had the password
Now I put a token
1213 21:40:59 [Debug] :  Use lovelace is true
1213 21:40:59 [Debug] :  [Sending] ==> {"id": 33, "type": "get_states"}
1213 21:40:59 [Debug] :  [Sending] ==> {"id": 34, "type": "lovelace/config"}
1213 21:40:59 [Debug] :  [Sending] ==> {"id": 35, "type": "get_config"}
1213 21:40:59 [Debug] :  [Sending] ==> {"id": 36, "type": "get_services"}
1213 21:40:59 [Debug] :  [Sending] ==> {"id": 37, "type": "auth/current_user"}
1213 21:41:00 [Debug] :  [Received] <== id:33, success
1213 21:41:00 [Debug] :  Parsing 1316 Home Assistant entities
1213 21:41:00 [Debug] :  [Received] <== id:35, success
1213 21:41:00 [Debug] :  [Received] <== id:36, success
1213 21:41:00 [Debug] :  [Received] <== id:37, success
1213 21:41:00 [Debug] :  [Received] <== id:34, success
1213 21:41:00 [Debug] :  Creating Lovelace UI
1213 21:41:00 [Debug] :  --Title: null
1213 21:41:00 [Debug] :  --Views count: 10
1213 21:41:00 [Debug] :  ----view id: 0
1213 21:41:00 [Error] :  type '_InternalLinkedHashMap<String, dynamic>' is not a subtype of type 'String'
1213 21:41:00 [Error] :  #0      HomeAssistant._createLovelaceCards.<anonymous closure>.<anonymous closure> (file:///D:/src/hass_client/lib/home_assistant.class.dart:453)
#1      _GrowableList.forEach (dart:core/runtime/libgrowable_array.dart:278)
#2      HomeAssistant._createLovelaceCards.<anonymous closure> (file:///D:/src/hass_client/lib/home_assistant.class.dart:442)
#3      _GrowableList.forEach (dart:core/runtime/libgrowable_array.dart:278)
#4      HomeAssistant._createLovelaceCards (file:///D:/src/hass_client/lib/home_assistant.class.dart:430)
#5      HomeAssistant._createLovelaceCards.<anonymous closure> (file:///D:/src/hass_client/lib/home_assistant.class.dart:432)
#6      _GrowableList.forEach (dart:core/runtime/libgrowable_array.dart:278)
#7      HomeAssistant._createLovelaceCards (file:///D:/src/hass_client/lib/home_assistant.class.dart:430)
#8      HomeAssistant._parseLovelace.<anonymous closure> (file:///D:/src/hass_client/lib/home_assistant.class.dart:420)
#9      _GrowableList.forEach (dart:core/runtime/libgrowable_array.dart:278)
#10     HomeAssistant._parseLovelace (file:///D:/src/hass_client/lib/home_assistant.class.dart:412)
#11     HomeAssistant._createUI (file:///D:/src/hass_client/lib/home_assistant.class.dart:506)
#12     HomeAssistant._getData (file:///D:/src/hass_client/lib/home_assistant.class.dart:174)
<asynchronous suspension>
#13     HomeAssistant.fetch.<anonymous closure> (file:///D:/src/hass_client/lib/home_assistant.class.dart:82)
#14     _rootRunUnary (dart:async/zone.dart:1132)
#15     _CustomZone.runUnary (dart:async/zone.dart:1029)
#16     _FutureListener.handleValue (dart:async/future_impl.dart:129)
#17     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642)
#18     Future._propagateToListeners (dart:async/future_impl.dart:671)
#19     Future._addListener.<anonymous closure> (dart:async/future_impl.dart:351)
#20     _rootRun (dart:async/zone.dart:1124)
#21     _CustomZone.run (dart:async/zone.dart:1021)
#22     _CustomZone.runGuarded (dart:async/zone.dart:923)
#23     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963)
#24     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#25     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)

1213 21:41:00 [Debug] :  [Received] <== event.state_changed: sensor.oven_voltage
1213 21:41:01 [Debug] :  Use lovelace is true
1213 21:41:01 [Debug] :  [Sending] ==> {"id": 38, "type": "get_states"}
1213 21:41:01 [Debug] :  [Sending] ==> {"id": 39, "type": "lovelace/config"}
1213 21:41:01 [Debug] :  [Sending] ==> {"id": 40, "type": "get_config"}
1213 21:41:01 [Debug] :  [Sending] ==> {"id": 41, "type": "get_services"}
1213 21:41:01 [Debug] :  [Sending] ==> {"id": 42, "type": "auth/current_user"}
1213 21:41:01 [Debug] :  [Received] <== id:38, success
1213 21:41:01 [Debug] :  Parsing 1316 Home Assistant entities
1213 21:41:01 [Debug] :  [Received] <== id:40, success
1213 21:41:01 [Debug] :  [Received] <== id:41, success
1213 21:41:01 [Debug] :  [Received] <== id:42, success
1213 21:41:01 [Debug] :  [Received] <== id:39, success
1213 21:41:01 [Debug] :  Creating Lovelace UI
1213 21:41:01 [Debug] :  --Title: null
1213 21:41:01 [Debug] :  --Views count: 10
1213 21:41:01 [Debug] :  ----view id: 0
1213 21:41:01 [Error] :  type '_InternalLinkedHashMap<String, dynamic>' is not a subtype of type 'String'
1213 21:41:01 [Error] :  #0      HomeAssistant._createLovelaceCards.<anonymous closure>.<anonymous closure> (file:///D:/src/hass_client/lib/home_assistant.class.dart:453)
#1      _GrowableList.forEach (dart:core/runtime/libgrowable_array.dart:278)
#2      HomeAssistant._createLovelaceCards.<anonymous closure> (file:///D:/src/hass_client/lib/home_assistant.class.dart:442)
#3      _GrowableList.forEach (dart:core/runtime/libgrowable_array.dart:278)
#4      HomeAssistant._createLovelaceCards (file:///D:/src/hass_client/lib/home_assistant.class.dart:430)
#5      HomeAssistant._createLovelaceCards.<anonymous closure> (file:///D:/src/hass_client/lib/home_assistant.class.dart:432)
#6      _GrowableList.forEach (dart:core/runtime/libgrowable_array.dart:278)
#7      HomeAssistant._createLovelaceCards (file:///D:/src/hass_client/lib/home_assistant.class.dart:430)
#8      HomeAssistant._parseLovelace.<anonymous closure> (file:///D:/src/hass_client/lib/home_assistant.class.dart:420)
#9      _GrowableList.forEach (dart:core/runtime/libgrowable_array.dart:278)
#10     HomeAssistant._parseLovelace (file:///D:/src/hass_client/lib/home_assistant.class.dart:412)
#11     HomeAssistant._createUI (file:///D:/src/hass_client/lib/home_assistant.class.dart:506)
#12     HomeAssistant._getData (file:///D:/src/hass_client/lib/home_assistant.class.dart:174)
<asynchronous suspension>
#13     HomeAssistant.fetch.<anonymous closure> (file:///D:/src/hass_client/lib/home_assistant.class.dart:82)
#14     _rootRunUnary (dart:async/zone.dart:1132)
#15     _CustomZone.runUnary (dart:async/zone.dart:1029)
#16     _FutureListener.handleValue (dart:async/future_impl.dart:129)
#17     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642)
#18     Future._propagateToListeners (dart:async/future_impl.dart:671)
#19     Future._addListener.<anonymous closure> (dart:async/future_impl.dart:351)
#20     _rootRun (dart:async/zone.dart:1124)
#21     _CustomZone.run (dart:async/zone.dart:1021)
#22     _CustomZone.runGuarded (dart:async/zone.dart:923)
#23     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963)
#24     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#25     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)

1213 21:41:02 [Debug] :  Use lovelace is true
1213 21:41:02 [Debug] :  [Sending] ==> {"id": 43, "type": "get_states"}
1213 21:41:02 [Debug] :  [Sending] ==> {"id": 44, "type": "lovelace/config"}
1213 21:41:02 [Debug] :  [Sending] ==> {"id": 45, "type": "get_config"}
1213 21:41:02 [Debug] :  [Sending] ==> {"id": 46, "type": "get_services"}
1213 21:41:02 [Debug] :  [Sending] ==> {"id": 47, "type": "auth/current_user"}
1213 21:41:02 [Debug] :  [Received] <== id:43, success
1213 21:41:02 [Debug] :  Parsing 1316 Home Assistant entities
1213 21:41:02 [Debug] :  [Received] <== id:45, success
1213 21:41:02 [Debug] :  [Received] <== id:46, success
1213 21:41:02 [Debug] :  [Received] <== id:47, success
1213 21:41:02 [Debug] :  [Received] <== id:44, success
1213 21:41:02 [Debug] :  [Received] <== event.state_changed: binary_sensor.ping_gateway_corridor
1213 21:41:02 [Debug] :  Creating Lovelace UI
1213 21:41:02 [Debug] :  --Title: null
1213 21:41:02 [Debug] :  --Views count: 10
1213 21:41:02 [Debug] :  ----view id: 0
1213 21:41:02 [Error] :  type '_InternalLinkedHashMap<String, dynamic>' is not a subtype of type 'String'
1213 21:41:02 [Error] :  #0      HomeAssistant._createLovelaceCards.<anonymous closure>.<anonymous closure> (file:///D:/src/hass_client/lib/home_assistant.class.dart:453)
#1      _GrowableList.forEach (dart:core/runtime/libgrowable_array.dart:278)
#2      HomeAssistant._createLovelaceCards.<anonymous closure> (file:///D:/src/hass_client/lib/home_assistant.class.dart:442)
#3      _GrowableList.forEach (dart:core/runtime/libgrowable_array.dart:278)
#4      HomeAssistant._createLovelaceCards (file:///D:/src/hass_client/lib/home_assistant.class.dart:430)
#5      HomeAssistant._createLovelaceCards.<anonymous closure> (file:///D:/src/hass_client/lib/home_assistant.class.dart:432)
#6      _GrowableList.forEach (dart:core/runtime/libgrowable_array.dart:278)
#7      HomeAssistant._createLovelaceCards (file:///D:/src/hass_client/lib/home_assistant.class.dart:430)
#8      HomeAssistant._parseLovelace.<anonymous closure> (file:///D:/src/hass_client/lib/home_assistant.class.dart:420)
#9      _GrowableList.forEach (dart:core/runtime/libgrowable_array.dart:278)
#10     HomeAssistant._parseLovelace (file:///D:/src/hass_client/lib/home_assistant.class.dart:412)
#11     HomeAssistant._createUI (file:///D:/src/hass_client/lib/home_assistant.class.dart:506)
#12     HomeAssistant._getData (file:///D:/src/hass_client/lib/home_assistant.class.dart:174)
<asynchronous suspension>
#13     HomeAssistant.fetch.<anonymous closure> (file:///D:/src/hass_client/lib/home_assistant.class.dart:82)
#14     _rootRunUnary (dart:async/zone.dart:1132)
#15     _CustomZone.runUnary (dart:async/zone.dart:1029)
#16     _FutureListener.handleValue (dart:async/future_impl.dart:129)
#17     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642)
#18     Future._propagateToListeners (dart:async/future_impl.dart:671)
#19     Future._addListener.<anonymous closure> (dart:async/future_impl.dart:351)
#20     _rootRun (dart:async/zone.dart:1124)
#21     _CustomZone.run (dart:async/zone.dart:1021)
#22     _CustomZone.runGuarded (dart:async/zone.dart:923)
#23     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963)
#24     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#25     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)

1213 21:41:03 [Debug] :  Use lovelace is true
1213 21:41:03 [Debug] :  [Sending] ==> {"id": 48, "type": "get_states"}
1213 21:41:03 [Debug] :  [Sending] ==> {"id": 49, "type": "lovelace/config"}
1213 21:41:03 [Debug] :  [Sending] ==> {"id": 50, "type": "get_config"}
1213 21:41:03 [Debug] :  [Sending] ==> {"id": 51, "type": "get_services"}
1213 21:41:03 [Debug] :  [Sending] ==> {"id": 52, "type": "auth/current_user"}
1213 21:41:03 [Debug] :  [Received] <== id:48, success
1213 21:41:03 [Debug] :  Parsing 1316 Home Assistant entities
1213 21:41:03 [Debug] :  [Received] <== id:50, success
1213 21:41:03 [Debug] :  [Received] <== id:51, success
1213 21:41:03 [Debug] :  [Received] <== id:52, success
1213 21:41:03 [Debug] :  [Received] <== id:49, success
1213 21:41:03 [Debug] :  Creating Lovelace UI
1213 21:41:03 [Debug] :  --Title: null
1213 21:41:03 [Debug] :  --Views count: 10
1213 21:41:03 [Debug] :  ----view id: 0
1213 21:41:03 [Error] :  type '_InternalLinkedHashMap<String, dynamic>' is not a subtype of type 'String'
1213 21:41:03 [Error] :  #0      HomeAssistant._createLovelaceCards.<anonymous closure>.<anonymous closure> (file:///D:/src/hass_client/lib/home_assistant.class.dart:453)
#1      _GrowableList.forEach (dart:core/runtime/libgrowable_array.dart:278)
#2      HomeAssistant._createLovelaceCards.<anonymous closure> (file:///D:/src/hass_client/lib/home_assistant.class.dart:442)
#3      _GrowableList.forEach (dart:core/runtime/libgrowable_array.dart:278)
#4      HomeAssistant._createLovelaceCards (file:///D:/src/hass_client/lib/home_assistant.class.dart:430)
#5      HomeAssistant._createLovelaceCards.<anonymous closure> (file:///D:/src/hass_client/lib/home_assistant.class.dart:432)
#6      _GrowableList.forEach (dart:core/runtime/libgrowable_array.dart:278)
#7      HomeAssistant._createLovelaceCards (file:///D:/src/hass_client/lib/home_assistant.class.dart:430)
#8      HomeAssistant._parseLovelace.<anonymous closure> (file:///D:/src/hass_client/lib/home_assistant.class.dart:420)
#9      _GrowableList.forEach (dart:core/runtime/libgrowable_array.dart:278)
#10     HomeAssistant._parseLovelace (file:///D:/src/hass_client/lib/home_assistant.class.dart:412)
#11     HomeAssistant._createUI (file:///D:/src/hass_client/lib/home_assistant.class.dart:506)
#12     HomeAssistant._getData (file:///D:/src/hass_client/lib/home_assistant.class.dart:174)
<asynchronous suspension>
#13     HomeAssistant.fetch.<anonymous closure> (file:///D:/src/hass_client/lib/home_assistant.class.dart:82)
#14     _rootRunUnary (dart:async/zone.dart:1132)
#15     _CustomZone.runUnary (dart:async/zone.dart:1029)
#16     _FutureListener.handleValue (dart:async/future_impl.dart:129)
#17     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642)
#18     Future._propagateToListeners (dart:async/future_impl.dart:671)
#19     Future._addListener.<anonymous closure> (dart:async/future_impl.dart:351)
#20     _rootRun (dart:async/zone.dart:1124)
#21     _CustomZone.run (dart:async/zone.dart:1021)
#22     _CustomZone.runGuarded (dart:async/zone.dart:923)
#23     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963)
#24     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#25     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)

1213 21:41:04 [Debug] :  [Received] <== event.state_changed: switch.light_kitchen
1213 21:41:04 [Debug] :  [Received] <== event.state_changed: group.living_dining_room
1213 21:41:04 [Debug] :  Use lovelace is true
1213 21:41:04 [Debug] :  [Sending] ==> {"id": 53, "type": "get_states"}
1213 21:41:04 [Debug] :  [Sending] ==> {"id": 54, "type": "lovelace/config"}
1213 21:41:04 [Debug] :  [Sending] ==> {"id": 55, "type": "get_config"}
1213 21:41:04 [Debug] :  [Sending] ==> {"id": 56, "type": "get_services"}
1213 21:41:04 [Debug] :  [Sending] ==> {"id": 57, "type": "auth/current_user"}
1213 21:41:05 [Debug] :  [Received] <== id:53, success
1213 21:41:05 [Debug] :  Parsing 1316 Home Assistant entities
1213 21:41:05 [Debug] :  [Received] <== id:55, success
1213 21:41:05 [Debug] :  [Received] <== id:56, success
1213 21:41:05 [Debug] :  [Received] <== id:57, success
1213 21:41:05 [Debug] :  [Received] <== id:54, success
1213 21:41:05 [Debug] :  Creating Lovelace UI
1213 21:41:05 [Debug] :  --Title: null
1213 21:41:05 [Debug] :  --Views count: 10
1213 21:41:05 [Debug] :  ----view id: 0
1213 21:41:05 [Error] :  type '_InternalLinkedHashMap<String, dynamic>' is not a subtype of type 'String'
1213 21:41:05 [Error] :  #0      HomeAssistant._createLovelaceCards.<anonymous closure>.<anonymous closure> (file:///D:/src/hass_client/lib/home_assistant.class.dart:453)
#1      _GrowableList.forEach (dart:core/runtime/libgrowable_array.dart:278)
#2      HomeAssistant._createLovelaceCards.<anonymous closure> (file:///D:/src/hass_client/lib/home_assistant.class.dart:442)
#3      _GrowableList.forEach (dart:core/runtime/libgrowable_array.dart:278)
#4      HomeAssistant._createLovelaceCards (file:///D:/src/hass_client/lib/home_assistant.class.dart:430)
#5      HomeAssistant._createLovelaceCards.<anonymous closure> (file:///D:/src/hass_client/lib/home_assistant.class.dart:432)
#6      _GrowableList.forEach (dart:core/runtime/libgrowable_array.dart:278)
#7      HomeAssistant._createLovelaceCards (file:///D:/src/hass_client/lib/home_assistant.class.dart:430)
#8      HomeAssistant._parseLovelace.<anonymous closure> (file:///D:/src/hass_client/lib/home_assistant.class.dart:420)
#9      _GrowableList.forEach (dart:core/runtime/libgrowable_array.dart:278)
#10     HomeAssistant._parseLovelace (file:///D:/src/hass_client/lib/home_assistant.class.dart:412)
#11     HomeAssistant._createUI (file:///D:/src/hass_client/lib/home_assistant.class.dart:506)
#12     HomeAssistant._getData (file:///D:/src/hass_client/lib/home_assistant.class.dart:174)
<asynchronous suspension>
#13     HomeAssistant.fetch.<anonymous closure> (file:///D:/src/hass_client/lib/home_assistant.class.dart:82)
#14     _rootRunUnary (dart:async/zone.dart:1132)
#15     _CustomZone.runUnary (dart:async/zone.dart:1029)
#16     _FutureListener.handleValue (dart:async/future_impl.dart:129)
#17     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642)
#18     Future._propagateToListeners (dart:async/future_impl.dart:671)
#19     Future._addListener.<anonymous closure> (dart:async/future_impl.dart:351)
#20     _rootRun (dart:async/zone.dart:1124)
#21     _CustomZone.run (dart:async/zone.dart:1021)
#22     _CustomZone.runGuarded (dart:async/zone.dart:923)
#23     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963)
#24     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#25     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)

1213 21:41:05 [Debug] :  [Received] <== event.state_changed: automation.main_daily_energy
1213 21:41:05 [Debug] :  [Received] <== event.state_changed: sensor.today_main_kwh
1213 21:41:05 [Debug] :  [Received] <== event.state_changed: automation.sensor_values_to_file
1213 21:41:07 [Debug] :  [Received] <== event.state_changed: binary_sensor.ping_efergy
1213 21:41:08 [Debug] :  [Received] <== event.state_changed: sensor.router_current
1213 21:41:08 [Debug] :  [Received] <== event.state_changed: sensor.router_voltage

**Comment by estevez-dev** [comment]
Ah I see now. Relates to #249 
Working on fix
