### ISSUE TITLE
APK

### ISSUE THREAD

**Issue by quthla** [estevez-dev/ha_client#251]
Can you maybe publish the apk here so it can be downloaded easily without the need to join the Google group?

**Comment by estevez-dev** [comment]
It will be available for easy download when it will become stable. For now it is only alpha version and needs testers.

**Comment by estevez-dev** [comment]
Starting from the next version apk will be available in [releases](https://github.com/estevez-dev/ha_client/releases)

**Comment by quthla** [comment]
Ok thank you. I also thought about contributing as there's still a lot to be done but I never worked with flutter.

**Comment by estevez-dev** [comment]
Me too )) This is my first Flutter app :-)

**Comment by quthla** [comment]
Are you on home assistant discord? We could have a chat maybe
