### ISSUE TITLE
Custom sensor incorrect display 

### ISSUE THREAD

**Issue by kvvoff** [estevez-dev/ha_client#253]
Custom sensor incorrectly shows the state - it is stretched almost the entire screen. Below is an example of display in mobile chrome, desktop chrome and in the HA Client.

HA Client:
![app_custom](https://user-images.githubusercontent.com/38342171/49999530-267b3f00-ffa8-11e8-8a2c-2cf5ba728e8a.png)

Display in mobile chrome:
![chrome_custom](https://user-images.githubusercontent.com/38342171/49999501-12cfd880-ffa8-11e8-8885-1cb99a270e6f.png)

Display in desktop chrome:
![desktop_custom](https://user-images.githubusercontent.com/38342171/49999552-34c95b00-ffa8-11e8-9065-830df69cabd6.png)

Here is the code in the sensors.yaml:

```
# Аптайм raspberry кастом
- platform: template
  sensors:
    uptime_hass_rpi_custom:
      icon_template: mdi:clock
      value_template: >
        {% set uptime = states.sensor.uptime_hass_rpi.state | int %}
        {% set minutes = (( uptime % 60) / 1) | int %}
        {% set hours = ((uptime % 1440) / 60) | int %}
        {% set days = (uptime / 1440) | int %}
          {% if uptime < 1 %}
            Меньше минуты
          {% else %}
            {% if days > 0 %}
              {{ days }} д.
            {% endif %}
            {% if hours > 0 %}
              {% if days > 0 %}
                {{ ' ' }}
              {% endif %}
              {{ hours }} ч.
            {% endif %}
            {% if minutes > 0 %}
              {% if days > 0 or hours > 0 %}
                {{ ' ' }}
              {% endif %}
                {{ minutes }} мин.
            {% endif %}
          {% endif %}

```

**Comment by estevez-dev** [comment]
Oh looks like I need to trim spaces ) Thanks.
