### ISSUE TITLE
When clicking on the UP sign of a thermostat strange behaviour 

### ISSUE THREAD

**Issue by Klagio** [estevez-dev/ha_client#257]
Clicking on the UP sign (singular) it went from 24 to 127 degree Celsius!

A minor bug. I would eliminate the single UP/DOWN symbol in the climate card, since it increments/decrement by 0,1 degree which I don't think is needed (the double sign increments by 0,5 degree which is enough.

**Comment by estevez-dev** [comment]
What is the minimum, maximum temp and temp step for your thermostat?
