### ISSUE TITLE
Timer support

### ISSUE THREAD

**Issue by Kvasenok** [estevez-dev/ha_client#258]
There is an icon missing for the timer entity. It's not a big deal since it can be replaced with a any other icon and it should solve the problem, but it is still a bug that needs to be fixed.

Also, the timer card in the app shows only states, e.g. idle, active etc. and doesn't show the actual timer when it's running. 
Although, there is seems to be a bug in HA as the "remaining" parameter won't update in HA frontend, but it is still dynamically shown in the right part of the card.

![screenshot_20181218-204654_chrome](https://user-images.githubusercontent.com/44749170/50172754-ca494f80-0306-11e9-89d3-6f63e72a28fb.jpg)
![screenshot_20181218-204800_chrome](https://user-images.githubusercontent.com/44749170/50172756-cae1e600-0306-11e9-864e-2638345b0014.jpg)
![screenshot_20181218-205044](https://user-images.githubusercontent.com/44749170/50172776-d33a2100-0306-11e9-81df-82b36efde03b.jpg)
![screenshot_20181218-205126](https://user-images.githubusercontent.com/44749170/50172777-d3d2b780-0306-11e9-9956-e9ba8e7a10b6.jpg)

**Comment by estevez-dev** [comment]
Turns out this is an unsupported component yet. Will be implemented in future.
https://www.home-assistant.io/components/timer/
