### ISSUE TITLE
Update MDI

### ISSUE THREAD

**Issue by kvvoff** [estevez-dev/ha_client#260]
Devices like "zwave.nodename" do not display icons:

HA Client:
![screenshot_20181228-102053](https://user-images.githubusercontent.com/38342171/50506714-44a66c00-0a8b-11e9-9acf-1c58da494c79.png)

Desktop Chrome:
![2018-12-28 10 21 16](https://user-images.githubusercontent.com/38342171/50506749-5e47b380-0a8b-11e9-8625-49e656e8dbdb.png)

**Comment by estevez-dev** [comment]
Material design icons library should be updated
