### ISSUE TITLE
Color picker improvements

### ISSUE THREAD

**Issue by estevez-dev** [estevez-dev/ha_client#273]
Need to replace color picker with something similar to HA web and most of smart lights apps.

Selected color on the picker should correspond to current light color

**Comment by Klagio** [comment]
Actually I kind of like the current solution :)

**Comment by Klagio** [comment]
Ahh well yes I understand now, of course too many palette types is also not good to have, so maybe the classic colour palette is the way to go , for all RGB lights.

What I would liek is the differentiation between RGB and cold/warm white
