### ISSUE TITLE
Publish on F-Droid

### ISSUE THREAD

**Issue by Preisschild** [estevez-dev/ha_client#275]
Can we work on getting this published on F-Droid?

Does the App require Google Apps?
Does the App require binary blobs?
Is the App completely Open-Source?

**Comment by estevez-dev** [comment]
Do you really need it there?

**Comment by Preisschild** [comment]
Well, many people use Android without using stuff from Google. Those people use F-Droid as Appstore.

I'm just interested if ha_client meets the inclusion crtieria: https://f-droid.org/en/docs/Inclusion_Policy/
Maybe someone else can work on publishing it there if you have other priorities.

**Comment by estevez-dev** [comment]
Actually it is not a problem I think. I will review the requirements and handle this.
Anyway, you can always download an .apk right here: https://github.com/estevez-dev/ha_client/releases

**Comment by Preisschild** [comment]
Thanks! Thats awesome as Maxr1998/home-assistant-Android seems to be stalled on development.

**Comment by Preisschild** [comment]
https://gitlab.com/fdroid/fdroiddata/blob/master/CONTRIBUTING.md#merge-requests
This seems to be a good documentation on where to get started.

**Comment by rradar** [comment]
I think it's even **important** to have the official open source number 1 home automatisation app in the number 1 foss app store!

As right now there is only this app (even looking somehow official) https://f-droid.org/en/packages/io.homeassistant.android/ if you search for home assistant in the F-Droid app store.

Once set up:
- https://f-droid.org/en/forums/topic/adding-apps-with-git/ 
- https://gitlab.com/fdroid/fdroiddata/blob/master/CONTRIBUTING.md#after-you-added-your-app

it's a fire and **forget** :fire: :fast_forward:

**Comment by estevez-dev** [comment]
In progress

**Comment by rradar** [comment]
:heart:

**Comment by rradar** [comment]
:zap: anti stale bot :robot:

**Comment by estevez-dev** [comment]
I have some update.
Unfortunately HA Client does not match the [Inclusion Policy of F-Droid](https://f-droid.org/docs/Inclusion_Policy/) =(
There is a lot of work should be done to make it available for inclusion. May be I'll do this in future.

**Comment by rradar** [comment]
What exactly is the problem which breaks the inclusion policy?

And could be apk's be released again in the meantime? #516 

So painful to see a great FOSS project like Home Assistant (and probably this official app) not supporting the biggest FOSS app store... :disappointed:

**Comment by rradar** [comment]
[Most upvoted issue ever (ha-client)
](https://github.com/estevez-dev/ha_client/issues?q=sort%3Areactions-%2B1-desc+)

![image](https://user-images.githubusercontent.com/34582688/80322107-9a735b80-881a-11ea-83ae-c2216c98f3cb.png)

**Comment by estevez-dev** [comment]
Hi @rradar 
apk files can be downloaded from [releases](https://github.com/estevez-dev/ha_client/releases) starting from 0.8.2.

HA Client is not an official app.

HA Client can't be included in F-Droid because I'm using non-FOSS components like [Syncfuxion widgets](https://www.syncfusion.com/flutter-widgets)

**Comment by estevez-dev** [comment]
Closing as unattainable
