### ISSUE TITLE
Add "Trigger" button to alarm_control_panel controls

### ISSUE THREAD

**Issue by estevez-dev** [estevez-dev/ha_client#282]
Additional flat button to trigger the alarm immediately.

**Comment by Klagio** [comment]
Great!

Just a word of caution, you do not want that while scrolling the page, inadvertedly you trigger the alarm: so maybe a functionality like more-info is better (you click on it, after the first click it comes a button/slider where you can click/slide it, and only then it triggers ther alarm)

**Comment by estevez-dev** [comment]
Differently I will not add it to "alarm panel" card. It will be in more-info dialog.
And you are right, we need "more-info" button somewhere on "alarm panel"

**Comment by Klagio** [comment]
The solution as is works for me, a bit less for my wife and people less techie: now to trigger the alarm you need to press the small 3 dots, then click on the small trigger sign and then click yes.
Maybe better  put an additional button with written Trigger (of course keeping the second popup for confirmation yes or no)?

Again its a minor thing to a perfect app.

**Comment by estevez-dev** [comment]
May be, but Alarm panel card is already have too much buttons. But I'll see what I can do.

**Comment by pepeEL** [comment]
But how i can use it i HA ?

**Comment by Klagio** [comment]
> But how i can use it i HA ?

you need to have the alarm setup in Home Assistant first, then you will see it in the app: the app is just front-end visualization of the server side

**Comment by pepeEL** [comment]
Ok i have alarm Satel with ETHM-1 Plus. But trigger will work to activate alarm ?

**Comment by pepeEL** [comment]
But you mean that it activate PANIC ALARM ?

**Comment by estevez-dev** [comment]
It will call 'alarm_control_panel.alarm_trigger' service in HA. All other depends on your alarm platform.

**Comment by estevez-dev** [comment]
> For me not activate panic alarm. How i can configure it to work as panic alarm ?

I don't know. Ask HA community.
