### ISSUE TITLE
Hue colour bulb shows only brightness and colour palette but not warm/cold white slider 

### ISSUE THREAD

**Issue by Klagio** [estevez-dev/ha_client#284]
This applies to the Hue colour bulb.

In HASS you can correctly choose all 3 (palette, brightness and warm/cold white)

**Comment by Klagio** [comment]
Strangely I have a different Hue color bulb for which is possible to change brightness and warm/cold white, but not colour palette

**Comment by estevez-dev** [comment]
Could you please tell me `supported_features` attribute value for both of them

**Comment by Klagio** [comment]
One is from Jiiawen: supported feautures 63 (palette+brightness) ==== NOT OK
One is from HUE: supported feautures 63 (palette+brightness) ====   NOT OK
One is from HUE: supported feautures 63 (palette+brightness+cold/warm white) ====  OK

strange, maybe those from Hue are different series, I do not remember

**Comment by estevez-dev** [comment]
Ah I see. Had the same issue with MiLight. [Fixed](https://github.com/estevez-dev/ha_client/commit/be5ea55f6b00bba3d74707d5abd79d55e0e038c9). Will be released with 0.3.14
