### ISSUE TITLE
Updater icon issue

### ISSUE THREAD

**Issue by pepeEL** [estevez-dev/ha_client#293]
When update is available not show correct icon for badges updater.updater.
![screenshot_20190211-072716](https://user-images.githubusercontent.com/16692223/52548581-d9acbc80-2dce-11e9-871c-85b52bd2b170.jpg)

**Comment by estevez-dev** [comment]
@pepeEL do you still have this entity in your HA? I'm on HA 0.87.1 and there is no updater entity in my HA.

**Comment by pepeEL** [comment]
Lost icon in app:
![53596513-32869e00-3ba0-11e9-9fca-d016def1507a](https://user-images.githubusercontent.com/16692223/53642824-e9cbf500-3c32-11e9-9930-c0f13327fb27.jpg)


In web is ok
![53596530-3a464280-3ba0-11e9-88cb-a2d6c29db6b5](https://user-images.githubusercontent.com/16692223/53642830-ee90a900-3c32-11e9-95e4-996cbf1efb7b.jpg)


You can not implement all icons material ?
