### ISSUE TITLE
LED RGBW

### ISSUE THREAD

**Issue by pepeEL** [estevez-dev/ha_client#296]
Hi
Is any chance to implement option to setup color as it is in mobile view in Home Assistant ? It looks better than in app. 
Also i use controller led for RGBW and in app not show slider to setup WHITE color. Only show slider to setup brightnes. 
When go to web view my Home Assistant i have brightnes and white.
Now by your app i can not setup light WHITE. Only colors can set.

**Comment by estevez-dev** [comment]
There is complicatedly new color picker coming in next release. Also there was some fixes for light controls. So all this should be fixed in the upcoming 0.4.0. there will be still no Color temp control in app in version 0.4.0 - please report a separate issue.

**Comment by pepeEL** [comment]
Ok thanks
