### ISSUE TITLE
Gravatar images are not displayed on device trackers

### ISSUE THREAD

**Issue by ajayjohn** [estevez-dev/ha_client#299]
Not much to explain here. So given below are two images of how the app shows these entities vs. how HA Web handles them.

**HA Web**
[http://imgur.com/gallery/DU1LvUz](http://imgur.com/gallery/DU1LvUz)

**HA Client App**
[http://imgur.com/gallery/Lke6ZwF](http://imgur.com/gallery/Lke6ZwF)

**Comment by estevez-dev** [comment]
I think it is the same as #234 but could you please show me the list of attributes for that entities?

**Comment by estevez-dev** [comment]
@ajayjohn I need some additional info here. I need attributes for any of those entities and its config please. Thanks.

**Comment by ajayjohn** [comment]
Sorry for the delay. Here are the attributes for the entity. Some personal details have been redacted.
`source_type: gps
latitude: <lat coordinates>
longitude: <long coordinates>
gps_accuracy: 10
battery: 59
friendly_name: AJ
entity_picture: https://www.gravatar.com/avatar/<link details specific to my image>`

**Comment by estevez-dev** [comment]
A assume `<link details specific to my image>` is an md5 of your email right? I tried to put an md5 of my email and I see only default avatar =(
