### ISSUE TITLE
Support for monster cards in the Lovelace UI

### ISSUE THREAD

**Issue by ajayjohn** [estevez-dev/ha_client#300]
**Monster card Github Link**
[https://github.com/ciotlosm/custom-lovelace](url)

Monster cards are currently not rendered on the app UI. No visible errors are shown in the logs.

**Comment by estevez-dev** [comment]
Yes, this is custom card. Custom cards it's not supported for now. Some of them can be implemented in future, but only most requested.

**Comment by Klagio** [comment]
> **Monster card Github Link**
> [https://github.com/ciotlosm/custom-lovelace](url)
> 
> Monster cards are currently not rendered on the app UI. No visible errors are shown in the logs.

You can use conditional card and you get (almost) the same effect as monster card

**Comment by ajayjohn** [comment]
Thanks a lot for the suggestion @Klagio!

**Comment by Klagio** [comment]
> Thanks a lot for the suggestion @Klagio!

conditional card and entity-filter: you do not have wild cards, but just put all the entity_id you need, and you achieve the same effect

**Comment by estevez-dev** [comment]
So we can close it for now?
