### ISSUE TITLE
Camera content_type: 'image/svg+xml' support

### ISSUE THREAD

**Issue by klejejs** [estevez-dev/ha_client#302]

**Comment by estevez-dev** [comment]
Please provide here the logs as well. And camera platform. Thanks

**Comment by estevez-dev** [comment]
Or is it the same camera as in #303 ?

**Comment by klejejs** [comment]
0218 13:49:14 [Debug] :  <!!!> Creating new HomeAssistant instance
0218 13:49:14 [Debug] :  AppLifecycleState.inactive
0218 13:49:14 [Debug] :  AppLifecycleState.resumed
0218 13:49:14 [Debug] :  Use lovelace is true
0218 13:49:14 [Debug] :  Socket connecting...
0218 13:49:14 [Debug] :  [Sending] ==> auth request
0218 13:49:14 [Debug] :  [Sending] ==> {"id": 1, "type": "subscribe_events", "event_type": "state_changed"}
0218 13:49:14 [Debug] :  [Sending] ==> {"id": 2, "type": "get_states"}
0218 13:49:14 [Debug] :  [Sending] ==> {"id": 3, "type": "lovelace/config"}
0218 13:49:14 [Debug] :  [Sending] ==> {"id": 4, "type": "get_config"}
0218 13:49:14 [Debug] :  [Sending] ==> {"id": 5, "type": "get_services"}
0218 13:49:14 [Debug] :  [Sending] ==> {"id": 6, "type": "auth/current_user"}
0218 13:49:14 [Debug] :  [Received] <== id:1, success
0218 13:49:14 [Debug] :  [Received] <== id:2, success
0218 13:49:14 [Debug] :  Parsing 207 Home Assistant entities
0218 13:49:14 [Debug] :  [Received] <== id:4, success
0218 13:49:14 [Debug] :  [Received] <== id:5, success
0218 13:49:14 [Debug] :  [Received] <== id:6, success
0218 13:49:14 [Debug] :  [Received] <== id:3, success
0218 13:49:14 [Debug] :  [Received] <== event.state_changed: sensor.bathroomtempsensor_hum
0218 13:49:14 [Debug] :  Creating Lovelace UI
0218 13:49:14 [Debug] :  --Title: null
0218 13:49:14 [Debug] :  --Views count: 6
0218 13:49:14 [Debug] :  ----view id: null
0218 13:49:14 [Debug] :  ----view id: null
0218 13:49:14 [Debug] :  ----view id: null
0218 13:49:14 [Debug] :  ----view id: null
0218 13:49:14 [Debug] :  ----view id: null
0218 13:49:14 [Debug] :  ----view id: null
0218 13:49:14 [Debug] :  Fetch complete successful
0218 13:49:15 [Error] :  Exception: operation failed
0218 13:49:16 [Debug] :  [Sending] ==> http://hass.lejejs.com:8123/api/camera_proxy_stream/camera.demo_camera?token=595c71f0195f22625f1b0d17c55033d06a6ed3b0d76d8e1f6d2767873f55610e
0218 13:49:16 [Debug] :  [Sending] ==> http://hass.lejejs.com:8123/api/history/period/2019-02-17T13:49:16+0200?&filter_entity_id=camera.riga_meteogram
0218 13:49:16 [Debug] :  [Received] <== {content-type: text/plain; charset=utf-8, date: Mon, 18 Feb 2019 11:49:13 GMT, server: Python/3.6 aiohttp/3.5.4, content-length: 14}
0218 13:49:17 [Debug] :  [Received] <== 4 history recors

Looks like the same log.

The config is like this:
`  - platform: generic
    name: "Riga meteogram"
    still_image_url: https://www.yr.no/place/Latvia/Riga/Riga/meteogram.svg
    content_type: 'image/svg+xml'`

I think the issue can be merged.

**Comment by estevez-dev** [comment]
#303 was fixed in version 0.4.2. But there is still an issue with svg images.

**Comment by estevez-dev** [comment]
SVG is not supported by image class in Flutter. Will be implemented using [flutter_svg](https://pub.dartlang.org/packages/flutter_svg). Changing the type to CR.

**Comment by estevez-dev** [comment]
Will support simple SVG for now without <style> elements. Depends on dnfield/flutter_svg#105

**Comment by estevez-dev** [comment]
HA Client was discontinued
