### ISSUE TITLE
Camera icon loads, but full image not loading, shows "Starting..." all the time

### ISSUE THREAD

**Issue by klejejs** [estevez-dev/ha_client#303]
![whatsapp image 2019-02-18 at 00 19 19](https://user-images.githubusercontent.com/24546950/52920255-35b59a80-3313-11e9-8853-580a00ec91cb.jpeg)

**Comment by estevez-dev** [comment]
Please attach logs, after trying to open camera. Also please show the attributes of this camera. Thanks.

**Comment by klejejs** [comment]
0218 00:26:32 [Debug] :  <!!!> Creating new HomeAssistant instance~
0218 00:26:32 [Debug] :  AppLifecycleState.inactive
0218 00:26:32 [Debug] :  AppLifecycleState.resumed
0218 00:26:32 [Debug] :  Use lovelace is true
0218 00:26:32 [Debug] :  Socket connecting...
0218 00:26:32 [Debug] :  [Sending] ==> auth request
0218 00:26:32 [Debug] :  [Sending] ==> {"id": 1, "type": "subscribe_events", "event_type": "state_changed"}
0218 00:26:32 [Debug] :  [Sending] ==> {"id": 2, "type": "get_states"}
0218 00:26:32 [Debug] :  [Sending] ==> {"id": 3, "type": "lovelace/config"}
0218 00:26:32 [Debug] :  [Sending] ==> {"id": 4, "type": "get_config"}
0218 00:26:32 [Debug] :  [Sending] ==> {"id": 5, "type": "get_services"}
0218 00:26:32 [Debug] :  [Sending] ==> {"id": 6, "type": "auth/current_user"}
0218 00:26:32 [Debug] :  [Received] <== id:1, success
0218 00:26:32 [Debug] :  [Received] <== id:2, success
0218 00:26:32 [Debug] :  Parsing 207 Home Assistant entities
0218 00:26:32 [Debug] :  [Received] <== id:4, success
0218 00:26:32 [Debug] :  [Received] <== id:5, success
0218 00:26:32 [Debug] :  [Received] <== id:6, success
0218 00:26:32 [Debug] :  [Received] <== id:3, success
0218 00:26:32 [Debug] :  Creating Lovelace UI
0218 00:26:32 [Debug] :  --Title: null
0218 00:26:32 [Debug] :  --Views count: 6
0218 00:26:32 [Debug] :  ----view id: null
0218 00:26:32 [Debug] :  ----view id: null
0218 00:26:32 [Debug] :  ----view id: null
0218 00:26:32 [Debug] :  ----view id: null
0218 00:26:32 [Debug] :  ----view id: null
0218 00:26:32 [Debug] :  ----view id: null
0218 00:26:32 [Debug] :  Fetch complete successful
0218 00:26:32 [Error] :  Exception: operation failed
0218 00:26:34 [Debug] :  [Sending] ==> http://hass.lejejs.com:8123/api/camera_proxy_stream/camera.demo_camera?token=fa341a9544132bf33347702e899b6bd490a77242549c67c67dc4d57ae8508c8a
0218 00:26:34 [Debug] :  [Sending] ==> http://hass.lejejs.com:8123/api/history/period/2019-02-17T00:26:34+0200?&filter_entity_id=camera.sigulda
0218 00:26:34 [Debug] :  [Received] <== {content-type: text/plain; charset=utf-8, date: Sun, 17 Feb 2019 22:26:32 GMT, server: Python/3.6 aiohttp/3.5.4, content-length: 14}
0218 00:26:34 [Debug] :  [Received] <== 3 history recors

![whatsapp image 2019-02-18 at 00 26 26](https://user-images.githubusercontent.com/24546950/52920371-44e91800-3314-11e9-9e33-d065d5f9ba30.jpeg)

**Comment by estevez-dev** [comment]
Is it working in web UI? And how? Your see a steam or just last captured image?

**Comment by estevez-dev** [comment]
And what is the platform of this camera?

**Comment by klejejs** [comment]
The platform is `generic`.
The web UI is working and I see still images being updated every few seconds.

**Comment by klejejs** [comment]
`- platform: generic
    name: sigulda
    still_image_url: http://cam2.sigulda.lv/trase.jpg`

**Comment by estevez-dev** [comment]
Nice. Thanks!

**Comment by estevez-dev** [comment]
I've configured this camera in my HA. It works now in app version 0.4.2
