### ISSUE TITLE
Camera stream/image not shown

### ISSUE THREAD

**Issue by Klagio** [estevez-dev/ha_client#304]
Version 0.4.0.

I have various camera streams (generic, ffmpeg, as per below configuration), but none is shown in HA Client. Same configuration in Lovelace is shown in card size (and when clicked upon it expanded to very big size)
```

- platform: ffmpeg
    name: Living2
    input: rtsp://admin:xxxxxxx@192.168.1.10:554/rtsp_live0

  - platform: generic
    name: Kitchen
    still_image_url: http://192.168.1.12/snapshot.cgi?user=admin&pwd=xxxxxxx 

  - platform: generic
    name: West
    still_image_url: http://admin:xxxxxxx@192.168.1.11/ISAPI/Streaming/channels/101/picture
```

**Comment by estevez-dev** [comment]
Please, open 'Living2' camera in app, then got to Log viewer and copy log output here. Thanks.

**Comment by Klagio** [comment]
nothing in log .....

**Comment by Klagio** [comment]
0218 18:10:08 [Debug] :  State change event handled by entity page: sensor.washer_and_dryer_interval
0218 18:10:09 [Debug] :  [Received] <== event.state_changed: zwave.washer_and_dryer
0218 18:10:09 [Debug] :  [Received] <== event.state_changed: sensor.washer_and_dryer_exporting
0218 18:10:09 [Debug] :  State change event handled by entity page: zwave.washer_and_dryer
0218 18:10:09 [Debug] :  State change event handled by entity page: sensor.washer_and_dryer_exporting
0218 18:10:09 [Debug] :  [Received] <== event.state_changed: sensor.washer_and_dryer_energy
0218 18:10:09 [Debug] :  [Received] <== event.state_changed: sensor.washer_and_dryer_previous_reading
0218 18:10:09 [Debug] :  [Received] <== event.state_changed: sensor.washer_and_dryer_interval
0218 18:10:09 [Debug] :  [Received] <== event.state_changed: sensor.washer_and_dryer_power
0218 18:10:09 [Debug] :  [Received] <== event.state_changed: sensor.washer_and_dryer_previous_reading_2
0218 18:10:09 [Debug] :  [Received] <== event.state_changed: sensor.washer_and_dryer_interval_2
0218 18:10:09 [Debug] :  [Received] <== event.state_changed: sensor.washer_and_dryer_voltage
0218 18:10:09 [Debug] :  [Received] <== event.state_changed: sensor.washer_and_dryer_previous_reading_3
0218 18:10:09 [Debug] :  [Received] <== event.state_changed: sensor.washer_and_dryer_interval_3
0218 18:10:09 [Debug] :  [Received] <== event.state_changed: sensor.washer_and_dryer_current
0218 18:10:09 [Debug] :  [Received] <== event.state_changed: sensor.washer_and_dryer_previous_reading_4
0218 18:10:09 [Debug] :  [Received] <== event.state_changed: sensor.washer_and_dryer_interval_4
0218 18:10:09 [Debug] :  [Received] <== event.state_changed: sensor.washer_and_dryer_alarm_type
0218 18:10:09 [Debug] :  [Received] <== event.state_changed: sensor.washer_and_dryer_alarm_level
0218 18:10:09 [Debug] :  [Received] <== event.state_changed: sensor.washer_and_dryer_sourcenodeid
0218 18:10:09 [Debug] :  [Received] <== event.state_changed: sensor.washer_and_dryer_power_management
0218 18:10:09 [Debug] :  State change event handled by entity page: sensor.washer_and_dryer_energy
0218 18:10:09 [Debug] :  State change event handled by entity page: sensor.washer_and_dryer_previous_reading
0218 18:10:09 [Debug] :  State change event handled by entity page: sensor.washer_and_dryer_interval
0218 18:10:09 [Debug] :  State change event handled by entity page: sensor.washer_and_dryer_power
0218 18:10:09 [Debug] :  State change event handled by entity page: sensor.washer_and_dryer_previous_reading_2
0218 18:10:09 [Debug] :  State change event handled by entity page: sensor.washer_and_dryer_interval_2
0218 18:10:09 [Debug] :  State change event handled by entity page: sensor.washer_and_dryer_voltage
0218 18:10:09 [Debug] :  State change event handled by entity page: sensor.washer_and_dryer_previous_reading_3
0218 18:10:09 [Debug] :  State change event handled by entity page: sensor.washer_and_dryer_interval_3
0218 18:10:09 [Debug] :  State change event handled by entity page: sensor.washer_and_dryer_current
0218 18:10:09 [Debug] :  State change event handled by entity page: sensor.washer_and_dryer_previous_reading_4
0218 18:10:09 [Debug] :  State change event handled by entity page: sensor.washer_and_dryer_interval_4
0218 18:10:09 [Debug] :  State change event handled by entity page: sensor.washer_and_dryer_alarm_type
0218 18:10:09 [Debug] :  State change event handled by entity page: sensor.washer_and_dryer_alarm_level
0218 18:10:09 [Debug] :  State change event handled by entity page: sensor.washer_and_dryer_sourcenodeid
0218 18:10:09 [Debug] :  State change event handled by entity page: sensor.washer_and_dryer_power_management
0218 18:10:09 [Debug] :  [Received] <== event.state_changed: automation.main_daily_energy
0218 18:10:09 [Debug] :  State change event handled by entity page: automation.main_daily_energy
0218 18:10:09 [Debug] :  [Received] <== event.state_changed: automation.sensor_values_to_file
0218 18:10:09 [Debug] :  [Received] <== event.state_changed: automation.automation_ran
0218 18:10:09 [Debug] :  State change event handled by entity page: automation.sensor_values_to_file
0218 18:10:09 [Debug] :  State change event handled by entity page: automation.automation_ran
0218 18:10:09 [Debug] :  [Received] <== event.state_changed: automation.automation_ran
0218 18:10:09 [Debug] :  [Received] <== event.state_changed: sensor.today_main_kwh
0218 18:10:09 [Debug] :  State change event handled by entity page: automation.automation_ran
0218 18:10:09 [Debug] :  State change event handled by entity page: sensor.today_main_kwh
0218 18:10:10 [Debug] :  [Received] <== event.state_changed: zwave.washer_and_dryer
0218 18:10:10 [Debug] :  [Received] <== event.state_changed: sensor.washer_and_dryer_exporting
0218 18:10:10 [Debug] :  State change event handled by entity page: zwave.washer_and_dryer
0218 18:10:10 [Debug] :  State change event handled by entity page: sensor.washer_and_dryer_exporting
0218 18:10:10 [Debug] :  [Received] <== event.state_changed: sensor.washer_and_dryer_voltage
0218 18:10:10 [Debug] :  State change event handled by entity page: sensor.washer_and_dryer_voltage
0218 18:10:10 [Debug] :  [Received] <== event.state_changed: sensor.washer_and_dryer_previous_reading_3
0218 18:10:10 [Debug] :  [Received] <== event.state_changed: sensor.washer_and_dryer_interval_3
0218 18:10:10 [Debug] :  State change event handled by entity page: sensor.washer_and_dryer_previous_reading_3
0218 18:10:10 [Debug] :  State change event handled by entity page: sensor.washer_and_dryer_interval_3
0218 18:10:10 [Debug] :  [Received] <== event.state_changed: binary_sensor.ping_router_asus
0218 18:10:10 [Debug] :  State change event handled by entity page: binary_sensor.ping_router_asus
0218 18:10:11 [Debug] :  [Received] <== event.state_changed: zwave.washer_and_dryer
0218 18:10:11 [Debug] :  [Received] <== event.state_changed: sensor.washer_and_dryer_exporting
0218 18:10:11 [Debug] :  State change event handled by entity page: zwave.washer_and_dryer
0218 18:10:11 [Debug] :  State change event handled by entity page: sensor.washer_and_dryer_exporting
0218 18:10:11 [Debug] :  [Received] <== event.state_changed: sensor.washer_and_dryer_current
0218 18:10:11 [Debug] :  [Received] <== event.state_changed: sensor.washer_and_dryer_previous_reading_4
0218 18:10:11 [Debug] :  State change event handled by entity page: sensor.washer_and_dryer_current
0218 18:10:11 [Debug] :  State change event handled by entity page: sensor.washer_and_dryer_previous_reading_4
0218 18:10:11 [Debug] :  [Received] <== event.state_changed: sensor.washer_and_dryer_interval_4
0218 18:10:11 [Debug] :  State change event handled by entity page: sensor.washer_and_dryer_interval_4
0218 18:10:13 [Debug] :  [Received] <== event.state_changed: binary_sensor.ping_camera_digo2
0218 18:10:13 [Debug] :  State change event handled by entity page: binary_sensor.ping_camera_digo2
0218 18:10:14 [Debug] :  [Received] <== event.state_changed: sensor.oven_current
0218 18:10:14 [Debug] :  [Received] <== event.state_changed: sensor.oven_power
0218 18:10:14 [Debug] :  [Received] <== event.state_changed: sensor.oven_voltage
0218 18:10:14 [Debug] :  [Received] <== event.state_changed: sensor.total_oven_energy_consumed
0218 18:10:14 [Debug] :  [Received] <== event.state_changed: sensor.today_oven_energy_consumed
0218 18:10:14 [Debug] :  State change event handled by entity page: sensor.oven_current
0218 18:10:14 [Debug] :  State change event handled by entity page: sensor.oven_power
0218 18:10:14 [Debug] :  State change event handled by entity page: sensor.oven_voltage
0218 18:10:14 [Debug] :  State change event handled by entity page: sensor.total_oven_energy_consumed
0218 18:10:14 [Debug] :  State change event handled by entity page: sensor.today_oven_energy_consumed
0218 18:10:15 [Debug] :  [Received] <== event.state_changed: binary_sensor.east_one_motion
0218 18:10:15 [Debug] :  State change event handled by entity page: binary_sensor.east_one_motion
0218 18:10:16 [Debug] :  [Received] <== event.state_changed: binary_sensor.ping_deconz
0218 18:10:16 [Debug] :  State change event handled by entity page: binary_sensor.ping_deconz
0218 18:10:17 [Debug] :  [Received] <== event.state_changed: binary_sensor.ping_router_r7000
0218 18:10:17 [Debug] :  State change event handled by entity page: binary_sensor.ping_router_r7000
0218 18:10:19 [Debug] :  [Received] <== event.state_changed: automation.main_daily_energy
0218 18:10:19 [Debug] :  [Received] <== event.state_changed: automation.sensor_values_to_file
0218 18:10:19 [Debug] :  State change event handled by entity page: automation.main_daily_energy
0218 18:10:19 [Debug] :  State change event handled by entity page: automation.sensor_values_to_file
0218 18:10:19 [Debug] :  [Received] <== event.state_changed: automation.automation_ran
0218 18:10:19 [Debug] :  [Received] <== event.state_changed: automation.automation_ran
0218 18:10:19 [Debug] :  State change event handled by entity page: automation.automation_ran
0218 18:10:19 [Debug] :  State change event handled by entity page: automation.automation_ran
0218 18:10:19 [Debug] :  [Received] <== event.state_changed: sensor.today_main_kwh
0218 18:10:19 [Debug] :  State change event handled by entity page: sensor.today_main_kwh
0218 18:10:20 [Debug] :  [Received] <== event.state_changed: sensor.time
0218 18:10:20 [Debug] :  [Received] <== event.state_changed: binary_sensor.ping_efergy
0218 18:10:21 [Debug] :  [Received] <== event.state_changed: binary_sensor.ping_broadlink_irma_room

**Comment by estevez-dev** [comment]
You need to copy log right after you tried to open camera entity view. There should be messages about getting camera stream.

**Comment by Klagio** [comment]
Demo camera it's not mine

0218 19:04:21 [Debug] :  <!!!> Creating new HomeAssistant instance
0218 19:04:21 [Debug] :  AppLifecycleState.inactive
0218 19:04:21 [Debug] :  AppLifecycleState.resumed
0218 19:04:21 [Debug] :  Use lovelace is true
0218 19:04:21 [Debug] :  Socket connecting...
0218 19:04:25 [Debug] :  [Sending] ==> auth request
0218 19:04:25 [Debug] :  [Sending] ==> {"id": 1, "type": "subscribe_events", "event_type": "state_changed"}
0218 19:04:25 [Debug] :  [Sending] ==> {"id": 2, "type": "get_states"}
0218 19:04:25 [Debug] :  [Sending] ==> {"id": 3, "type": "lovelace/config"}
0218 19:04:25 [Debug] :  [Sending] ==> {"id": 4, "type": "get_config"}
0218 19:04:25 [Debug] :  [Sending] ==> {"id": 5, "type": "get_services"}
0218 19:04:25 [Debug] :  [Sending] ==> {"id": 6, "type": "auth/current_user"}
0218 19:04:25 [Debug] :  [Received] <== id:1, success
0218 19:04:25 [Debug] :  [Received] <== id:2, success
0218 19:04:25 [Debug] :  Parsing 1455 Home Assistant entities
0218 19:04:25 [Debug] :  [Received] <== id:4, success
0218 19:04:25 [Debug] :  [Received] <== id:5, success
0218 19:04:25 [Debug] :  [Received] <== id:6, success
0218 19:04:25 [Debug] :  [Received] <== id:3, success
0218 19:04:25 [Debug] :  Creating Lovelace UI
0218 19:04:25 [Debug] :  --Title: null
0218 19:04:25 [Debug] :  --Views count: 9
0218 19:04:25 [Debug] :  ----view id: 0
0218 19:04:25 [Debug] :  ----view id: lights
0218 19:04:25 [Debug] :  ----view id: 2
0218 19:04:25 [Debug] :  ----view id: 3
0218 19:04:25 [Debug] :  ----view id: 4
0218 19:04:25 [Debug] :  ----view id: 5
0218 19:04:25 [Debug] :  ----view id: 6
0218 19:04:25 [Debug] :  ----view id: 8
0218 19:04:25 [Debug] :  ----view id: 9
0218 19:04:25 [Debug] :  Fetch complete successful
0218 19:04:26 [Debug] :  [Received] <== event.state_changed: binary_sensor.ping_router_tenda
0218 19:04:27 [Debug] :  [Received] <== event.state_changed: binary_sensor.ping_broadlink_living_room
0218 19:04:27 [Debug] :  [Received] <== event.state_changed: sensor.lux_kitchen_room
0218 19:04:28 [Debug] :  [Received] <== event.state_changed: binary_sensor.ping_router_netgear
0218 19:04:29 [Debug] :  [Received] <== event.state_changed: automation.sensor_values_to_file
0218 19:04:29 [Debug] :  [Received] <== event.state_changed: automation.main_daily_energy
0218 19:04:29 [Debug] :  [Received] <== event.state_changed: automation.automation_ran
0218 19:04:29 [Debug] :  [Received] <== event.state_changed: automation.automation_ran
0218 19:04:29 [Debug] :  [Received] <== event.state_changed: sensor.today_main_kwh
0218 19:04:29 [Debug] :  [Received] <== event.state_changed: cover.porsche
0218 19:04:29 [Debug] :  [Received] <== event.state_changed: binary_sensor.ping_rf_bridge
0218 19:04:32 [Debug] :  [Received] <== event.state_changed: binary_sensor.ping_max_cube
0218 19:04:33 [Debug] :  [Sending] ==> https://barbano.duckdns.org:443/api/camera_proxy_stream/camera.demo_camera?token=17d1da34d8182a81f0fd21ae47faf414a65f4125565ca791d544f32731be7aac
0218 19:04:33 [Debug] :  [Sending] ==> https://barbano.duckdns.org:443/api/history/period/2019-02-17T19:04:33+0100?&filter_entity_id=camera.living2
0218 19:04:33 [Debug] :  [Received] <== {content-type: text/plain; charset=utf-8, date: Mon, 18 Feb 2019 18:05:14 GMT, server: Caddy,Python/3.6 aiohttp/3.5.4, content-length: 14}
0218 19:04:33 [Error] :  Error loading camera.living2 history: Bad state: No element
0218 19:04:33 [Debug] :  [Received] <== event.state_changed: binary_sensor.ping_qnap2
0218 19:04:33 [Debug] :  State change event handled by entity page: binary_sensor.ping_qnap2
0218 19:04:34 [Debug] :  [Received] <== event.state_changed: binary_sensor.ping_broadlink_guest_room
0218 19:04:34 [Debug] :  State change event handled by entity page: binary_sensor.ping_broadlink_guest_room
0218 19:04:34 [Debug] :  [Received] <== event.state_changed: sensor.oven_current
0218 19:04:34 [Debug] :  State change event handled by entity page: sensor.oven_current
0218 19:04:35 [Debug] :  [Received] <== event.state_changed: sensor.pir_bathroom
0218 19:04:35 [Debug] :  [Received] <== event.state_changed: binary_sensor.ping_netatmo_living

**Comment by Klagio** [comment]
I was in my LAN (WiFi), while I opened living2


0218 19:04:33 [Debug] : [Sending] ==> https://xxxx.duckdns.org:443/api/camera_proxy_stream/camera.demo_camera?token=xxxxxx
0218 19:04:33 [Debug] : [Sending] ==> https://xxxxxduckdns.org:443/api/history/period/2019-02-17T19:04:33+0100?&filter_entity_id=camera.living2
0218 19:04:33 [Debug] : [Received] <== {content-type: text/plain; charset=utf-8, date: Mon, 18 Feb 2019 18:05:14 GMT, server: Caddy,Python/3.6 aiohttp/3.5.4, content-length: 14}
0218 19:04:33 [Error] : Error loading camera.living2 history: Bad state: No element

**Comment by estevez-dev** [comment]
Please update to 0.4.2, retest and conform it is fixed or need improvements. Thanks.
