### ISSUE TITLE
Ffmpeg camera not working

### ISSUE THREAD

**Issue by Klagio** [estevez-dev/ha_client#307]
Great app, camera feed is fast, excellent.

On some there is error like

219 20:08:47 [Error] :  Error loading camera.door_12 history: Bad state: No element

Below configuration in HASS 

  - platform: ffmpeg
    name: Door 12
    input: -rtsp_transport tcp -i rtsp://admin:xxxxx@192.168.1.3:554/Streaming/Channels/101/

**Comment by Klagio** [comment]
Also this gives same error

  - platform: ffmpeg
    name: Kitchen2
    input: rtsp://admin:xxx@192.168.1.4:554/onvif2

**Comment by Klagio** [comment]
Also this same error

  - platform: ffmpeg
    name: Office2
    input: rtsp://admin:xxxx@192.168.1.5:554/rtsp_live0

**Comment by Klagio** [comment]
I have all the generic camera work perfectly

**Comment by estevez-dev** [comment]
The error provided is not about streaming. Try to open any of this cameras and then copy the full lot there

**Comment by vladosam** [comment]
Also ffmpeg problem.
```
0219 20:04:23 [Debug] :  Fetch complete successful
0219 20:04:44 [Debug] :  [Sending] ==> http://192.168.1.250:8123/api/camera_proxy_stream/camera.cam_1?token=7a5fe2be6764f2ccc04face8cf6e46fae635035396bdcb926a77c3cb25418944
0219 20:04:44 [Debug] :  [Sending] ==> http://192.168.1.250:8123/api/history/period/2019-02-18T20:04:44+0100?&filter_entity_id=camera.cam_1
0219 20:04:44 [Debug] :  [Received] <== {content-type: multipart/x-mixed-replace;boundary=ffserver, date: Tue, 19 Feb 2019 19:04:52 GMT, transfer-encoding: chunked, server: Python/3.6 aiohttp/3.5.4}
0219 20:04:44 [Error] :  Error loading camera.cam_1 history: Bad state: No element
```
Config:
```
camera:
  - platform: ffmpeg
    input: -rtsp_transport tcp -i rtsp://xxxxx:xxxxx@192.168.1.12:10554/tcp/av0_0
    name: CAM_1
```
After 3-4 seconds on camera entity app freeze.

**Comment by Klagio** [comment]
19 20:52:38 [Debug] :  [Sending] ==> https://xxx.duckdns.org:443/api/camera_proxy_stream/camera.living2?token=ac64dc301af0fcb288810f29272c2676b697645c618a9835b616b5909449
0219 20:52:38 [Debug] :  [Sending] ==> https://xxx.duckdns.org:443/api/history/period/2019-02-18T20:52:38+0100?&filter_entity_id=camera.living2
0219 20:52:38 [Error] :  Error loading camera.living2 history: Bad state: No element

**Comment by estevez-dev** [comment]
@Klagio i need the next line )) It should contain `[Received] <== {content-type:`

**Comment by Klagio** [comment]
219 21:24:45 [Error] :  Error loading camera.living2 history: Bad state: No element
0219 21:24:45 [Debug] :  [Received] <== {content-type: multipart/x-mixed-replace;boundary=ffserver, transfer-encoding: chunked, date: Tue, 19 Feb 2019 20:25:25 GMT, server: Caddy,Python/3.6 aiohttp/3.5.4

**Comment by estevez-dev** [comment]
If something will not work after 0.4.3 update, feel free to reopen or report new.
