### ISSUE TITLE
Feature request: Lock to have both UNLOCK and LOCK button (as new 0.88 HASS)

### ISSUE THREAD

**Issue by Klagio** [estevez-dev/ha_client#310]
I have various lock that do not report well the status, hence sometimes the frontend gives the possibility to UNLOCK when the lock is unlocked, so you need to press UNLOCK, wait some time and then press again LOCK

its good to have both UNLOCK, LOCK, options, as is now also in HASS 0.88

Image in case is not clear

https://www.dropbox.com/s/fn0f9laih6dsafp/Lock%20Unlock.JPG?dl=0

**Comment by Klagio** [comment]
[https://www.dropbox.com/s/fn0f9laih6dsafp/Lock%20Unlock.JPG?dl=0](url)

**Comment by estevez-dev** [comment]
Could you please show the screenshot of this lock attributes from the app? Thanks

**Comment by Klagio** [comment]
Your app is this
https://imgur.com/a/w7U6Akk

**Comment by Klagio** [comment]
This is in Home Assistant since 0.88
https://imgur.com/a/medZhQV

**Comment by Klagio** [comment]
In state attriubutes, just this

{
  "friendly_name": "14a office door"
}

**Comment by Klagio** [comment]
I see in 0.88 reference of change in lock I think only this

https://github.com/home-assistant/home-assistant/pull/21025

**Comment by estevez-dev** [comment]
> I see in 0.88 reference of change in lock I think only this
> 
> [home-assistant/home-assistant#21025](https://github.com/home-assistant/home-assistant/pull/21025)

This is not relevant to this feature

**Comment by Klagio** [comment]
Is this difficult to fix? I ask because I use your app as an everyday app, and I need to open/close my door multiple times a day, so for just that opening/closing I need to open the very slow Chrome Web app, and not use your wonderful app

**Comment by estevez-dev** [comment]
It is difficult to understand, how to know which control to show. One or both. Your lock has no difference with the demo one, but demo lock has only one button at a time - lock or unlock. And there is no special attributes for the lock.

**Comment by estevez-dev** [comment]
Oh, wait! Could you please show a screenshot of that lock from web ui dev tools, where the table of all your entities is shown. I need to see a state of lock in text format.

**Comment by Klagio** [comment]
I wish both control are shown (UNLOCK LOCK)

**Comment by Klagio** [comment]
This?
https://imgur.com/a/heV0NRG

**Comment by estevez-dev** [comment]
> This?
> https://imgur.com/a/heV0NRG

Almost. The table under "Current entities". Find your lock there and show me all row work state and attributes.

**Comment by Klagio** [comment]
If I understood correctly is this, but its showing only friendly_name

https://imgur.com/a/dMvowcZ

**Comment by Klagio** [comment]
Maybe a bug to report to HA devs?

**Comment by Klagio** [comment]
values of state are locked or unlocked
