### ISSUE TITLE
White value support for light entity

### ISSUE THREAD

**Issue by pepeEL** [estevez-dev/ha_client#312]
Hi
On app no available slider for white.... only brightnes. On web page is availavle also brightnes and white slider.

WEB
![color](https://user-images.githubusercontent.com/16692223/53197740-0eb0de80-361b-11e9-8c83-881abc945384.jpg)

APP
![screenshot_20190221-205321](https://user-images.githubusercontent.com/16692223/53197821-4ddf2f80-361b-11e9-8b62-136f507c27b5.jpg)

**Comment by estevez-dev** [comment]
Show me all device attributes from the app please. It is the bottom part of entity view. I see only "rgb_color" on screenshot

**Comment by pepeEL** [comment]
![screenshot_20190222-075608](https://user-images.githubusercontent.com/16692223/53225187-801e7a80-3677-11e9-85bd-a0d9ec5b0b9d.jpg)

**Comment by estevez-dev** [comment]
Does the brightness control works fine in the app? Because according to attributes it shouldn't ))

**Comment by estevez-dev** [comment]
And what is the platform of this light?

**Comment by pepeEL** [comment]
Yes works ok and it is platform MySensors....
This sketch:
https://github.com/OliverHi/RGBW-Controller/tree/master/Software/RGBWDimmerV2

**Comment by estevez-dev** [comment]
Found it! I thought it is a color temperature, but it is a "white value"! It is not supported in up now. I'll add it. Thanks for the report.

**Comment by pepeEL** [comment]
Ok thanks
