### ISSUE TITLE
Change app color scheme

### ISSUE THREAD

**Issue by Kvasenok** [estevez-dev/ha_client#315]
It is more of a small feature request. 

I know that the color schemes in HA and in HAClient look similar, but it is quite obvious that HAClient uses the default blue color scheme for Flutter apps. 
Is it possible to change it to a lighter shade of blue in accordance with HA color scheme?

I mean, it's not a big deal at all, it is still blue, just bugs my inner perfectionist))

**Comment by estevez-dev** [comment]
Should be done after #102

**Comment by Kvasenok** [comment]
Sooo, if #102 means HA Client will use data from HA themes and change colors accordingly, than it probably will also use "Default" HA theme as default color scheme , and this issue kinda counts as a duplicate?))

**Comment by estevez-dev** [comment]
No, #102 is a technical task to use Flutter built in material theme tools

**Comment by estevez-dev** [comment]
Done in 0.8.3. You can choose app theme in App settings
