### ISSUE TITLE
Not show icon

### ISSUE THREAD

**Issue by pepeEL** [estevez-dev/ha_client#316]
I found that in App not show icon for one entity but on web page show ok. Look
App
![screenshot_20190228-173118](https://user-images.githubusercontent.com/16692223/53596513-32869e00-3ba0-11e9-9fca-d016def1507a.jpg)

Web
![screenshot_20190228-212931](https://user-images.githubusercontent.com/16692223/53596530-3a464280-3ba0-11e9-88cb-a2d6c29db6b5.jpg)

**Comment by estevez-dev** [comment]
Please add this screenshots to #293 . This is the same issue. Thanks. I'm closing this as duplicate.
