### ISSUE TITLE
Feature Request: Client Certificate Authentication Support

### ISSUE THREAD

**Issue by photinus** [estevez-dev/ha_client#319]
Please add support for specifying a Client Certificate for authentication to a proxy server when connecting to home assistant.

**Comment by estevez-dev** [comment]
Usually client certificates should be installed in Android OS to allow any connection through specific proxy.

**Comment by photinus** [comment]
Proxy is probably a little bit of a misnomer here, but here is a link to an
article about how nginx gets setup:
https://blog.codeship.com/how-to-set-up-mutual-tls-authentication/

Because ha client is using flutter, it has to be setup by the app. I have
the cert installed on my phone, but it won't connect through the app.

**Comment by photinus** [comment]
If you need a server to test against, let me know. I have a test server setup for developing against this feature

**Comment by estevez-dev** [comment]
It would be very useful, thanks. I'll let you know.

**Comment by carlos-sarmiento** [comment]
@estevez-dev Is there any chance this gets implemented? It's THE feature blocking me from using the app all the time.

**Comment by estevez-dev** [comment]
It is. There is a chance we will solve it with this: https://github.com/estevez-dev/ha_client/issues/344#issuecomment-552178418
I already added network security config. Will be released soon.

**Comment by carlos-sarmiento** [comment]
@estevez-dev Thanks for the quick reply. I checked the comment you mentioned but it seems to be related to self-signed certificates for server validation. Client Authentication is a different feature in which the server requires the client to authenticate with a certificate (this is also called TLS Mutual Authentication)

**Comment by estevez-dev** [comment]
Ah sorry, indeed. So still there is a chance but I can't give you any estimations, sorry.

**Comment by estevez-dev** [comment]
HA Client was discontinued
