### ISSUE TITLE
type: divider ui problem

### ISSUE THREAD

**Issue by klejejs** [estevez-dev/ha_client#324]
Divider on the left does not have any margin and the line goes right to the side of the card.
![_20190314_103715](https://user-images.githubusercontent.com/24546950/54342805-16760880-4646-11e9-90de-d7e8bc57f68a.JPG)

**Comment by klejejs** [comment]
Could you please also make it a bit darker, as it is barely visible now. Or maybe you can leave it as it is and we will be able to specify out own colors when the theme support comes out?

**Comment by estevez-dev** [comment]
Agree, it really almost not visible. Will fix.
