### ISSUE TITLE
Scheduled service calls

### ISSUE THREAD

**Issue by Klagio** [estevez-dev/ha_client#325]
This is not present in HASS, and I think is a big lack: every app made by producers of home automation devices have a scheduler and a timer. 

Would it be possible by HA Client to associate a timer to a switch/script (easily from frontend)?

**Comment by estevez-dev** [comment]
Sorry didn't get it. What do you mean by timer associated with switch?

**Comment by Klagio** [comment]
Ok the timer per se, is not (to me) very useful: I wish I could associate  a (for example) switch.power_plug to the timer, and give timer 1 minute, after one minute switch goes off

**Comment by estevez-dev** [comment]
Oh I see now. This can be done and should be done on Home Assistant side by scripts and automation. It is a duplication of functionality so will not be implemented on HA Client side.

**Comment by Klagio** [comment]
Sure but it lacks an app that does this without coding: simple input time in timer simple drop down menu with switch/script.

Sometimes my wife wants to add a timer for the oven, I can't ask her to modify a yaml file :)

**Comment by estevez-dev** [comment]
May be it really make sense

**Comment by Klagio** [comment]
Something like Ewelink app does (there are many many app doing that).

To me is something that has to be in front-end (in an easy way). I am not a programmer but everything should be already there:
- the timer is set in configuration
- the entity_id are there (I would just use it for switch and/or script)

the HA client should just give a simple front-end and at timer end call a service (switch.turn_on or off and/or script.turn_on or off)

https://www.youtube.com/watch?v=EKbzmmRnXUg
https://www.youtube.com/watch?v=9ZxXQbjvdpA

**Comment by estevez-dev** [comment]
I understood, thanks.

**Comment by estevez-dev** [comment]
HA Client was discontinued
