### ISSUE TITLE
Open Web UI in Chrome Custom Tab

### ISSUE THREAD

**Issue by Kvasenok** [estevez-dev/ha_client#328]
Since we now have CCT support, wouldn't it make more sense to have Web UI open in a custom tab as well, instead of a browser?

**Comment by estevez-dev** [comment]
Actually I'm not sure it would be better. CCT is good for one page where you do something and then go back to app. If you want to open HA web ui, you can navigate through pages and it's like opening an app inside another app. Very strange.

**Comment by Kvasenok** [comment]
Hmm, good point. Didn't think about it this way.

**Comment by estevez-dev** [comment]
So I'll close this?

**Comment by Kvasenok** [comment]
Nah, I closed it already)))
