### ISSUE TITLE
Material remote icon is not displayed

### ISSUE THREAD

**Issue by porankazi** [estevez-dev/ha_client#345]
Hi,
    All of my material icons displays correctly on the app except for remote. The remote icon displays correctly on the browser but not in the app. I use the customize file for Hassio to assign all of my icons. Please let me know if you need any additional details. Thanks.

**Comment by estevez-dev** [comment]
Hi.
It would be good to see a screenshots of wrong icon from app and from web. Thanks.

**Comment by porankazi** [comment]
Here you go.
![Screenshot_20190326-101420_Chrome](https://user-images.githubusercontent.com/48230163/55004106-fb918580-4faf-11e9-827f-c4d872079d71.jpg)
![20190325_123944](https://user-images.githubusercontent.com/48230163/55004139-0c41fb80-4fb0-11e9-82e6-71e119ec6e90.jpg)

**Comment by klejejs** [comment]
I have remote icon in glance card and it is showing up.

**Comment by estevez-dev** [comment]
> I have remote icon in glance card and it is showing up.

The proble is in "Remote" platform, not in icon I think.
