### ISSUE TITLE
Auth not saved

### ISSUE THREAD

**Issue by klejejs** [estevez-dev/ha_client#354]
When updating app to 0.6.0 alpha, login information is not saved and you are asked to login once more.

**Comment by estevez-dev** [comment]
Force close the app, launch it again, go through login process once again, the go to "Log" in main menu and copy it with the Copy button in upper-right corner. Paste logs here please. Thanks.

**Comment by estevez-dev** [comment]
The app will ask to login after update to 0.6.0. This is as intended.
