### ISSUE TITLE
Group entities missing

### ISSUE THREAD

**Issue by Derkades** [estevez-dev/ha_client#365]
![image](https://user-images.githubusercontent.com/15892014/55681780-abf57700-592a-11e9-8c4d-a0925911521c.png)

As you can see, the switch for everything in the card and the "all lights" entity does not appear in the app. 

This feature has also been suggested in this issue: https://github.com/estevez-dev/ha_client/issues/186 (closed, supposedly added)

Also in this issue (I think?): https://github.com/estevez-dev/ha_client/issues/157 (still open)

**Comment by estevez-dev** [comment]
Yes, card switches will be added in #157 
But groups should be shown, so I assume there is some issue with groups. Will check.

**Comment by e-budianto** [comment]
Could somebody confirm 2 level grouping not supported yet?

**Comment by Derkades** [comment]
To confirm: this fixes both header toggles and group entities?

**Comment by estevez-dev** [comment]
> To confirm: this fixes both header toggles and group entities?

card switches will be added in #157

**Comment by Derkades** [comment]
Okay thank you
