### ISSUE TITLE
Unable to connect

### ISSUE THREAD

**Issue by valepe** [estevez-dev/ha_client#367]
After input ip address, port and the token, the app reports error code 1.
I'm using hassio.
This from the log:

0413 09:42:43 [Debug] :  Use lovelace is true
0413 09:42:43 [Debug] :  Socket connecting...
0413 09:42:43 [Error] :  Socket stream Error: WebSocketChannelException: WebSocketChannelException: HandshakeException: Handshake error in client (OS Error: 
	WRONG_VERSION_NUMBER(tls_record.cc:242))
0413 09:42:43 [Debug] :  Automatic reconnect is false
0413 09:42:46 [Debug] :  Socket sink closed

**Comment by valepe** [comment]
Sorry, I fixed using http and not the https protocol.

One tip: can you get the sun elevation text from HA? Now itsn't translated.

**Comment by estevez-dev** [comment]
WIll be implemented in #190
