### ISSUE TITLE
Layout errors

### ISSUE THREAD

**Issue by croghostrider** [estevez-dev/ha_client#368]
Hi, I have some layout errors and the history from the sensors are missing.
I have all marked in the screenshots.

**Webinterface**
![android](https://user-images.githubusercontent.com/8603272/56097879-3d9c5000-5efa-11e9-95ec-932799bd0cd9.jpg)
**Android**
![webinterface](https://user-images.githubusercontent.com/8603272/56097880-3d9c5000-5efa-11e9-9080-b492967fcdbf.jpg)

**Comment by estevez-dev** [comment]
Sensor card support is for future: #220

**Comment by estevez-dev** [comment]
Closing as duplicate of #220 and #239
