### ISSUE TITLE
Access token (silly newbie question)

### ISSUE THREAD

**Issue by PieBru** [estevez-dev/ha_client#372]
Hi,
when configuring the just installed app on my phone, it's not obvious to me what "Access token" I should use.
Where can I find/generate it?
Thanks,
Piero

**Comment by estevez-dev** [comment]
Hi. Here is a documentation link:
http://ha-client.homemade.systems/docs#authentication

пт, 26 апр. 2019 г. в 13:43, PieBru <notifications@github.com>:
