### ISSUE TITLE
Error when lovalaceUI activated

### ISSUE THREAD

**Issue by pafsan** [estevez-dev/ha_client#373]
I can connect, but if I activate lovelace i have:
Red screen with error:
No such method error: the method 'touppercase' was called on null.
Receiver: null
Tried calling: toUpperCase()

Without lovelace it' s working

**Comment by estevez-dev** [comment]
Could you please copy logs from the app? Thanks

**Comment by estevez-dev** [comment]
Could you please attach a screenshot of that red screen? Thanks

**Comment by NicoBijl** [comment]
Same here. Screenshot: 
![Screenshot_20190507-120423](https://user-images.githubusercontent.com/1883943/57302261-112fba00-70db-11e9-9b29-2e46759d946f.jpg)

**Comment by estevez-dev** [comment]
Resolved in 0.5.4
