### ISSUE TITLE
custom:monster-card support

### ISSUE THREAD

**Issue by mattlward** [estevez-dev/ha_client#378]
I have a card in HA that is a quick access card to enable and disable automations on the fly, here it is in a web browser:
![image](https://user-images.githubusercontent.com/8540074/57791336-37201480-7702-11e9-9694-6179967e9853.png)

In the latest client, the card is completely blank.  

It did not quite look like any of the other open cases, so posted it up.

**Comment by estevez-dev** [comment]
Could you please show a configuration of this card? Thanks.

**Comment by mattlward** [comment]
Will get the config on friday.

**Comment by mattlward** [comment]
Here is the code for the card, sorry for the delay:
`- cards:
      - card:
          show_header_toggle: false
          title: 'On'
          type: entities
        filter:
          exclude:
            - attributes:
                hidden: true
              entity_id: automation.*
          include:
            - entity_id: automation.*
              state: 'on'
        show_empty: false
        type: 'custom:monster-card'
      - card:
          show_header_toggle: false
          title: 'Off'
          type: entities
        filter:
          include:
            - entity_id: automation.*
              state: 'off'
        show_empty: false
        type: 'custom:monster-card'
    icon: 'mdi:home-automation'
    id: automations
    title: Automations`

**Comment by estevez-dev** [comment]
Ah sorry, just realized that this is a custom card. Custom cards is not supported yet. I will change this issue to feature request to support monster-card

**Comment by Schluggi** [comment]
Push

**Comment by Schluggi** [comment]
Since last month monster-card is deprecated. You should use [auto-entities](https://github.com/thomasloven/lovelace-auto-entities) instead.

**Comment by estevez-dev** [comment]
HA Client was discontinued
