### ISSUE TITLE
Multiple instances support

### ISSUE THREAD

**Issue by marci144** [estevez-dev/ha_client#390]
The apps is really great and it's really making a difference from using the html5 version!

One improvement that I would recommend is the possibility of having multiple instances configured in the App! 

All of us have a test instance to try out things before blocking home with some stupid implementation or are managing home and office/shop or a second house somewhere.

moving from one instance to the other .... changing IP and Token is taking quite a while !

So having a multiple instances  would be a very good improvement.

Thanks 
Marcello

**Comment by estevez-dev** [comment]
This is very useful feature. Thanks.

**Comment by estevez-dev** [comment]
HA Client was discontinued
