### ISSUE TITLE
Sensors without icons

### ISSUE THREAD

**Issue by antoweb** [estevez-dev/ha_client#397]
Hi,
The sensors items have no icon

**Comment by estevez-dev** [comment]
Hi. There is a lot of different sensors and sum of them indeed can be without icons. But to fix that I need to know more information.

**Comment by antoweb** [comment]
Hi,
for example icons of tracked device with platform nmap like router, ap, and any device discoverted trouth nmap. THis device in Home Assistant web app are rapresented wioth a small human
