### ISSUE TITLE
A lot of badges issue

### ISSUE THREAD

**Issue by Pirol62** [estevez-dev/ha_client#399]
Hi, the only component, which is missing are the picture cards. So some screens are looking confusing. Please implement these cards 
Could you make the badges scrollable so that they do not need half of the screen on a smaller device like mobiles? 
Thanks for your good work
Jörg

**Comment by estevez-dev** [comment]
#214 is for Picture Cards
Will leave this issue to solve badges problem

**Comment by estevez-dev** [comment]
Done in 1.0.1
