### ISSUE TITLE
Connection refused ERRNO = 111

### ISSUE THREAD

**Issue by manny199** [estevez-dev/ha_client#400]
Hello,
I cant' connect with HA Client.
My home assistant work very well but NO connection from android HA client.
I create a long life token but always error: ERRNO = 111.
Hi also assign port 8123 but in log I found a different port number that change on every time that I try to connect.

Please see screenshot
![20190717_234658](https://user-images.githubusercontent.com/50017898/61414278-dffb1380-a8ed-11e9-8ae8-b899f62e129c.jpg)

**Comment by estevez-dev** [comment]
Do you use http://192.168.1.229:8123 to access your Home Assistant web interface, or there is some domain assigned to it?

**Comment by manny199** [comment]
I have also a domain myhome.duckdns.org.
I have created https SSL certificate in home assistant and long lived token that I pasted on HA Client app but now I have error: token or password wrong. Seems that it does not want to recognize the generated token but this is correct.
![20190718_123423](https://user-images.githubusercontent.com/50017898/61451134-03a77380-a959-11e9-8531-e37b2b148f48.jpg)

**Comment by estevez-dev** [comment]
Just make sure you don't have excess spaces at the beginning and at the end of your long-lived token. Also make sure you copied it all.

**Comment by manny199** [comment]
No space and copied all. Any other suggestion?

**Comment by manny199** [comment]
Can I download release 0.6 apk?

**Comment by estevez-dev** [comment]
0.6.0 is in closed alpha now. It is unstable. Everybody are using 0.5.4 now. Could you please show me a screenshot with error you see on a main screen?

**Comment by manny199** [comment]
The log screenshot is above. Main screen error is: "invalid access token or password (code 6)". 
Seems that it does not want to recognize the generated token but this is correct.

**Comment by manny199** [comment]
Please, can you tell me how to install a not-signed certifcate on home assistant?

**Comment by Racle** [comment]
Same problem. Using ip as http host and defined 8123 as port. 
On logs there is random port where this app is trying to connect, not using 8123.

**Comment by estevez-dev** [comment]
I'll check my setup with local ip and 8123 port

**Comment by estevez-dev** [comment]
Will be resolved with #309
