### ISSUE TITLE
Extra keys not allowed error when the notification pressed

### ISSUE THREAD

**Issue by smartHomeHub** [estevez-dev/ha_client#410]
`Received invalid webhook payload: extra keys not allowed @ data['os_name']. Got 'Android'`

**Comment by estevez-dev** [comment]
Hmmm... They removed that key from API. Strange...

**Comment by estevez-dev** [comment]
What is your Home Assistant version?

**Comment by smartHomeHub** [comment]
The latest stable (0.97.2)

**Comment by estevez-dev** [comment]
I have the same version and can't reproduce it. Could you please describe the exact steps please. The is on a background when notification arrives?

**Comment by smartHomeHub** [comment]
I send a notification through services including title and message. When I tap the notification this error occurs in HA. It happens if the client runs in the foreground or background.

**Comment by smartHomeHub** [comment]
It seems that it happens even if the lifecycle of the app resumes

**Comment by estevez-dev** [comment]
Ok, I see. Thanks
