### ISSUE TITLE
Release 6.2 of app. Component not found

### ISSUE THREAD

**Issue by ChrisTBarnes** [estevez-dev/ha_client#415]
Mobile App component not found in release 6.2

Hi Great app. However, the latest update 3 hours ago, I think 6.2 will no longer work. Had to re login to Home Assistant Now States: - Mobile App component not found. Rebooted my Nokia 7 Plus and problem still the same. Running latest Andriod One with August 2019 security patch. Running Home Assistant 0.97.2 Home Assistant works fine through Open Web UI in app and direct thru web browser.

**Comment by estevez-dev** [comment]
Is it completely not working, or you just see some error? Could you provide a screenshot and a copy of Logs from the app?

**Comment by ChrisTBarnes** [comment]
0822 10:23:55 [Debug] :  AppLifecycleState.inactive
0822 10:23:55 [Debug] :  AppLifecycleState.resumed
0822 10:23:55 [Error] :  Loading settings...
0822 10:23:55 [Error] :  Long-lived token read successful
0822 10:23:55 [Debug] :  Socket connecting: wss://ctbserver.duckdns.org:443/api/websocket...
0822 10:23:56 [Debug] :  [Received] <== {type: auth_required, ha_version: 0.97.2}
0822 10:23:56 [Debug] :  Long-lived token exist
0822 10:23:56 [Debug] :  [Sending] ==> auth request
0822 10:23:56 [Debug] :  [Sending] ==> {"type":"auth","access_token":"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiI1NmQ4MjViNmFlNDM0OTlhYWYyZTZjYzI0MzY1NjQ1MSIsImlhdCI6MTU2NjQ2NDM1MiwiZXhwIjoxNTk4MDAwMzUyfQ.q4kYrW8UnnFux119DfZqYhywzllN5WDfu_CVWlakb4I"}
0822 10:23:56 [Debug] :  [Received] <== {type: auth_ok, ha_version: 0.97.2}
0822 10:23:56 [Debug] :  doConnect is finished 1
0822 10:23:56 [Debug] :  Authentication complete
0822 10:23:56 [Debug] :  [Sending] ==> {"type":"get_states","id":1}
0822 10:23:56 [Debug] :  [Sending] ==> {"type":"lovelace/config","id":2}
0822 10:23:56 [Debug] :  [Sending] ==> {"type":"get_config","id":3}
0822 10:23:56 [Debug] :  [Sending] ==> {"type":"get_services","id":4}
0822 10:23:56 [Debug] :  [Sending] ==> {"type":"auth/current_user","id":5}
0822 10:23:56 [Debug] :  [Sending] ==> {"type":"get_panels","id":6}
0822 10:23:56 [Debug] :  [Sending] ==> {"type":"subscribe_events","id":7,"event_type":"state_changed"}
0822 10:23:56 [Debug] :  [Received] <== Request id 1 was successful
0822 10:23:56 [Debug] :  Parsing 109 Home Assistant entities
0822 10:23:56 [Debug] :  [Received] <== Request id 3 was successful
0822 10:23:56 [Debug] :  [Received] <== Request id 6 was successful
0822 10:23:56 [Debug] :  [Received] <== Request id 7 was successful
0822 10:23:56 [Debug] :  [Received] <== Request id 4 was successful
0822 10:23:56 [Debug] :  Services received
0822 10:23:56 [Debug] :  [Received] <== Request id 5 was successful
0822 10:23:56 [Debug] :  [Received] <== Request id 2 was successful
0822 10:24:04 [Debug] :  [Received] <== event.state_changed: sensor.memory_free
0822 10:24:21 [Error] :  Loading settings...
0822 10:24:21 [Error] :  Long-lived token read successful
0822 10:24:21 [Debug] :  Socket disconnecting...
0822 10:24:21 [Debug] :  Socket connecting: wss://ctbserver.duckdns.org:443/api/websocket...
0822 10:24:22 [Debug] :  [Received] <== {type: auth_required, ha_version: 0.97.2}
0822 10:24:22 [Debug] :  Long-lived token exist
0822 10:24:22 [Debug] :  [Sending] ==> auth request
0822 10:24:22 [Debug] :  [Sending] ==> {"type":"auth","access_token":"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiI1NmQ4MjViNmFlNDM0OTlhYWYyZTZjYzI0MzY1NjQ1MSIsImlhdCI6MTU2NjQ2NDM1MiwiZXhwIjoxNTk4MDAwMzUyfQ.q4kYrW8UnnFux119DfZqYhywzllN5WDfu_CVWlakb4I"}
0822 10:24:22 [Debug] :  [Received] <== {type: auth_ok, ha_version: 0.97.2}
0822 10:24:22 [Debug] :  doConnect is finished 1
0822 10:24:22 [Debug] :  Authentication complete
0822 10:24:22 [Debug] :  [Sending] ==> {"type":"get_states","id":8}
0822 10:24:22 [Debug] :  [Sending] ==> {"type":"lovelace/config","id":9}
0822 10:24:22 [Debug] :  [Sending] ==> {"type":"get_config","id":10}
0822 10:24:22 [Debug] :  [Sending] ==> {"type":"get_services","id":11}
0822 10:24:22 [Debug] :  [Sending] ==> {"type":"auth/current_user","id":12}
0822 10:24:22 [Debug] :  [Sending] ==> {"type":"get_panels","id":13}
0822 10:24:22 [Debug] :  [Sending] ==> {"type":"subscribe_events","id":14,"event_type":"state_changed"}
0822 10:24:22 [Debug] :  [Received] <== Request id 8 was successful
0822 10:24:22 [Debug] :  Parsing 109 Home Assistant entities
0822 10:24:22 [Debug] :  [Received] <== Request id 10 was successful
0822 10:24:22 [Debug] :  [Received] <== Request id 13 was successful
0822 10:24:22 [Debug] :  [Received] <== Request id 14 was successful
0822 10:24:22 [Debug] :  [Received] <== Request id 11 was successful
0822 10:24:22 [Debug] :  Services received
0822 10:24:22 [Debug] :  [Received] <== Request id 12 was successful
0822 10:24:22 [Debug] :  [Received] <== Request id 9 was successful

**Comment by estevez-dev** [comment]
According to [documentation](http://ha-client.homemade.systems/docs#requirements):

> To connect to your Home Assistant instance with HA Client you need http, websocket_api and mobile_app components to be enabled

So you just need to add this to your `configuration.yaml`:

```yaml
mobile_app:
```

And restart your Home Assistant

**Comment by ChrisTBarnes** [comment]
Hi
Many thanks.  All is now working.
