### ISSUE TITLE
Error getting lovelace config: No config found

### ISSUE THREAD

**Issue by SzymonZy** [estevez-dev/ha_client#419]
Hello 
Together with latest update of HA (hass.io) my HA Client stopped to run with this comment. If I switch to web interface it loads ok.

**Comment by estevez-dev** [comment]
Could you please copy logs from the app right after error appears and post it here? Thanks.

**Comment by SzymonZy** [comment]
0824 21:27:44 [Error] :  Loading settings...
0824 21:27:44 [Error] :  Long-lived token read successful
0824 21:27:44 [Debug] :  Socket disconnecting...
0824 21:27:44 [Debug] :  Socket connecting: ws://MYDOMAIN:8123/api/websocket...
0824 21:27:45 [Debug] :  [Received] <== {type: auth_required, ha_version: 0.97.2}
0824 21:27:45 [Debug] :  Long-lived token exist
0824 21:27:45 [Debug] :  [Sending] ==> auth request
0824 21:27:45 [Debug] :  [Sending] ==> {"type":"auth","access_token":"REMOVED"}
0824 21:27:45 [Debug] :  [Received] <== {type: auth_ok, ha_version: 0.97.2}
0824 21:27:45 [Debug] :  doConnect is finished 1
0824 21:27:45 [Debug] :  Authentication complete
0824 21:27:45 [Debug] :  [Sending] ==> {"type":"get_states","id":8}
0824 21:27:45 [Debug] :  [Sending] ==> {"type":"lovelace/config","id":9}
0824 21:27:45 [Debug] :  [Sending] ==> {"type":"get_config","id":10}
0824 21:27:45 [Debug] :  [Sending] ==> {"type":"get_services","id":11}
0824 21:27:45 [Debug] :  [Sending] ==> {"type":"auth/current_user","id":12}
0824 21:27:45 [Debug] :  [Sending] ==> {"type":"get_panels","id":13}
0824 21:27:45 [Debug] :  [Sending] ==> {"type":"subscribe_events","id":14,"event_type":"state_changed"}
0824 21:27:45 [Debug] :  [Received] <== Request id 8 was successful
0824 21:27:45 [Debug] :  [Received] <== Request id 10 was successful
0824 21:27:45 [Debug] :  Parsing 19 Home Assistant entities
0824 21:27:45 [Error] :  [Received] <== Error received on request id 9: {code: config_not_found, message: No config found.}
0824 21:27:45 [Debug] :  [Received] <== Request id 11 was successful
0824 21:27:45 [Debug] :  [Received] <== Request id 12 was successful
0824 21:27:45 [Debug] :  [Received] <== Request id 13 was successful
0824 21:27:45 [Debug] :  [Received] <== Request id 14 was successful
0824 21:27:45 [Debug] :  Services received
0824 21:27:47 [Error] :  Loading settings...
0824 21:27:47 [Error] :  Long-lived token read successful
0824 21:27:47 [Debug] :  Socket disconnecting...
0824 21:27:47 [Debug] :  Socket connecting: ws://MYDOMAIN:8123/api/websocket...
0824 21:27:47 [Debug] :  [Received] <== {type: auth_required, ha_version: 0.97.2}
0824 21:27:47 [Debug] :  Long-lived token exist
0824 21:27:47 [Debug] :  [Sending] ==> auth request
0824 21:27:47 [Debug] :  [Sending] ==> {"type":"auth","access_token":"REMOVED"}
0824 21:27:47 [Debug] :  [Received] <== {type: auth_ok, ha_version: 0.97.2}
0824 21:27:47 [Debug] :  doConnect is finished 1
0824 21:27:47 [Debug] :  Authentication complete
0824 21:27:47 [Debug] :  [Sending] ==> {"type":"get_states","id":15}
0824 21:27:47 [Debug] :  [Sending] ==> {"type":"lovelace/config","id":16}
0824 21:27:47 [Debug] :  [Sending] ==> {"type":"get_config","id":17}
0824 21:27:47 [Debug] :  [Sending] ==> {"type":"get_services","id":18}
0824 21:27:47 [Debug] :  [Sending] ==> {"type":"auth/current_user","id":19}
0824 21:27:47 [Debug] :  [Sending] ==> {"type":"get_panels","id":20}
0824 21:27:47 [Debug] :  [Sending] ==> {"type":"subscribe_events","id":21,"event_type":"state_changed"}
0824 21:27:47 [Debug] :  [Received] <== Request id 15 was successful
0824 21:27:47 [Debug] :  [Received] <== Request id 17 was successful
0824 21:27:47 [Debug] :  [Received] <== Request id 20 was successful
0824 21:27:47 [Debug] :  [Received] <== Request id 21 was successful
0824 21:27:47 [Debug] :  Parsing 19 Home Assistant entities
0824 21:27:47 [Error] :  [Received] <== Error received on request id 16: {code: config_not_found, message: No config found.}
0824 21:27:47 [Debug] :  [Received] <== Request id 18 was successful
0824 21:27:47 [Debug] :  [Received] <== Request id 19 was successful
0824 21:27:47 [Debug] :  Services received
0824 21:27:51 [Debug] :  doConnect is finished 2
0824 21:27:51 [Debug] :  [Sending] ==> {"type":"get_states","id":22}
0824 21:27:51 [Debug] :  [Sending] ==> {"type":"lovelace/config","id":23}
0824 21:27:51 [Debug] :  [Sending] ==> {"type":"get_config","id":24}
0824 21:27:51 [Debug] :  [Sending] ==> {"type":"get_services","id":25}
0824 21:27:51 [Debug] :  [Sending] ==> {"type":"auth/current_user","id":26}
0824 21:27:51 [Debug] :  [Sending] ==> {"type":"get_panels","id":27}
0824 21:27:51 [Debug] :  [Sending] ==> {"type":"subscribe_events","id":28,"event_type":"state_changed"}
0824 21:27:52 [Debug] :  [Received] <== Request id 22 was successful
0824 21:27:52 [Debug] :  Parsing 19 Home Assistant entities
0824 21:27:52 [Error] :  [Received] <== Error received on request id 23: {code: config_not_found, message: No config found.}
0824 21:27:52 [Debug] :  [Received] <== Request id 24 was successful
0824 21:27:52 [Debug] :  [Received] <== Request id 27 was successful
0824 21:27:52 [Debug] :  [Received] <== Request id 28 was successful
0824 21:27:52 [Debug] :  [Received] <== Request id 25 was successful
0824 21:27:52 [Debug] :  [Received] <== Request id 26 was successful
0824 21:27:52 [Debug] :  Services received
0824 21:27:54 [Error] :  Loading settings...
0824 21:27:54 [Error] :  Long-lived token read successful
0824 21:27:54 [Debug] :  Socket disconnecting...
0824 21:27:54 [Debug] :  Socket connecting: ws://MYDOMAIN:8123/api/websocket...
0824 21:27:54 [Debug] :  [Received] <== {type: auth_required, ha_version: 0.97.2}
0824 21:27:54 [Debug] :  Long-lived token exist
0824 21:27:54 [Debug] :  [Sending] ==> auth request
0824 21:27:54 [Debug] :  [Sending] ==> {"type":"auth","access_token":"REMOVED"}
0824 21:27:54 [Debug] :  [Received] <== {type: auth_ok, ha_version: 0.97.2}
0824 21:27:54 [Debug] :  doConnect is finished 1
0824 21:27:54 [Debug] :  Authentication complete
0824 21:27:54 [Debug] :  [Sending] ==> {"type":"get_states","id":29}
0824 21:27:54 [Debug] :  [Sending] ==> {"type":"lovelace/config","id":30}
0824 21:27:54 [Debug] :  [Sending] ==> {"type":"get_config","id":31}
0824 21:27:54 [Debug] :  [Sending] ==> {"type":"get_services","id":32}
0824 21:27:54 [Debug] :  [Sending] ==> {"type":"auth/current_user","id":33}
0824 21:27:54 [Debug] :  [Sending] ==> {"type":"get_panels","id":34}
0824 21:27:54 [Debug] :  [Sending] ==> {"type":"subscribe_events","id":35,"event_type":"state_changed"}
0824 21:27:54 [Debug] :  [Received] <== Request id 29 was successful
0824 21:27:54 [Debug] :  Parsing 19 Home Assistant entities
0824 21:27:54 [Error] :  [Received] <== Error received on request id 30: {code: config_not_found, message: No config found.}
0824 21:27:54 [Debug] :  [Received] <== Request id 31 was successful
0824 21:27:54 [Debug] :  [Received] <== Request id 32 was successful
0824 21:27:54 [Debug] :  [Received] <== Request id 34 was successful
0824 21:27:54 [Debug] :  [Received] <== Request id 35 was successful
0824 21:27:54 [Debug] :  [Received] <== Request id 33 was successful
0824 21:27:54 [Debug] :  Services received
0824 21:27:55 [Error] :  Bad state: Cannot add event after closing
0824 21:27:55 [Error] :  #0      _StreamController.add (dart:async/stream_controller.dart:585)
#1      _WebSocketConsumer.add (dart:_http/websocket_impl.dart:953)
#2      _WebSocketImpl.set:pingInterval.<anonymous closure> (dart:_http/websocket_impl.dart:1198)
#3      _rootRun (dart:async/zone.dart:1120)
#4      _CustomZone.run (dart:async/zone.dart:1021)
#5      _CustomZone.runGuarded (dart:async/zone.dart:923)
#6      _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963)
#7      _rootRun (dart:async/zone.dart:1124)
#8      _CustomZone.run (dart:async/zone.dart:1021)
#9      _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947)
#10     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:21)
#11     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:382)
#12     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:416)
#13     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172

**Comment by estevez-dev** [comment]
Do you use Lovelace at all? Or your UI is based on groups? If you are not using Lovelace UI, you should disable it in Connection settings in the app.

**Comment by tschork** [comment]
I have the same issue, and I am using lovelace.
I cannot say exactly when it started, it cpuld be linked to me updating hass to the latest version. 
My log is as follow:

0825 17:19:32 [Debug] :  [Sending] ==> {"type":"get_states","id":35}
0825 17:19:32 [Debug] :  [Sending] ==> {"type":"get_config","id":36}
0825 17:19:32 [Debug] :  [Sending] ==> {"type":"get_services","id":37}
0825 17:19:32 [Debug] :  [Sending] ==> {"type":"auth/current_user","id":38}
0825 17:19:32 [Debug] :  [Sending] ==> {"type":"get_panels","id":39}
0825 17:19:32 [Debug] :  [Sending] ==> {"type":"subscribe_events","id":40,"event_type":"state_changed"}
0825 17:19:32 [Debug] :  [Received] <== Request id 35 was successful
0825 17:19:32 [Debug] :  [Received] <== Request id 36 was successful
0825 17:19:32 [Debug] :  Parsing 41 Home Assistant entities
0825 17:19:32 [Debug] :  [Received] <== Request id 37 was successful
0825 17:19:32 [Debug] :  [Received] <== Request id 38 was successful
0825 17:19:32 [Debug] :  [Received] <== Request id 39 was successful
0825 17:19:32 [Debug] :  [Received] <== Request id 40 was successful
0825 17:19:32 [Debug] :  Services received
0825 17:19:38 [Error] :  Bad state: Cannot add event after closing
0825 17:19:38 [Error] :  #0      _StreamController.add (dart:async/stream_controller.dart:585)
#1      _WebSocketConsumer.add (dart:_http/websocket_impl.dart:953)
#2      _WebSocketImpl.set:pingInterval.<anonymous closure> (dart:_http/websocket_impl.dart:1198)
#3      _rootRun (dart:async/zone.dart:1120)
#4      _CustomZone.run (dart:async/zone.dart:1021)
#5      _CustomZone.runGuarded (dart:async/zone.dart:923)
#6      _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963)
#7      _rootRun (dart:async/zone.dart:1124)
#8      _CustomZone.run (dart:async/zone.dart:1021)
#9      _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947)
#10     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:21)
#11     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:382)
#12     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:416)
#13     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172)

0825 17:19:40 [Debug] :  Settings changed. Saving...
0825 17:19:40 [Debug] :  Settings change event: reconnect=true
0825 17:19:40 [Error] :  Loading settings...
0825 17:19:40 [Error] :  Long-lived token read successful
0825 17:19:40 [Debug] :  Socket disconnecting...
0825 17:19:40 [Debug] :  Socket connecting: ws://hass.schork.home:8123/api/websocket...
0825 17:19:40 [Debug] :  [Received] <== {type: auth_required, ha_version: 0.97.2}
0825 17:19:40 [Debug] :  Long-lived token exist
0825 17:19:40 [Debug] :  [Sending] ==> auth request
0825 17:19:40 [Debug] :  [Sending] ==> {"type":"auth","access_token":"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJlNWJjNzY4MWU3NjE0MzMzYjIyNDg4ODMzNjI1MWJiZCIsImlhdCI6MTU2NjY1NjQ1NCwiZXhwIjoxNTk4MTkyNDU0fQ.DxjDEaXQxPY9mfEl8884YjwcHI48VTgxeNw6Ywq45gE"}
0825 17:19:40 [Debug] :  [Received] <== {type: auth_ok, ha_version: 0.97.2}
0825 17:19:40 [Debug] :  doConnect is finished 1
0825 17:19:40 [Debug] :  Authentication complete
0825 17:19:40 [Debug] :  [Sending] ==> {"type":"get_states","id":41}
0825 17:19:40 [Debug] :  [Sending] ==> {"type":"lovelace/config","id":42}
0825 17:19:40 [Debug] :  [Sending] ==> {"type":"get_config","id":43}
0825 17:19:40 [Debug] :  [Sending] ==> {"type":"get_services","id":44}
0825 17:19:40 [Debug] :  [Sending] ==> {"type":"auth/current_user","id":45}
0825 17:19:40 [Debug] :  [Sending] ==> {"type":"get_panels","id":46}
0825 17:19:40 [Debug] :  [Sending] ==> {"type":"subscribe_events","id":47,"event_type":"state_changed"}
0825 17:19:40 [Debug] :  [Received] <== Request id 41 was successful
0825 17:19:40 [Error] :  [Received] <== Error received on request id 42: {code: config_not_found, message: No config found.}
0825 17:19:40 [Debug] :  [Received] <== Request id 43 was successful
0825 17:19:40 [Debug] :  [Received] <== Request id 44 was successful
0825 17:19:40 [Debug] :  [Received] <== Request id 46 was successful
0825 17:19:40 [Debug] :  Parsing 41 Home Assistant entities
0825 17:19:40 [Debug] :  Services received
0825 17:19:40 [Debug] :  [Received] <== Request id 45 was successful
0825 17:19:40 [Debug] :  [Received] <== Request id 47 was successful
0825 17:19:41 [Error] :  Loading settings...
0825 17:19:41 [Error] :  Long-lived token read successful
0825 17:19:41 [Debug] :  Socket disconnecting...
0825 17:19:41 [Debug] :  Socket connecting: ws://hass.schork.home:8123/api/websocket...
0825 17:19:41 [Debug] :  [Received] <== {type: auth_required, ha_version: 0.97.2}
0825 17:19:41 [Debug] :  Long-lived token exist
0825 17:19:41 [Debug] :  [Sending] ==> auth request
0825 17:19:41 [Debug] :  [Sending] ==> {"type":"auth","access_token":"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJlNWJjNzY4MWU3NjE0MzMzYjIyNDg4ODMzNjI1MWJiZCIsImlhdCI6MTU2NjY1NjQ1NCwiZXhwIjoxNTk4MTkyNDU0fQ.DxjDEaXQxPY9mfEl8884YjwcHI48VTgxeNw6Ywq45gE"}
0825 17:19:41 [Debug] :  [Received] <== {type: auth_ok, ha_version: 0.97.2}
0825 17:19:41 [Debug] :  doConnect is finished 1
0825 17:19:41 [Debug] :  Authentication complete
0825 17:19:41 [Debug] :  [Sending] ==> {"type":"get_states","id":48}
0825 17:19:41 [Debug] :  [Sending] ==> {"type":"lovelace/config","id":49}
0825 17:19:41 [Debug] :  [Sending] ==> {"type":"get_config","id":50}
0825 17:19:41 [Debug] :  [Sending] ==> {"type":"get_services","id":51}
0825 17:19:41 [Debug] :  [Sending] ==> {"type":"auth/current_user","id":52}
0825 17:19:41 [Debug] :  [Sending] ==> {"type":"get_panels","id":53}
0825 17:19:41 [Debug] :  [Sending] ==> {"type":"subscribe_events","id":54,"event_type":"state_changed"}
0825 17:19:41 [Debug] :  [Received] <== Request id 48 was successful
0825 17:19:41 [Debug] :  Parsing 41 Home Assistant entities
0825 17:19:41 [Error] :  [Received] <== Error received on request id 49: {code: config_not_found, message: No config found.}
0825 17:19:41 [Debug] :  [Received] <== Request id 50 was successful
0825 17:19:41 [Debug] :  [Received] <== Request id 51 was successful
0825 17:19:41 [Debug] :  [Received] <== Request id 52 was successful
0825 17:19:41 [Debug] :  [Received] <== Request id 53 was successful
0825 17:19:41 [Debug] :  [Received] <== Request id 54 was successful
0825 17:19:41 [Debug] :  Services received
0825 17:19:46 [Error] :  Bad state: Cannot add event after closing
0825 17:19:46 [Error] :  #0      _StreamController.add (dart:async/stream_controller.dart:585)
#1      _WebSocketConsumer.add (dart:_http/websocket_impl.dart:953)
#2      _WebSocketImpl.set:pingInterval.<anonymous closure> (dart:_http/websocket_impl.dart:1198)
#3      _rootRun (dart:async/zone.dart:1120)
#4      _CustomZone.run (dart:async/zone.dart:1021)
#5      _CustomZone.runGuarded (dart:async/zone.dart:923)
#6      _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963)
#7      _rootRun (dart:async/zone.dart:1124)
#8      _CustomZone.run (dart:async/zone.dart:1021)
#9      _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947)
#10     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:21)
#11     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:382)
#12     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:416)
#13     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172)

0825 17:19:46 [Debug] :  AppLifecycleState.inactive
0825 17:19:46 [Debug] :  AppLifecycleState.paused
0825 17:19:47 [Error] :  Bad state: Cannot add event after closing
0825 17:19:47 [Error] :  #0      _StreamController.add (dart:async/stream_controller.dart:585)
#1      _WebSocketConsumer.add (dart:_http/websocket_impl.dart:953)
#2      _WebSocketImpl.set:pingInterval.<anonymous closure> (dart:_http/websocket_impl.dart:1198)
#3      _rootRun (dart:async/zone.dart:1120)
#4      _CustomZone.run (dart:async/zone.dart:1021)
#5      _CustomZone.runGuarded (dart:async/zone.dart:923)
#6      _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963)
#7      _rootRun (dart:async/zone.dart:1124)
#8      _CustomZone.run (dart:async/zone.dart:1021)
#9      _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947)
#10     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:21)
#11     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:382)
#12     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:416)
#13     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172)

0825 17:19:55 [Error] :  Bad state: Cannot add event after closing
0825 17:19:55 [Error] :  #0      _StreamController.add (dart:async/stream_controller.dart:585)
#1      _WebSocketConsumer.add (dart:_http/websocket_impl.dart:953)
#2      _WebSocketImpl.set:pingInterval.<anonymous closure> (dart:_http/websocket_impl.dart:1198)
#3      _rootRun (dart:async/zone.dart:1120)
#4      _CustomZone.run (dart:async/zone.dart:1021)
#5      _CustomZone.runGuarded (dart:async/zone.dart:923)
#6      _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963)
#7      _rootRun (dart:async/zone.dart:1124)
#8      _CustomZone.run (dart:async/zone.dart:1021)
#9      _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947)
#10     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:21)
#11     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:382)
#12     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:416)
#13     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172)

0825 17:19:59 [Debug] :  [Received] <== event.state_changed: sensor.time
0825 17:20:43 [Debug] :  AppLifecycleState.inactive
0825 17:20:43 [Debug] :  AppLifecycleState.resumed
0825 17:20:43 [Debug] :  doConnect is finished 2
0825 17:20:43 [Debug] :  [Sending] ==> {"type":"get_states","id":55}
0825 17:20:43 [Debug] :  [Sending] ==> {"type":"lovelace/config","id":56}
0825 17:20:43 [Debug] :  [Sending] ==> {"type":"get_config","id":57}
0825 17:20:43 [Debug] :  [Sending] ==> {"type":"get_services","id":58}
0825 17:20:43 [Debug] :  [Sending] ==> {"type":"auth/current_user","id":59}
0825 17:20:43 [Debug] :  [Sending] ==> {"type":"get_panels","id":60}
0825 17:20:43 [Debug] :  [Sending] ==> {"type":"subscribe_events","id":61,"event_type":"state_changed"}
0825 17:20:43 [Debug] :  [Received] <== Request id 55 was successful
0825 17:20:43 [Debug] :  Parsing 41 Home Assistant entities
0825 17:20:43 [Debug] :  [Received] <== Request id 57 was successful
0825 17:20:43 [Error] :  [Received] <== Error received on request id 56: {code: config_not_found, message: No config found.}
0825 17:20:43 [Debug] :  [Received] <== Request id 58 was successful
0825 17:20:43 [Debug] :  [Received] <== Request id 59 was successful
0825 17:20:43 [Debug] :  [Received] <== Request id 60 was successful
0825 17:20:43 [Debug] :  [Received] <== Request id 61 was successful
0825 17:20:43 [Debug] :  Services received

**Comment by tschork** [comment]
by the way, my hass version is 0.97.2

**Comment by ps1x** [comment]
Subscribing. Getting same error, though web version works with lovelace.

**Comment by estevez-dev** [comment]
@ps1x , try to disable Lovelace in Connection settings. If you will see the same ui as on the web, then you just don't use Lovelace

**Comment by polarbearshirt** [comment]
@estevez-dev Great work so far. Just wanted to add that I also have the "Error getting lovelace config: No config found" error when lovelace UI is enabled on the mobile app. I connect via http and SSL is turned off in the app. The following are screenshots from (1) the app with lovelace turned on, (2) app with lovelace turned off, and (3) the mobile browser with lovelace default.

![app_with_lovelace_on](https://user-images.githubusercontent.com/55421737/65894508-c6029600-e35e-11e9-9715-0673f32fe929.png)
![app_with_lovelace_off](https://user-images.githubusercontent.com/55421737/65894334-72904800-e35e-11e9-86a6-ab705ce6c97f.png)
![with_lovelace_via_browser](https://user-images.githubusercontent.com/55421737/65894371-863bae80-e35e-11e9-825b-53c339ce56e8.png)

Here is the log output:
0930 08:47:26 [Debug] :  AppLifecycleState.inactive
0930 08:47:26 [Debug] :  AppLifecycleState.resumed
0930 08:47:26 [Debug] :  [Sending] ==> {"type":"get_states","id":191}
0930 08:47:26 [Debug] :  [Sending] ==> {"type":"lovelace/config","id":192}
0930 08:47:26 [Debug] :  [Sending] ==> {"type":"get_config","id":193}
0930 08:47:26 [Debug] :  [Sending] ==> {"type":"get_services","id":194}
0930 08:47:26 [Debug] :  [Sending] ==> {"type":"auth/current_user","id":195}
0930 08:47:26 [Debug] :  [Sending] ==> {"type":"get_panels","id":196}
0930 08:47:26 [Debug] :  [Sending] ==> {"type":"subscribe_events","id":197,"event_type":"state_changed"}
0930 08:47:26 [Debug] :  [Received] <== Request id 191 was successful
0930 08:47:26 [Debug] :  [Received] <== Request id 193 was successful
0930 08:47:26 [Debug] :  Parsing 19 Home Assistant entities
0930 08:47:26 [Error] :  [Received] <== Error received on request id 192: {code: config_not_found, message: No config found.}
0930 08:47:26 [Debug] :  [Received] <== Request id 194 was successful
0930 08:47:26 [Debug] :  [Received] <== Request id 195 was successful
0930 08:47:26 [Debug] :  Got 17 services
0930 08:47:26 [Debug] :  Media extractor: null
0930 08:47:26 [Debug] :  [Received] <== Request id 196 was successful
0930 08:47:26 [Debug] :  [Received] <== Request id 197 was successful
0930 08:47:30 [Debug] :  [WebView] Injecting external auth JS
0930 08:47:35 [Debug] :  [Received] <== event.state_changed: sun.sun
0930 08:47:35 [Debug] :  [Received] <== event.state_changed: sun.sun

**Comment by estevez-dev** [comment]
If your Home Assistant says there is no lovelace config found it means there is no lovelace config found. There is nothing I can do if there no config found. Also if you disabled "Use Lovelace UI" in the app and see the same UI as in the web, it means that you are not using Lovelace UI at all.

**Comment by oblitum** [comment]
It's weird though as my default HA setup states the default UI is lovelace, but I have to mark the app the reverse to avoid this issue.

**Comment by estevez-dev** [comment]
> It's weird though as my default HA setup states the default UI is lovelace, but I have to mark the app the reverse to avoid this issue.

And you still has the same cards in web ui and in the app?

**Comment by oblitum** [comment]
@estevez-dev yes, but the app's more useful UI is available when I click on my profile, then it show a menu that resembles the web UI, for example, the overview shows my weather card, just like the web one.

Forgot to mention, the web URL contains /lovelace/.

**Comment by estevez-dev** [comment]
I think you are viewing your web UI in a webview. It is not HA Client interface

**Comment by oblitum** [comment]
> Forgot to mention, the web URL contains `/lovelace/`.

That's on my PC accessing the browser, to confirm it's using lovelace by default.

> I think you are viewing your web UI in a webview. It is not HA Client interface

You mean the app is doing it? I simply can't know as it just seems part of the app when I click on my profile name, it UI appearance is still the same. I just get a second level of menus, the content of which are more equal to the ones I get on PC.

**Comment by estevez-dev** [comment]
The app has a webview to open unsupported panels in it. It will be removed in 0.7.0 and replaced with Chrome Custom Tab, but still it will be a web UI opened by the app. Clicking your profile picture opens your Profile settings (Web UI) in webview. Then you are able to navigate to main page inside that webview.

**Comment by oblitum** [comment]
OK.

The app has two cards overview. Currently on my PC/lovelace I just have weather card. On the app, when I start it, it doesn't show any card on the initial overview. I can only see the weather card on the second level overview, after browsing my user name.

**Comment by oblitum** [comment]
Correction. Actually, there's weather card on the initial overview, but it's not a "pretty" card. It's just like a list, with a title "weather" and a "partlycloudy" result. The card on the second level overview is equal with the one on lovelace, it should a sun picture, etc.

**Comment by estevez-dev** [comment]
Yes. HA Client is not supporting weather card yet. "The second level overview" it's just your web UI in a webview, the one you seeing on PC.

**Comment by oblitum** [comment]
OK, got it. Still the original issue is confusing, as I access lovelace view on PC, but the app claims there isn't.

**Comment by estevez-dev** [comment]
Actually, the app saying exactly the same phrase it gets from Home Assistant API. So looks like this is Home Assistant issue. But I any way 'll try to switch to states UI without showing this error

**Comment by mchwalisz** [comment]
I have encountered the same problem when I was using the auto generated lovelace UI. Switching to manual mode "fixes" the app.

IMO, switching to manual mode is a workaround and the app should work regardless of the setting. Cannot say on which side there is a problem now.
