### ISSUE TITLE
Camera view improvement

### ISSUE THREAD

**Issue by hellcry37** [estevez-dev/ha_client#420]
This was ok until 20/08/2019 update where i have to put in my user and password, no more token access, and for want? App just created another token .... what was the problem with old login style via token directly?

Also camera worked great, now when i click it i see a yellow pc screen and when i click that it open in full screen the camera but is only black, not working anymore. Just as a reference before 20/08/2019 worked very well.

**Comment by estevez-dev** [comment]
Logging in with manual token will be back soon: #421

**Comment by estevez-dev** [comment]
For camera issue just try to zoom out

**Comment by cristianlivella** [comment]
Same camera problem here. Yes, I can zoom out, but it's uncomfortable do it every time... I prefer the camera view in the previous version, I hope it will be re introduced.

**Comment by hellcry37** [comment]
same as cristianlivella, I prefer the old approach. what was wrong with it, it worked very well and did not have to do 3 or 4 steps to see my camera

**Comment by estevez-dev** [comment]
The problem with old approach was in supporting formats. I agree it needs to be improved. Will transform this into a CR.

**Comment by estevez-dev** [comment]
Will be released with 0.8.0
