### ISSUE TITLE
Error - NoSuchMethodError

### ISSUE THREAD

**Issue by DarwinData** [estevez-dev/ha_client#422]
When I launch HA Client I see a dark red screen with lots of these error messages:
NoSuchMethodError: The getter 'isNotEmpty' was called on null
Receiver: null
Tried calling: isNotEmpty

**Comment by estevez-dev** [comment]
Copy logs please and post it here. Thanks.

**Comment by estevez-dev** [comment]
Thanks

**Comment by estevez-dev** [comment]
Also do you use Lovelace UI on the web version? Or your UI is group-based?

**Comment by estevez-dev** [comment]
Could you please attach your groups.yaml here?

**Comment by estevez-dev** [comment]
Sure! Just send it to vyalov.egor at gmail.com
