### ISSUE TITLE
The getter is not empty was called on null

### ISSUE THREAD

**Issue by verylatestarter** [estevez-dev/ha_client#423]
Version 0.6.3
I am now getting the above error message over and over on each tab in the UI. The lovelace looks to work but as I only have a single test card here that is of limited use at the moment. 
![Screenshot_20190827_181703_com keyboardcrumbs haclient](https://user-images.githubusercontent.com/18047189/63794218-6b0df700-c8f9-11e9-9e61-ee05233eb728.jpg)

**Comment by estevez-dev** [comment]
Fixed in #422
