### ISSUE TITLE
Screen artifact visible on entity cards.

### ISSUE THREAD

**Issue by tdejneka** [estevez-dev/ha_client#424]
I first noticed this issue in version 0.6 and also see it in the current version, 0.6.3.  

- There's a narrow shaded bar that appears at the top of entity cards. 
- The bar flickers and appears to moves horizontally (or flash/toggle between two locations) when the page is scrolled vertically.
- Sometimes the bar disappears completely then re-appears.
- It doesn't appear at the top of the first card, only on the second and subsequent cards on the page.
- This bar was never displayed prior to version 0.6.

![Screenshot_20190827-163929 1](https://user-images.githubusercontent.com/44732909/63808011-f5039300-c8ec-11e9-8e48-f30cdd706aed.png)

**Comment by estevez-dev** [comment]
Nice one ))  What device you are using?

**Comment by tdejneka** [comment]
FYI

Something must have changed in 0.6.7 because the screen artifacts are no longer present.

They were visible (on my phone) in every release since I first noticed them in 0.6 but now, in 0.6.7, they are gone.

**Comment by estevez-dev** [comment]
There was no any changes to entity cards, but there was several updates of Flutter framework, so I'm thinking this was an issue of framework itself.
Closing for now. Feel free to report again if needed.
Thank for letting me know.
