### ISSUE TITLE
Nosuchmethod error

### ISSUE THREAD

**Issue by mwestra** [estevez-dev/ha_client#439]
For one screen I got the typical redscreen with nosuchmethodeerror
Log:
0903 09:18:09 [Debug] :  AppLifecycleState.inactive
0903 09:18:09 [Debug] :  AppLifecycleState.resumed
0903 09:18:09 [Error] :  Loading settings...
0903 09:18:09 [Error] :  Long-lived token read successful
0903 09:18:09 [Debug] :  Socket connecting...
0903 09:18:09 [Debug] :  [Received] <== {type: auth_required, ha_version: 0.98.2}
0903 09:18:09 [Debug] :  Long-lived token exist
0903 09:18:09 [Debug] :  [Sending] ==> auth request
0903 09:18:09 [Debug] :  [Sending] ==> type=auth
0903 09:18:09 [Debug] :  [Received] <== {type: auth_ok, ha_version: 0.98.2}
0903 09:18:09 [Debug] :  Authentication complete
0903 09:18:09 [Debug] :  [Sending] ==> {"type":"get_states","id":1}
0903 09:18:09 [Debug] :  [Sending] ==> {"type":"lovelace/config","id":2}
0903 09:18:09 [Debug] :  [Sending] ==> {"type":"get_config","id":3}
0903 09:18:09 [Debug] :  [Sending] ==> {"type":"get_services","id":4}
0903 09:18:09 [Debug] :  [Sending] ==> {"type":"auth/current_user","id":5}
0903 09:18:09 [Debug] :  [Sending] ==> {"type":"get_panels","id":6}
0903 09:18:09 [Debug] :  [Sending] ==> {"type":"subscribe_events","id":7,"event_type":"state_changed"}
0903 09:18:09 [Debug] :  [Received] <== Request id 1 was successful
0903 09:18:09 [Debug] :  Parsing 449 Home Assistant entities
0903 09:18:09 [Debug] :  [Received] <== Request id 3 was successful
0903 09:18:09 [Debug] :  [Received] <== Request id 6 was successful
0903 09:18:09 [Debug] :  [Received] <== Request id 7 was successful
0903 09:18:09 [Debug] :  [Received] <== Request id 4 was successful
0903 09:18:09 [Debug] :  Services received
0903 09:18:09 [Debug] :  [Received] <== Request id 5 was successful
0903 09:18:09 [Debug] :  [Received] <== Request id 2 was successful
0903 09:18:09 [Debug] :  Creating Lovelace UI
0903 09:18:09 [Debug] :  --Title: xxx
0903 09:18:09 [Debug] :  --Views count: 12
0903 09:18:09 [Debug] :  ----view id: null
0903 09:18:09 [Debug] :  ----view id: null
0903 09:18:09 [Debug] :  ----view id: null
0903 09:18:09 [Debug] :  ----view id: null
0903 09:18:09 [Debug] :  ----view id: null
0903 09:18:09 [Debug] :  ----view id: null
0903 09:18:09 [Debug] :  ----view id: null
0903 09:18:09 [Debug] :  ----view id: null
0903 09:18:09 [Debug] :  ----view id: null
0903 09:18:09 [Debug] :  ----view id: null
0903 09:18:09 [Debug] :  ----view id: null
0903 09:18:09 [Debug] :  ----view id: null
0903 09:18:09 [Debug] :  App was previously registered. Checking...
0903 09:18:09 [Debug] :  [Sending] ==> HTTP /api/webhook/b5224be521599eb9f28f7feb6f884bd440856e10744ca96e83196b0af8304223
0903 09:18:09 [Debug] :  Views count changed (null->12). Creating new tabs controller.
0903 09:18:10 [Error] :  Invalid argument(s): 0.0
0903 09:18:10 [Error] :  NoSuchMethodError: The getter 'height' was called on null.
Receiver: null
Tried calling: height
0903 09:18:10 [Error] :  NoSuchMethodError: The getter 'width' was called on null.
Receiver: null
Tried calling: width
0903 09:18:10 [Error] :  NoSuchMethodError: The getter 'width' was called on null.
Receiver: null
Tried calling: width
0903 09:18:10 [Error] :  NoSuchMethodError: The getter 'width' was called on null.
Receiver: null
Tried calling: width
0903 09:18:10 [Error] :  NoSuchMethodError: The getter 'height' was called on null.
Receiver: null
Tried calling: height
0903 09:18:10 [Error] :  NoSuchMethodError: The getter 'width' was called on null.
Receiver: null
Tried calling: width
0903 09:18:10 [Error] :  NoSuchMethodError: The getter 'height' was called on null.
Receiver: null
Tried calling: height
0903 09:18:10 [Error] :  NoSuchMethodError: The getter 'height' was called on null.
Receiver: null
Tried calling: height
0903 09:18:10 [Error] :  NoSuchMethodError: The getter 'scrollOffsetCorrection' was called on null.
Receiver: null
Tried calling: scrollOffsetCorrection
0903 09:18:10 [Error] :  NoSuchMethodError: The getter 'scrollOffsetCorrection' was called on null.
Receiver: null
Tried calling: scrollOffsetCorrection
0903 09:18:10 [Error] :  NoSuchMethodError: The getter 'visible' was called on null.
Receiver: null
Tried calling: visible
0903 09:18:10 [Error] :  NoSuchMethodError: The method '>' was called on null.
Receiver: null
Tried calling: >()
0903 09:18:10 [Debug] :  [Received] <== HTTP 200
0903 09:18:10 [Debug] :  App registration works fine
0903 09:18:11 [Error] :  NoSuchMethodError: The method '<' was called on null.
Receiver: null
Tried calling: <()

**Comment by estevez-dev** [comment]
It would be very useful to see a config for that view.

**Comment by marcelwestrahome** [comment]
views:
  - cards:
      - entities:
          - entity: light.kitchen
          - entity: light.living
          - entity: light.table
          - entity: light.porch
        title: Downstairs Lights
        type: entities
      - entities:
          - entity: cover.one_door
          - entity: cover.car_port
          - entity: camera.front_door
          - entity: sensor.ring_front_door_last_motion
        show_header_toggle: false
        title: Gate
        type: entities
      - camera_image: camera.xxx
        camera_view: live
        entities: []
        title: voorkant
        type: picture-glance
      - columns: 3
        entities:
          - group.xxx
          - group.xxx
          - group.xxx
        show_icon: true
        title: At Home
        type: glance
      - columns: -1
        entities:
          - entity: sensor.netatmo_outside_temperature
            name: outside
          - entity: sensor.netatmo_rain_gauge_sum_rain_1
            name: rain 1h
          - entity: sensor.netatmo_windy_angle
            name: wind angle
          - entity: sensor.netatmo_windy_strength
            name: wind strength
          - entity: sensor.netatmo_windy_gust_angle
            name: gust angle
          - entity: sensor.netatmo_windy_gust_strength
            name: gust strength
          - entity: sensor.netatmo_rain_gauge_sum_rain_24
            name: rain 24h
        title: Weather outside
        type: glance
      - entity: media_player.sonos_living
        type: media-control
      - entities:
          - entity: binary_sensor.alarm_on
          - entity: binary_sensor.alarm_alarm
        show_icon: false
        show_name: true
        title: Alarm
        type: glance
      - entities:
          - entity: sensor.netatmo_indoor_temperature
            name: table
          - entity: sensor.netatmo_x_temperature
            name: living
          - entity: sensor.netatmo_x_co2
            name: living CO2
          - entity: sensor.netatmo_x_humidity
            name: living hum
          - entity: sensor.netatmo_indoor_noise
            name: table noise
          - entity: sensor.netatmo_indoor_pressure
            name: pressure
          - entity: sensor.netatmo_indoor_co2
            name: table CO2
          - entity: sensor.netatmo_indoor_humidity
            name: table hum
        title: Climate
        type: glance
      - entities:
          - entity: sensor.ring_front_door_battery
        show_header_toggle: false
        title: Monitor
        type: entities
      - entities:
          - entity: sensor.wasmachine_remaining_program_time
          - entity: sensor.wasmachine_program_progress
          - entity: sensor.dryer_remaining_program_time
          - entity: sensor.dryer_program_progress
          - entity: sensor.oven_program_progress
          - entity: sensor.oven_remaining_program_time
        type: glance
      - entities:
          - entity: input_boolean.covers
          - entity: input_boolean.holiday
        show_header_toggle: false
        type: entities
    icon: 'mdi:home-assistant'
    title: bg
