### ISSUE TITLE
App won't login

### ISSUE THREAD

**Issue by dwvaughn** [estevez-dev/ha_client#447]
I try to login to HA and have Nabu Vasa setup and everything but get an error when trying to use the app. "connection refused"

**Comment by dwvaughn** [comment]
Hello,

1) 8123
2) Yes
3) OAuth
4) 0913 08:21:56 [Debug] :  AppLifecycleState.inactive
0913 08:21:56 [Debug] :  AppLifecycleState.resumed
0913 08:21:56 [Debug] :  AppLifecycleState.inactive
0913 08:21:56 [Error] :  Loading settings...
0913 08:21:56 [Error] :  Long-lived token read successful
0913 08:21:56 [Debug] :  Launching OAuth
0913 08:21:56 [Debug] :  AppLifecycleState.resumed
0913 08:21:58 [Debug] :  AppLifecycleState.inactive
0913 08:21:59 [Debug] :  AppLifecycleState.paused
0913 08:22:01 [Debug] :  AppLifecycleState.inactive
0913 08:22:01 [Debug] :  AppLifecycleState.resumed

That was it. I so have a screenahot of the error I get, not sure how to post that.

**Comment by estevez-dev** [comment]
If you are using Remote UI, try to change port number in HA Client to 443. Let me know if it'll help.

**Comment by dwvaughn** [comment]
This changes the error from ERR_SSL_PROTOCOL_ERROR to ERR_CONNECTION_REFUSED

**Comment by estevez-dev** [comment]
Ok. So you are using Remote UI url in application settings? The one that in `.nabu.casa` domain. Right?

**Comment by dwvaughn** [comment]
That did it.  I'm in now but now it seems to be having trouble getting my lovelace config.  I can access it via the WebUi no problem though.

**Comment by estevez-dev** [comment]
Disable "Use Lovelace UI" in connection settings. Will it show your UI from web version?

**Comment by dwvaughn** [comment]
Yes it comes up fine now.
