### ISSUE TITLE
First look feedback

### ISSUE THREAD

**Issue by IanAdd** [estevez-dev/ha_client#456]
So, 
Some mdi icons are not showing up. I use them to title each view.
Google calendar not delivering appointments
Darksky weather card not showing.
Person icon not showing in badges 
History graph cards not there

I have chrome save the web interface as an app icon currently. This works perfectly and i can also develop whilst on my phone.
Not sure what this app is going to deliver that beats it.

**Comment by estevez-dev** [comment]
Thanks for feedback. If you want any issue to be fixed, feel free to report it as a separate bug report.

**Comment by Klagio** [comment]
> So,
> Some mdi icons are not showing up. I use them to title each view.
> Google calendar not delivering appointments
> Darksky weather card not showing.
> Person icon not showing in badges
> History graph cards not there
> 
> I have chrome save the web interface as an app icon currently. This works perfectly and i can also develop whilst on my phone.
> Not sure what this app is going to deliver that beats it.

Way faster then the browser app, moving between tabs its a swipe, fast and easy, good luck swiping with the browser app.
Plus some nice features, like color pick and othewrs
