### ISSUE TITLE
Accessibility improvement

### ISSUE THREAD

**Issue by estevez-dev** [estevez-dev/ha_client#466]
**Is your feature request related to a problem? Please describe.**
Reported by user:

> The only problem that I am having so far is some of your elements don't seem to be labeled. For people who are blind or have a visual impairment, Android has a screen reader built in called TalkBack. This will read all elements on the screen. To find it, go into settings, accessibility, and you can turn it on from there. The only thing that I am noticing so far is some of your buttons are unlabeled. If The few things could be fixed, this app would be 100% accessible.

**Comment by jage9** [comment]
Thanks for marking this as a milestone. In general terms, if you have icons that are unlabeled, setting the ContentDescription element will fix them. If you need further guidance, just ask.

**Comment by estevez-dev** [comment]
HA Client was discontinued
