### ISSUE TITLE
Extended notifications with actions

### ISSUE THREAD

**Issue by CrallH** [estevez-dev/ha_client#471]
**Is your feature request related to a problem? Please describe.**
When sending messages to the phone the possibility to add images, stream url and so on would be great!

**Describe the solution you'd like**
Well to be honest, i want the "same" notification features that Ariela has. 

**Additional context**
title
message
data:
  url
  actions
  color
  message_type
  tag
  dismiss
  image
  icon
  force_image
  stream_source

**Comment by polarbearshirt** [comment]
Being able to add an image or url to the notification would be great!

**Comment by InToSSH** [comment]
Yes I would also love to have Actionable notifications, the way they work on iOS, so I could send a notification with camera snapshot and respond to that (sounding an alarm, etc..), I am quite jealous there is no functionality like that for Android.
