### ISSUE TITLE
Entity-filter

### ISSUE THREAD

**Issue by jp181278** [estevez-dev/ha_client#472]
I have configured an entity Filter that shows if one or more member of the family is at home but noting is shown in the app, instead the webview shows name and picture
![Screenshot_20190927_002128_com keyboardcrumbs haclient](https://user-images.githubusercontent.com/54304648/65728975-f1665600-e0bc-11e9-805b-b60222297790.jpg)
![Screenshot_20190927_002227](https://user-images.githubusercontent.com/54304648/65728984-faefbe00-e0bc-11e9-8122-175193f9ca2a.jpg)
Also the picture in the glace card doesn't work

**Comment by estevez-dev** [comment]
Could you please post here a config for this card? Thanks

**Comment by jp181278** [comment]
# PERSONE
  - type: entity-filter
    entities:
      - device_tracker.jeanpaul
      - type: divider
      - device_tracker.micol
    state_filter:
      - home 
    card:
      type: glance
      title: Persone a Casa


and the known_device is as follow:
jeanpaul:
  hide_if_away: false
  icon:
  mac: _____________________
  name: jeanpaul
  picture: /local/Jeanpaul.jpg
  track: true

micol:
  hide_if_away: false
  icon:
  mac: ______________________
  name: micol
  picture: /local/Micol.jpg
  track: true
