### ISSUE TITLE
24hour format for history graph

### ISSUE THREAD

**Issue by jgmvdmeer** [estevez-dev/ha_client#476]
I prefer 24hour time forrmatting (instead of AM/PM). My android devices (tablet/phone) each display the 24hour format for other applications (e.g. in the browser window for homeassitant). 
When you click an entity icon a history graph is displayed. In the HA webpage this graph has 24hour formatted timeline, for the HA-client it shows the 12hour AM/PM format.

**Comment by estevez-dev** [comment]
HA Client was discontinued
