### ISSUE TITLE
No access

### ISSUE THREAD

**Issue by nnc6** [estevez-dev/ha_client#483]
Hello it's some time I got problems to be able to access ha's page. Seems hassio is not answering or something like that. Even with Alexa I'm not able to send commands to devices, she sais the device is not answering. I attach the log here, can anybody help me please? 

`1028 23:15:52 [Error] :  Bad state: Future already completed
1028 23:15:52 [Error] :  #0      _Completer.completeError (dart:async/future_impl.dart:21)
#1      ConnectionManager._doConnect.<anonymous closure>.<anonymous closure> (package:hass_client/managers/connection_manager.class.dart:103)
#2      _rootRunUnary (dart:async/zone.dart:1132)
#3      _CustomZone.runUnary (dart:async/zone.dart:1029)
#4      _FutureListener.handleValue (dart:async/future_impl.dart:137)
#5      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678)
#6      Future._propagateToListeners (dart:async/future_impl.dart:707)
#7      Future._completeWithValue (dart:async/future_impl.dart:522)
#8      Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:552)
#9      _rootRun (dart:async/zone.dart:1124)
#10     _CustomZone.run (dart:async/zone.dart:1021)
#11     _CustomZone.runGuarded (dart:async/zone.dart:923)
#12     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963)
#13     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#14     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)

1028 23:15:52 [Warning] :  Previous connection attempt pending...
1028 23:15:52 [Warning] :  Previous connection attempt pending...
1028 23:15:52 [Warning] :  Previous connection attempt pending...
1028 23:15:52 [Warning] :  Previous connection attempt pending...
1028 23:15:52 [Warning] :  Previous connection attempt pending...
1028 23:15:52 [Warning] :  Previous connection attempt pending...
1028 23:15:52 [Warning] :  Previous connection attempt pending...
1028 23:16:07 [Debug] :  [Sending] ==> {"type":"get_states","id":8}
1028 23:16:07 [Debug] :  [Sending] ==> {"type":"lovelace/config","id":9}
1028 23:16:07 [Debug] :  [Sending] ==> {"type":"get_config","id":10}
1028 23:16:07 [Debug] :  [Sending] ==> {"type":"get_services","id":11}
1028 23:16:07 [Debug] :  [Sending] ==> {"type":"auth/current_user","id":12}
1028 23:16:07 [Debug] :  [Sending] ==> {"type":"get_panels","id":13}
1028 23:16:07 [Debug] :  [Sending] ==> {"type":"subscribe_events","id":14,"event_type":"state_changed"}
1028 23:16:07 [Warning] :  Can't get services: Instance of 'HAError'
1028 23:16:07 [Warning] :  Can't get user info: Instance of 'HAError'
1028 23:16:07 [Debug] :  AppLifecycleState.inactive
1028 23:16:07 [Debug] :  AppLifecycleState.paused
1028 23:16:24 [Debug] :  AppLifecycleState.inactive
1028 23:16:24 [Debug] :  AppLifecycleState.resumed
1028 23:16:24 [Warning] :  Previous connection attempt pending...
1028 23:16:39 [Debug] :  Settings changed. Saving...
1028 23:16:39 [Debug] :  Settings change event: reconnect=true
1028 23:16:39 [Error] :  Loading settings...
1028 23:16:39 [Error] :  Long-lived token read successful
1028 23:16:39 [Warning] :  Previous connection attempt pending...
1028 23:16:39 [Error] :  Bad state: Future already completed
1028 23:16:39 [Error] :  #0      _Completer.completeError (dart:async/future_impl.dart:21)
#1      ConnectionManager._doConnect.<anonymous closure>.<anonymous closure> (package:hass_client/managers/connection_manager.class.dart:103)
#2      _rootRunUnary (dart:async/zone.dart:1132)
#3      _CustomZone.runUnary (dart:async/zone.dart:1029)
#4      _FutureListener.handleValue (dart:async/future_impl.dart:137)
#5      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678)
#6      Future._propagateToListeners (dart:async/future_impl.dart:707)
#7      Future._completeWithValue (dart:async/future_impl.dart:522)
#8      Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:552)
#9      _rootRun (dart:async/zone.dart:1124)
#10     _CustomZone.run (dart:async/zone.dart:1021)
#11     _CustomZone.runGuarded (dart:async/zone.dart:923)
#12     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963)
#13     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#14     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)

1028 23:16:39 [Warning] :  Previous connection attempt pending...
1028 23:16:39 [Warning] :  Previous connection attempt pending...
1028 23:16:39 [Warning] :  Previous connection attempt pending...
1028 23:16:39 [Warning] :  Previous connection attempt pending...
1028 23:16:39 [Warning] :  Previous connection attempt pending...
1028 23:16:39 [Warning] :  Previous connection attempt pending...
1028 23:16:54 [Error] :  Bad state: Future already completed
1028 23:16:54 [Error] :  #0      _Completer.completeError (dart:async/future_impl.dart:21)
#1      ConnectionManager._doConnect.<anonymous closure>.<anonymous closure> (package:hass_client/managers/connection_manager.class.dart:103)
#2      _rootRunUnary (dart:async/zone.dart:1132)
#3      _CustomZone.runUnary (dart:async/zone.dart:1029)
#4      _FutureListener.handleValue (dart:async/future_impl.dart:137)
#5      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678)
#6      Future._propagateToListeners (dart:async/future_impl.dart:707)
#7      Future._completeWithValue (dart:async/future_impl.dart:522)
#8      Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:552)
#9      _rootRun (dart:async/zone.dart:1124)
#10     _CustomZone.run (dart:async/zone.dart:1021)
#11     _CustomZone.runGuarded (dart:async/zone.dart:923)
#12     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963)
#13     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#14     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)

1028 23:16:54 [Warning] :  Previous data fetch is not completed yet
1028 23:16:54 [Debug] :  [Sending] ==> {"type":"get_states","id":15}
1028 23:16:54 [Debug] :  [Sending] ==> {"type":"get_config","id":16}
1028 23:16:54 [Debug] :  [Sending] ==> {"type":"get_services","id":17}
1028 23:16:54 [Debug] :  [Sending] ==> {"type":"auth/current_user","id":18}
1028 23:16:54 [Debug] :  [Sending] ==> {"type":"get_panels","id":19}
1028 23:16:54 [Debug] :  [Sending] ==> {"type":"subscribe_events","id":20,"event_type":"state_changed"}
1028 23:16:54 [Warning] :  Can't get services: Instance of 'HAError'
1028 23:16:54 [Warning] :  Can't get user info: Instance of 'HAError'
1028 23:17:11 [Debug] :  AppLifecycleState.inactive
1028 23:17:11 [Debug] :  AppLifecycleState.paused
1028 23:18:00 [Error] :  Socket stream Error: WebSocketChannelException: WebSocketChannelException: SocketException: OS Error: Software caused connection abort, errno = 103, address = zanna87.duckdns.org, port = 59390
1028 23:18:47 [Debug] :  AppLifecycleState.inactive
1028 23:18:47 [Debug] :  AppLifecycleState.resumed
1028 23:18:47 [Debug] :  Socket connecting...
1028 23:19:02 [Error] :  Bad state: Future already completed
1028 23:19:02 [Error] :  #0      _Completer.completeError (dart:async/future_impl.dart:21)
#1      ConnectionManager._doConnect.<anonymous closure>.<anonymous closure> (package:hass_client/managers/connection_manager.class.dart:103)
#2      _rootRunUnary (dart:async/zone.dart:1132)
#3      _CustomZone.runUnary (dart:async/zone.dart:1029)
#4      _FutureListener.handleValue (dart:async/future_impl.dart:137)
#5      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678)
#6      Future._propagateToListeners (dart:async/future_impl.dart:707)
#7      Future._completeWithValue (dart:async/future_impl.dart:522)
#8      Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:552)
#9      _rootRun (dart:async/zone.dart:1124)
#10     _CustomZone.run (dart:async/zone.dart:1021)
#11     _CustomZone.runGuarded (dart:async/zone.dart:923)
#12     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963)
#13     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#14     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)

1028 23:19:02 [Warning] :  Previous connection attempt pending...
1028 23:19:02 [Warning] :  Previous connection attempt pending...
1028 23:19:02 [Warning] :  Previous connection attempt pending...
1028 23:19:02 [Warning] :  Previous connection attempt pending...
1028 23:19:02 [Warning] :  Previous connection attempt pending...
1028 23:19:02 [Warning] :  Previous connection attempt pending...
1028 23:19:08 [Debug] :  AppLifecycleState.inactive
1028 23:19:08 [Debug] :  AppLifecycleState.paused
1028 23:19:10 [Debug] :  AppLifecycleState.inactive
1028 23:19:10 [Debug] :  AppLifecycleState.resumed
1028 23:19:10 [Warning] :  Previous connection attempt pending...
1028 23:19:16 [Debug] :  AppLifecycleState.inactive
1028 23:19:16 [Debug] :  AppLifecycleState.paused
1028 23:19:17 [Debug] :  [Sending] ==> {"type":"get_states","id":21}
1028 23:19:17 [Debug] :  [Sending] ==> {"type":"get_config","id":22}
1028 23:19:17 [Debug] :  [Sending] ==> {"type":"get_services","id":23}
1028 23:19:17 [Debug] :  [Sending] ==> {"type":"auth/current_user","id":24}
1028 23:19:17 [Debug] :  [Sending] ==> {"type":"get_panels","id":25}
1028 23:19:17 [Debug] :  [Sending] ==> {"type":"subscribe_events","id":26,"event_type":"state_changed"}
1028 23:19:17 [Warning] :  Can't get services: Instance of 'HAError'
1028 23:19:17 [Warning] :  Can't get user info: Instance of 'HAError'
1028 23:19:25 [Error] :  Bad state: Future already completed
1028 23:19:25 [Error] :  #0      _Completer.completeError (dart:async/future_impl.dart:21)
#1      ConnectionManager._doConnect.<anonymous closure>.<anonymous closure> (package:hass_client/managers/connection_manager.class.dart:103)
#2      _rootRunUnary (dart:async/zone.dart:1132)
#3      _CustomZone.runUnary (dart:async/zone.dart:1029)
#4      _FutureListener.handleValue (dart:async/future_impl.dart:137)
#5      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678)
#6      Future._propagateToListeners (dart:async/future_impl.dart:707)
#7      Future._completeWithValue (dart:async/future_impl.dart:522)
#8      Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:552)
#9      _rootRun (dart:async/zone.dart:1124)
#10     _CustomZone.run (dart:async/zone.dart:1021)
#11     _CustomZone.runGuarded (dart:async/zone.dart:923)
#12     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963)
#13     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#14     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)

1028 23:19:25 [Warning] :  Previous connection attempt pending...
1028 23:19:25 [Warning] :  Previous connection attempt pending...
1028 23:19:25 [Warning] :  Previous connection attempt pending...
1028 23:19:25 [Warning] :  Previous connection attempt pending...
1028 23:19:25 [Warning] :  Previous connection attempt pending...
1028 23:19:25 [Warning] :  Previous connection attempt pending...
1028 23:19:28 [Debug] :  AppLifecycleState.inactive
1028 23:19:28 [Debug] :  AppLifecycleState.resumed
1028 23:19:28 [Warning] :  Previous connection attempt pending...
1028 23:19:37 [Debug] :  AppLifecycleState.inactive
1028 23:19:37 [Debug] :  AppLifecycleState.paused
1028 23:19:39 [Debug] :  AppLifecycleState.inactive
1028 23:19:39 [Debug] :  AppLifecycleState.resumed
1028 23:19:39 [Warning] :  Previous connection attempt pending...
1028 23:19:40 [Debug] :  [Sending] ==> {"type":"get_states","id":27}
1028 23:19:40 [Debug] :  [Sending] ==> {"type":"get_config","id":28}
1028 23:19:40 [Debug] :  [Sending] ==> {"type":"get_services","id":29}
1028 23:19:40 [Debug] :  [Sending] ==> {"type":"auth/current_user","id":30}
1028 23:19:40 [Debug] :  [Sending] ==> {"type":"get_panels","id":31}
1028 23:19:40 [Debug] :  [Sending] ==> {"type":"subscribe_events","id":32,"event_type":"state_changed"}
1028 23:19:40 [Warning] :  Can't get services: Instance of 'HAError'
1028 23:19:40 [Warning] :  Can't get user info: Instance of 'HAError'
`

**Comment by estevez-dev** [comment]
HA Client is an unofficial Android app for Home Assistant. The issues with Home Assistant itself should be report to Home Assistant repository: https://github.com/home-assistant/home-assistant

**Comment by nnc6** [comment]
Ok, sorry!
