### ISSUE TITLE
Older Android versions support (Android 4.3?)

### ISSUE THREAD

**Issue by backcountrymountains** [estevez-dev/ha_client#487]
I've got a Wink Relay that runs Android 4.3 that I'd like to use with the app, but I can't get it to install.

Is there a way to compile the app for Android 4.3?

Thanks.

**Comment by estevez-dev** [comment]
Well, here is a good start: https://flutter.dev/docs/get-started/install
You need to setup Android Studio with Flutter tool and SDK, create an AVD (virtual device) with Android 4.3 and try to run the app on it.
Actually, I'm curious of this as well, but I have no possibility to run virtual device currently. And I don't have any real device with Android 4.3.
Also if there will be more requests for this, I'll look on it closely.

**Comment by backcountrymountains** [comment]
Thanks!

**Comment by estevez-dev** [comment]
Closing as this would not be done for HA Client
