### ISSUE TITLE
Location tracking always sends last known location

### ISSUE THREAD

**Issue by avdeevsv91** [estevez-dev/ha_client#490]
**HA Client version:** 0.7.0

**Home Assistant version:** 0.100.3

**Device name:** Xiaomi RedMi 2

**Android version:** 5.1.1

**Connection type:** Own domain

**Login type:** HA Login

**Description**
GPS will not work. Geolocation rights for the app are allowed. The coordinates are calculated on the basis of cellular networks, a large error of accuracy. In the screenshot the coordinates are 1 km away from me. Other apps work well with GPS (a system notification appears to search for satellites).

**Screenshots**

![rights](https://i.ibb.co/6NY3Gm7/Screenshot-2019-10-30-11-58-53-477-com-miui-securitycenter.png)
![screenshot](https://i.ibb.co/59dsJfL/screenshot.jpg)
![map](https://i.ibb.co/1J8p1ch/map.jpg)

**Logs**
```
1030 11:36:31 [Debug] : AppLifecycleState.inactive
1030 11:36:31 [Debug] : AppLifecycleState.resumed
1030 11:36:31 [Debug] : AppLifecycleState.inactive
1030 11:36:31 [Error] : Loading settings...
1030 11:36:31 [Error] : Long-lived token read successful
1030 11:36:31 [Debug] : Socket connecting...
1030 11:36:31 [Debug] : AppLifecycleState.resumed
1030 11:36:31 [Warning] : Previous connection attempt pending...
1030 11:36:32 [Debug] : [Received] <== {type: auth_required, ha_version: 0.100.3}
1030 11:36:32 [Debug] : Long-lived token exist
1030 11:36:32 [Debug] : [Sending] ==> auth request
1030 11:36:32 [Debug] : [Sending] ==> type=auth
1030 11:36:32 [Debug] : [Received] <== {type: auth_ok, ha_version: 0.100.3}
1030 11:36:32 [Debug] : Authentication complete
1030 11:36:32 [Debug] : [Sending] ==> {"type":"get_states","id":1}
1030 11:36:32 [Debug] : [Sending] ==> {"type":"lovelace/config","id":2}
1030 11:36:32 [Debug] : [Sending] ==> {"type":"get_config","id":3}
1030 11:36:32 [Debug] : [Sending] ==> {"type":"get_services","id":4}
1030 11:36:32 [Debug] : [Sending] ==> {"type":"auth/current_user","id":5}
1030 11:36:32 [Debug] : [Sending] ==> {"type":"get_panels","id":6}
1030 11:36:32 [Debug] : [Sending] ==> {"type":"subscribe_events","id":7,"event_type":"state_changed"}
1030 11:36:32 [Warning] : Previous data fetch is not completed yet
1030 11:36:32 [Debug] : Scheduling location update for every 5 minutes...
1030 11:36:32 [Debug] : Parsing 48 Home Assistant entities
1030 11:36:32 [Debug] : Got 17 services
1030 11:36:32 [Debug] : Media extractor: null
1030 11:36:32 [Debug] : Creating Lovelace UI
1030 11:36:32 [Debug] : —Title: Моя квартира
1030 11:36:32 [Debug] : —Views count: 6
1030 11:36:32 [Debug] : —--view id: null
1030 11:36:32 [Debug] : —--view id: null
1030 11:36:32 [Debug] : —--view id: null
1030 11:36:32 [Debug] : —--view id: null
1030 11:36:32 [Debug] : —--view id: null
1030 11:36:32 [Debug] : —--view id: null
1030 11:36:32 [Debug] : App was previously registered. Checking...
1030 11:36:32 [Debug] : [Sending] ==> HTTP /api/webhook/kbkbjkjn
1030 11:36:32 [Debug] : Views count changed (null->6). Creating new tabs controller.
1030 11:36:33 [Debug] : [Received] <== HTTP 200
1030 11:36:33 [Debug] : App registration works fine
1030 11:37:21 [Debug] : Stopping location tracking...
1030 11:37:21 [Debug] : Canceling previous schedule if any...
1030 11:37:22 [Debug] : [Location] Getting device location...
1030 11:37:22 [Debug] : [Location] Got location: 53.2072272 39.4356349. Sending home...
1030 11:37:23 [Debug] : [Location] ...done.
1030 11:37:23 [Debug] : Starting location tracking
1030 11:37:23 [Debug] : Scheduling location update for every 5 minutes...
```

**Comment by avdeevsv91** [comment]
It still doesn't work. The app does not initiate a gps satellite search. The coordinates are determined by the ones that were last in any other application using GPS.

**Comment by estevez-dev** [comment]
Please make sure you are using the last version of HA Client.
Then fo to "Integration" settings, disable location tracking and enable it back again. Then fo to "Log", copy it and post here. Thanks.

**Comment by avdeevsv91** [comment]
During the determination of coordinates, a system notification should appear that GPS is being used. It doesn't work here, other apps are fine. As I understand it, HA Clien does not search for coordinates itself, but takes from the system those that were found last with the help of another application. But this may not be relevant.

> 1102 20:03:41 [Debug] : AppLifecycleState.inactive
1102 20:03:41 [Debug] : AppLifecycleState.resumed
1102 20:03:41 [Debug] : AppLifecycleState.inactive
1102 20:03:41 [Error] : Loading settings...
1102 20:03:41 [Error] : Long-lived token read successful
1102 20:03:41 [Debug] : Socket connecting...
1102 20:03:41 [Debug] : AppLifecycleState.resumed
1102 20:03:41 [Warning] : Previous connection attempt pending...
1102 20:03:42 [Debug] : [Received] <== {type: auth_required, ha_version: 0.100.3}
1102 20:03:42 [Debug] : Long-lived token exist
1102 20:03:42 [Debug] : [Sending] ==> auth request
1102 20:03:42 [Debug] : [Sending] ==> type=auth
1102 20:03:43 [Debug] : [Received] <== {type: auth_ok, ha_version: 0.100.3}
1102 20:03:43 [Debug] : Authentication complete
1102 20:03:43 [Debug] : [Sending] ==> {"type":"get_states","id":1}
1102 20:03:43 [Debug] : [Sending] ==> {"type":"lovelace/config","id":2}
1102 20:03:43 [Debug] : [Sending] ==> {"type":"get_config","id":3}
1102 20:03:43 [Debug] : [Sending] ==> {"type":"get_services","id":4}
1102 20:03:43 [Debug] : [Sending] ==> {"type":"auth/current_user","id":5}
1102 20:03:43 [Debug] : [Sending] ==> {"type":"get_panels","id":6}
1102 20:03:43 [Debug] : [Sending] ==> {"type":"subscribe_events","id":7,"event_type":"state_changed"}
1102 20:03:43 [Warning] : Previous data fetch is not completed yet
1102 20:03:43 [Debug] : Scheduling location update for every 5 minutes...
1102 20:03:43 [Debug] : Parsing 52 Home Assistant entities
1102 20:03:43 [Debug] : Got 18 services
1102 20:03:43 [Debug] : Media extractor: null
1102 20:03:43 [Debug] : Creating Lovelace UI
1102 20:03:43 [Debug] : —Title: Моя квартира
1102 20:03:43 [Debug] : —Views count: 6
1102 20:03:43 [Debug] : —--view id: null
1102 20:03:43 [Debug] : —--view id: null
1102 20:03:43 [Debug] : —--view id: null
1102 20:03:43 [Debug] : —--view id: null
1102 20:03:43 [Debug] : —--view id: null
1102 20:03:43 [Debug] : —--view id: null
1102 20:03:43 [Debug] : App was previously registered. Checking...
1102 20:03:43 [Debug] : [Sending] ==> HTTP /api/webhook/8c5a1c8ad291842a603367f3966784d04d64635a7dbb945a70cc0a12b8c5c190
1102 20:03:43 [Debug] : Views count changed (null->6). Creating new tabs controller.
1102 20:03:44 [Debug] : [Received] <== HTTP 200
1102 20:03:44 [Debug] : App registration works fine
1102 20:03:45 [Debug] : Stopping location tracking...
1102 20:03:45 [Debug] : Canceling previous schedule if any...
1102 20:03:46 [Debug] : [Test location] Started
1102 20:03:46 [Debug] : [Test location] Forcing Android location manager...
1102 20:03:46 [Debug] : [Test location] Getting battery level...
1102 20:03:46 [Debug] : Starting location tracking
1102 20:03:46 [Debug] : Scheduling location update for every 5 minutes...
1102 20:03:46 [Debug] : [Test location] Getting device location...
1102 20:03:46 [Debug] : [Test location] Got location: 53.21292527 39.44949481 with accuracy of 39.0
1102 20:03:46 [Debug] : [Test location] Sending data home...
1102 20:03:47 [Debug] : [Received] <== event.state_changed: device_tracker.mobile_ha_client
1102 20:03:50 [Debug] : [Received] <== event.state_changed: sensor.home_assistant_v2_db
1102 20:03:50 [Debug] : [Received] <== event.state_changed: sensor.line_reactive_power
1102 20:03:50 [Debug] : [Received] <== event.state_changed: sensor.processor_use
1102 20:03:50 [Debug] : [Received] <== event.state_changed: sensor.line_reactive_power_positive
1102 20:03:50 [Debug] : [Received] <== event.state_changed: sensor.memory_use_percent
1102 20:03:50 [Debug] : [Received] <== event.state_changed: sensor.network_out_eth0
1102 20:03:50 [Debug] : [Received] <== event.state_changed: sensor.line_active_power
1102 20:03:50 [Debug] : [Received] <== event.state_changed: sensor.line_voltage

In logs coordinates which were found when I used the Navigator. But that was hours ago and my location has since changed.

**Comment by cmulk** [comment]
Just wanted to confirm that I'm consistently seeing the same behavior on 2 android devices.
Device 1: Moto G6 with Android 9
Device 2: Moto G5 Plus with Android 8

App version 0.7.2

I can tell the updates are going through properly because the reported battery level on the device entity in Home Assistant is accurate. However, just like the logs above, it continues to report old location coordinates, even after switching Location tracking off and on. Currently at over 12 hours with old location still showing. Thanks for your work, just wanted to provide a little more info/confirmation if it helps!

**Comment by banjo1891** [comment]
Same here on Moto G5 plus with Android 8.1.0.

**Comment by estevez-dev** [comment]
Blocked by BaseflowIT/flutter-geolocator#313

**Comment by hellcry37** [comment]
yah this happens to me also +1

**Comment by estevez-dev** [comment]
I'm now working on foreground service for location updates. It means that location will be always accurate but you will see a notification  saying that HA Client is tracking your location. I think I'll add location accuracy to the notification text to make it more useful.
