### ISSUE TITLE
Lovelace config parsing issue

### ISSUE THREAD

**Issue by andycrap** [estevez-dev/ha_client#491]
I am getting an error when enabling lovelace ui 

type '_lnternaILinkedHashMap(String, 
dynamic ' is not a subtype of type 'String ' Try again 

I can use it without lovelace ui but I get all badges and devices and it looks messy.

Using Samsung note 10+ on android 9

**Comment by estevez-dev** [comment]
Oh this is interesting. Is it possible to see your full Lovelace UI config? It is the only way for me to reproduce this issue. Thanks.

**Comment by andycrap** [comment]
Thanks for getting back to me.  Can you tell me what file you need.  i am running hassio latest version on RP

**Comment by estevez-dev** [comment]
On web UI click three dots menu on upper right:
![screenshot-3o3r1ehs64etrlasv5nw8gdmbxhk0i9g ui nabu casa-2019 11 01-11_27_39](https://user-images.githubusercontent.com/1819786/68015443-d928be80-fc9a-11e9-9fcc-c5f0da99a4ec.png)
Select "Configure UI". Then click the same three dots again and choose "Raw config editor". You will see your Lovelace config in yaml format. That's what I need.

**Comment by andycrap** [comment]
Thanks.  here is the contents.

title: Home
views:
  - path: default_view
    title: Home
    badges:
      - entity: binary_sensor.nicky_s_keys_presence
      - entity: binary_sensor.andy_s_note_10_presence
      - entity: binary_sensor.wendys_keys_presence
      - entity: device_tracker.andy_s_sm_n975f
      - entity: sensor.plex_qnapnas
    cards:
      - entity: weather.home
        type: weather-forecast
      - entities:
          - entity: light.hue
          - entity: light.bedroom_light
        show_header_toggle: false
        title: Bedroom
        type: entities
      - entities:
          - entity: light.lounge_light
          - entity: light.lounge_lamp
          - entity: sensor.lounge_temperature_measurement
          - entity: binary_sensor.lounge_alarm_motion
          - entity: binary_sensor.lounge_motion
        show_header_toggle: false
        title: Living Room
        type: entities
      - entities:
          - entity: light.office_light
          - entity: switch.office_lamp
          - entity: switch.my_computer
          - entity: switch.3d_printer
          - entity: switch.soldering_iron
          - entity: binary_sensor.office_alarm_motion
          - entity: binary_sensor.office_motion
        show_header_toggle: false
        title: Office
        type: entities
      - entities:
          - entity: light.landing_light
          - entity: binary_sensor.front_door_contact
          - entity: sensor.front_door_temperature_measurement
          - entity: sensor.stairs_temperature_measurement
          - entity: binary_sensor.stairs_alarm_motion
          - entity: binary_sensor.stairs_motion
        show_header_toggle: false
        title: Halls
        type: entities
      - entities:
          - entity: light.garden_light
          - entity: sensor.outside_temperature_temperature_measurement
          - entity: sensor.siren_alarm
        show_header_toggle: false
        title: Outside
        type: entities
      - entities:
          - entity: binary_sensor.bathroom_water_sensor_water
          - entity: sensor.bathroom_water_sensor_temperature_measurement
        show_header_toggle: false
        title: Bathroom
        type: entities
      - entities:
          - entity: light.backdoor_light
          - entity: sensor.backdoor_temperature_measurement
          - entity: sensor.kitchen_motion_temperature_measurement
          - entity: sensor.kitchen_water_sensor_temperature_measurement
          - entity: binary_sensor.kitchen_water_sensor_water
          - entity: binary_sensor.backdoor_contact
          - entity: binary_sensor.kitchen_alarm_motion
          - entity: binary_sensor.kitchen_motion_motion
        show_header_toggle: false
        title: Kitchen
        type: entities
      - entities:
          - entity: binary_sensor.spare_room_alarm_motion
        show_header_toggle: false
        title: Spare Room
        type: entities
      - entities:
          - entity: binary_sensor.frontroom_motion
          - entity: binary_sensor.frontroom_alarm_motion
        show_header_toggle: false
        title: Front Room
        type: entities
      - entities:
          - entity: switch.chargers
          - entity: sensor.garage_door_temperature_measurement
          - entity: binary_sensor.garage_door_contact
          - entity: binary_sensor.garage_motion
        show_header_toggle: false
        title: Garage
        type: entities

**Comment by estevez-dev** [comment]
Could you please also copy logs from app right after the error appears and post it here?

**Comment by andycrap** [comment]
i think this is all.

1101 09:50:22 [Error] :  Loading settings...
1101 09:50:22 [Error] :  Long-lived token read successful
1101 09:50:22 [Debug] :  Socket disconnecting...
1101 09:50:22 [Debug] :  Socket connecting...
1101 09:50:23 [Debug] :  [Received] <== {type: auth_required, ha_version: 0.101.1}
1101 09:50:23 [Debug] :  Long-lived token exist
1101 09:50:23 [Debug] :  [Sending] ==> auth request
1101 09:50:23 [Debug] :  [Sending] ==> type=auth
1101 09:50:23 [Debug] :  [Received] <== {type: auth_ok, ha_version: 0.101.1}
1101 09:50:23 [Debug] :  Authentication complete
1101 09:50:23 [Debug] :  [Sending] ==> {"type":"get_states","id":54}
1101 09:50:23 [Debug] :  [Sending] ==> {"type":"lovelace/config","id":55}
1101 09:50:23 [Debug] :  [Sending] ==> {"type":"get_config","id":56}
1101 09:50:23 [Debug] :  [Sending] ==> {"type":"get_services","id":57}
1101 09:50:23 [Debug] :  [Sending] ==> {"type":"auth/current_user","id":58}
1101 09:50:23 [Debug] :  [Sending] ==> {"type":"get_panels","id":59}
1101 09:50:23 [Debug] :  [Sending] ==> {"type":"subscribe_events","id":60,"event_type":"state_changed"}
1101 09:50:23 [Debug] :  Parsing 100 Home Assistant entities
1101 09:50:23 [Debug] :  Got 25 services
1101 09:50:23 [Debug] :  Media extractor: null
1101 09:50:23 [Debug] :  Creating Lovelace UI
1101 09:50:23 [Debug] :  --Title: Home
1101 09:50:23 [Debug] :  --Views count: 1
1101 09:50:23 [Debug] :  ----view id: null

**Comment by andycrap** [comment]
I think it may be an issue with my hassio install as i am getting a lot of sql errors in the log.  i will try a re install this evening and restore snapshot and see if that helps.

**Comment by koying** [comment]
Debugging the same issue and it comes from https://github.com/estevez-dev/ha_client/blob/master/lib/home_assistant.class.dart#L182

"entity" is (now?) a key/value map (e.g. `key: "entity"; value: "sun.sun"`) and not a string.
May be some breaking protocol change? 

I'm running HA 0.102.0.dev20191026

**Comment by koying** [comment]
Probably related to https://github.com/home-assistant/home-assistant-polymer/commit/c9242a507571f9f899c021fbad70154e5b82a24f

**Comment by koying** [comment]
Quick & dirty fix:
```
        if (rawView['badges'] != null && rawView['badges'] is List) {
          rawView['badges'].forEach((entity) {
            String sVal = "";
            if (entity is Map)
              sVal = entity["entity"];
            else
              sVal = entity;
            if (entities.isExist(sVal)) {
              Entity e = entities.get(sVal);
              view.badges.add(e);
            }
          });
        }
```

**Comment by estevez-dev** [comment]
Yep, changes in config structure. Will fix today
