### ISSUE TITLE
Iframe support 

### ISSUE THREAD

**Issue by dpackham** [estevez-dev/ha_client#504]
When the client tries to display an iframe I get an error message that says that I frame are not supported

**Comment by dpackham** [comment]
![Screenshot_20191114-115736](https://user-images.githubusercontent.com/707522/68887301-fb2c3300-06d5-11ea-9437-86cdf129b694.png)

**Comment by dpackham** [comment]
Here's a picture of the error

**Comment by estevez-dev** [comment]
Because it is not supported. But planned. See #211
