### ISSUE TITLE
Location tracking do not work in background 

### ISSUE THREAD

**Issue by mooonsee** [estevez-dev/ha_client#505]
I'm using Android 9 and Huawei P20 Light.
App integration works fine, but even after changing power setting for HA app I still cannot get properly working tracking system. 
App update location only when I turn it on manually, do not work in background.

**Comment by estevez-dev** [comment]
I can work in background but it could send last known location due to #490 
You can be sure it works in background by checking battery level reported to the same device_tracker entity.
