### ISSUE TITLE
Location not working properly

### ISSUE THREAD

**Issue by Cireasa23** [estevez-dev/ha_client#507]
Log attached
1121 07:55:51 [Debug] :  AppLifecycleState.inactive
1121 07:55:51 [Debug] :  AppLifecycleState.resumed
1121 07:55:51 [Debug] :  AppLifecycleState.inactive
1121 07:55:51 [Error] :  Loading settings...
1121 07:55:51 [Error] :  Long-lived token read successful
1121 07:55:51 [Debug] :  Socket connecting...
1121 07:55:52 [Debug] :  AppLifecycleState.resumed
1121 07:55:52 [Warning] :  Previous connection attempt pending...
1121 07:55:52 [Debug] :  [Received] <== {type: auth_required, ha_version: 0.102.0}
1121 07:55:52 [Debug] :  Long-lived token exist
1121 07:55:52 [Debug] :  [Sending] ==> auth request
1121 07:55:52 [Debug] :  [Sending] ==> type=auth
1121 07:55:52 [Debug] :  [Received] <== {type: auth_ok, ha_version: 0.102.0}
1121 07:55:52 [Debug] :  Authentication complete
1121 07:55:52 [Debug] :  [Sending] ==> {"type":"get_states","id":1}
1121 07:55:52 [Debug] :  [Sending] ==> {"type":"lovelace/config","id":2}
1121 07:55:52 [Debug] :  [Sending] ==> {"type":"get_config","id":3}
1121 07:55:52 [Debug] :  [Sending] ==> {"type":"get_services","id":4}
1121 07:55:52 [Debug] :  [Sending] ==> {"type":"auth/current_user","id":5}
1121 07:55:52 [Debug] :  [Sending] ==> {"type":"get_panels","id":6}
1121 07:55:52 [Debug] :  [Sending] ==> {"type":"subscribe_events","id":7,"event_type":"state_changed"}
1121 07:55:52 [Warning] :  Previous data fetch is not completed yet
1121 07:55:52 [Error] :  Failed assertion: boolean expression must not be null
1121 07:55:52 [Error] :  #0      LocationManager.updateDeviceLocation (package:hass_client/managers/location_manager.class.dart:112)
<asynchronous suspension>
#1      _MainPageState._quickLoad.<anonymous closure> (package:hass_client/pages/main.page.dart:125)
#2      _rootRunUnary (dart:async/zone.dart:1132)
#3      _CustomZone.runUnary (dart:async/zone.dart:1029)
#4      _FutureListener.handleValue (dart:async/future_impl.dart:137)
#5      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678)
#6      Future._propagateToListeners (dart:async/future_impl.dart:707)
#7      Future._completeWithValue (dart:async/future_impl.dart:522)
#8      Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:552)
#9      _rootRun (dart:async/zone.dart:1124)
#10     _CustomZone.run (dart:async/zone.dart:1021)
#11     _CustomZone.runGuarded (dart:async/zone.dart:923)
#12     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963)
#13     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#14     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)

1121 07:55:52 [Debug] :  Starting location update for every 5 minutes...
1121 07:55:52 [Debug] :  Scheduling location update task #1 for every 15 minutes in 5 minutes...
1121 07:55:52 [Debug] :  Scheduling location update task #2 for every 15 minutes in 10 minutes...
1121 07:55:52 [Debug] :  Scheduling location update task #3 for every 15 minutes in 15 minutes...
1121 07:55:52 [Debug] :  [Foreground location] Started
1121 07:55:52 [Debug] :  [Foreground location] Getting battery level...
1121 07:55:52 [Debug] :  [Foreground location] Getting device location...
1121 07:55:52 [Debug] :  [Foreground location] Location: 44.5705103 26.0791697. Accuracy: 19.583999633789062. (2019-11-20 23:10:33.740Z)
1121 07:55:52 [Debug] :  [Foreground location] Sending data home...
1121 07:55:52 [Debug] :  Parsing 70 Home Assistant entities
1121 07:55:52 [Debug] :  Got 23 services
1121 07:55:52 [Debug] :  Creating Lovelace UI
1121 07:55:52 [Debug] :  --Title: Super House
1121 07:55:52 [Debug] :  --Views count: 4
1121 07:55:52 [Debug] :  ----view id: null
1121 07:55:52 [Debug] :  ----view id: null
1121 07:55:52 [Debug] :  ----view id: null
1121 07:55:52 [Debug] :  ----view id: null
1121 07:55:52 [Debug] :  App was previously registered. Checking...
1121 07:55:52 [Debug] :  [Sending] ==> HTTP /api/webhook/8a4cd0edbe68dedb2c739ff5d9cc813763c2c8df6b9af6f875f02c90bf1acc7f
1121 07:55:52 [Debug] :  Views count changed (null->4). Creating new tabs controller.
1121 07:55:52 [Debug] :  [Foreground location] Got HTTP 200
1121 07:55:52 [Debug] :  [Received] <== event.state_changed: device_tracker.catalin_s_sne_lx1
1121 07:55:52 [Debug] :  [Received] <== event.state_changed: sensor.mate20_battery
1121 07:55:52 [Debug] :  [Received] <== HTTP 200
1121 07:55:52 [Debug] :  App registration works fine
1121 07:55:56 [Debug] :  [Received] <== event.state_changed: sensor.temperature_1
1121 07:55:56 [Debug] :  [Received] <== event.state_changed: sensor.humidity_1

**Comment by estevez-dev** [comment]
Resolved in 0.7.5
