### ISSUE TITLE
icons inmenu not visible

### ISSUE THREAD

**Issue by Geertseb** [estevez-dev/ha_client#509]
When I use icons in the Lovelace menu they are not visible. And not clickable.

**Comment by estevez-dev** [comment]
Please provide more information.

**Comment by Geertseb** [comment]
I'm sorry I was to quick, When I modified my Lovelace pages the 'reload' option in HA Client gives no effect. Closing the App and restart again did help. So what remains is the refresh of the Lovelace pages when you update of change something on another system .

**Comment by estevez-dev** [comment]
Sorry it is still not clear to me what is the issue.
You are changing UI in web version, then hit "Reload" in the app and no changes loaded? Are we talking about views (tabs) or panels (menu items)? May be some screenshot would be very useful.
