### ISSUE TITLE
apk missing on release page

### ISSUE THREAD

**Issue by rradar** [estevez-dev/ha_client#516]
**Description:**
-
The apk is missing on the release page. Only source code is available at the moment while desperately waiting for the app get's released in F-Droid #275 

**Screenshot**
![image](https://user-images.githubusercontent.com/34582688/70652263-3cb6ec00-1c4a-11ea-841a-9c1948dab744.png)

**Comment by estevez-dev** [comment]
The up is built by CI tool in a bundle (.aab). No .apk available for now. I'll add to to F-Droid.
