### ISSUE TITLE
Device tracker reports negative altitude and gives an error in log

### ISSUE THREAD

**Issue by biochemguy** [estevez-dev/ha_client#517]
**HA Client version: 1.1.2** [Main menu -> About HA Client]

**Home Assistant version: 0.102.3**

**Device name: Samsung S8**

**Android version: 9**

**Error in the HA Log stating that we should have a minimum value for altitude (Tracking). Somehow my phone reports a negative value. Maybe set a minimum limit of 0 in the app so it does not throw an error?

` 2019-12-12 19:45:19 ERROR (MainThread) [homeassistant.components.mobile_app.webhook] Received invalid webhook payload: value must be at least 0 for dictionary value @ data['altitude']. Got -2`

Thanks for the great work!
**

**Screenshots**
[Replace with screenshots]

**Comment by estevez-dev** [comment]
That's strange =) Will look into it. Thanks for report.

**Comment by stainlessray** [comment]
I have the same error on the same version of Hass. I wonder if anyone running the latest version is having a problem.
Android 10 
Pixel 4 XL
