### ISSUE TITLE
Increase or decrease temperature in climate.netatmo not working 

### ISSUE THREAD

**Issue by Klagio** [estevez-dev/ha_client#522]
**HA Client version:** [Main menu -> About HA Client]

**Home Assistant version:**
105.4
**Device name:**

**Android version:**
10
**Description**
[Replace with description]

**Screenshots**
[Replace with screenshots]

**Comment by estevez-dev** [comment]
Tried on demo thermostats. It works but not always. Will check, thanks

**Comment by estevez-dev** [comment]
Will be in 0.8.0
