### ISSUE TITLE
Change device name for integration

### ISSUE THREAD

**Issue by bschatzow** [estevez-dev/ha_client#523]
No way to add two identical devices. I have two sm-T813. If I integrate bother I get a duplicate device created in HA.  Need to be able to change the device name before integration.

**Comment by LiJu09** [comment]
Are you login with same account?

**Comment by estevez-dev** [comment]
You can avoid this issue by logging in with another user. But I agree, we need this option.

**Comment by bschatzow** [comment]
I'm not sure I understand your answer. I have two tablets that are the same and a phone that is different.  I log in as the same user as I am the same user.  You may want to check out how Areila handles it.  I used it until HA recommended your app do to the changes in HA.

**Comment by estevez-dev** [comment]
I see, you don't need to use different users. I'll add a possibility to change device name.

**Comment by estevez-dev** [comment]
Will be presented in 1.0.0.
You'll need to remove Mobile App integration from Home Assistant and restart server. Then just open HA Client and it will ask you to create an integration again with ability to set device name.
