### ISSUE TITLE
Log in with long lived token does not work

### ISSUE THREAD

**Issue by zolstarym** [estevez-dev/ha_client#534]
**HA Client version:** [Main menu -> About HA Client]
.8.3
**Home Assistant version:**
.108.1
**Device name:**
galaxy s9+
**Android version:**
9
**Description**
[Replace with description]
First I enabled mobile_app: as per the instructions at https://ha-client.app/docs#authentication
When clicking the blue login with home assistant button I got a white screen with nothing on it, so I tried long lived token instead generating and inputting the token, which also did not work. It would just say disconnected at the bottom and hitting reconnect would do nothing. Going back into the connection settings, right below the authentications settings line is a gray box that is really large. I can scroll on this page , but cannot scroll to the bottom of it as the box is too long and I don't have a scroll bar.

![Screenshot_20200411-153621](https://user-images.githubusercontent.com/1832149/79055422-3b9ec700-7c0a-11ea-9408-d2a7f5cfb3f8.jpg)

![Screenshot_20200411-152447](https://user-images.githubusercontent.com/1832149/79055271-faf27e00-7c08-11ea-8309-cf66120112f8.jpg)

0411 15:13:29 [Error] :  Socket stream Error: WebSocketChannelException: WebSocketChannelException: HandshakeException: Handshake error in client (OS Error: 
	CERTIFICATE_VERIFY_FAILED: self signed certificate(handshake.cc:354))
0411 15:13:30 [Debug] :  Loading settings...
0411 15:13:30 [Error] :  Long-lived token read successful
0411 15:13:30 [Debug] :  Socket connecting...
0411 15:13:30 [Error] :  Socket stream Error: WebSocketChannelException: WebSocketChannelException: HandshakeException: Handshake error in client (OS Error: 
	CERTIFICATE_VERIFY_FAILED: self signed certificate(handshake.cc:354))
0411 15:13:35 [Debug] :  Loading settings...
0411 15:13:35 [Error] :  Long-lived token read successful
0411 15:13:35 [Debug] :  Socket connecting...
0411 15:13:35 [Error] :  Socket stream Error: WebSocketChannelException: WebSocketChannelException: HandshakeException: Handshake error in client (OS Error: 
	CERTIFICATE_VERIFY_FAILED: self signed certificate(handshake.cc:354))
0411 15:13:38 [Debug] :  Socket connecting...
0411 15:13:38 [Error] :  Socket stream Error: WebSocketChannelException: WebSocketChannelException: HandshakeException: Handshake error in client (OS Error: 
	CERTIFICATE_VERIFY_FAILED: self signed certificate(handshake.cc:354))
0411 15:13:39 [Debug] :  Loading settings...
0411 15:13:39 [Error] :  Long-lived token read successful
0411 15:13:39 [Debug] :  Socket connecting...
0411 15:13:39 [Error] :  Socket stream Error: WebSocketChannelException: WebSocketChannelException: HandshakeException: Handshake error in client (OS Error: 
	CERTIFICATE_VERIFY_FAILED: self signed certificate(handshake.cc:354

**Comment by estevez-dev** [comment]
The issue with huge gray area is strangest thing I've ever saw here...... 
Anyway your connection issue is because of self signed certificate. Unfortunately it is not supported currently: #180

**Comment by estevez-dev** [comment]
To give you a little help with long lived token field - try to clear app data

**Comment by estevez-dev** [comment]
Closing for now. Feel free to reopen if still actual
