### ISSUE TITLE
Error compiling program with Visual Studio Code

### ISSUE THREAD

**Issue by jctrivera** [estevez-dev/ha_client#537]
I have a problem when I´m compiling the project with some changes that I made.

The debbuger error is:

{
	"resource": "/D:/Users/Juan Carlos/ha_client-master/lib/main.dart",
	"owner": "dart",
	"code": "uri_does_not_exist",
	"severity": 8,
	"message": "Target of URI doesn't exist: '.secrets.dart'.\nTry creating the file referenced by the URI, or Try using a URI for a file that does exist.",
	"source": "dart",
	"startLineNumber": 35,
	"startColumn": 8,
	"endLineNumber": 35,
	"endColumn": 23,
	"tags": []
}

Someone can help me because I do not find the file .secrets.dart in the project.

Thanks for all

**Comment by estevez-dev** [comment]
Sorry, but this is not the issue in the app itself. I've answered you in commit comments.
