### ISSUE TITLE
Integration for mobile app not working

### ISSUE THREAD

**Issue by Jewsh-S** [estevez-dev/ha_client#540]
Using Galaxy Note 10 on Android 10.  The app will not create an integration in Home Assistant anymore. It does not do anything when you press the check integration button, and pressing reset integration gives you a confirmation box but then does nothing.  I can't get an integration back, I deleted it from Home Assistant thinking I wanted to just refresh the integration, but now it's gone and I can't get it back.

**Comment by estevez-dev** [comment]
What is the version of your Home Assistant?

**Comment by Jewsh-S** [comment]
I just upgraded to the latest version thinking maybe that would help. At least it was the latest version it the updater found. It's version 0.100.2

Joshua Shell

________________________________

**Comment by estevez-dev** [comment]
But the latest version is 0.108.6
And you need at least 0.104 for integration to work.

**Comment by Jewsh-S** [comment]
Actually I just ran the upgraded again, and for some reason it found a newer version. I'm checking if it works now on version 0.103.6

Joshua Shell

________________________________

**Comment by Jewsh-S** [comment]
Okay, thanks. I'll figure it out from here!

Joshua Shell

________________________________

**Comment by estevez-dev** [comment]
I think the updates are incremental. Just check again after update to 0.103. got need at least 0.104.

**Comment by estevez-dev** [comment]
This issue was fixed in 1.0.1
