### ISSUE TITLE
Light entity update rate 

### ISSUE THREAD

**Issue by InToSSH** [estevez-dev/ha_client#541]
**HA Client version:** [Main menu -> About HA Client] 0.8.4

**Home Assistant version:** 0.108.6

**Device name:** SM-G955F 

**Android version:** 9

**Description**
I have few of Yeelight RGB bulbs. These are known to have an update rate limit at 60 per minut. 
It looks like this app updates new state even while dragging the sliders for brightness and white temperature, so if I move the slider slowly from left to right to increase the brightness or temperature to my desired value, it updates the state too quickly, causing the bulb to become unavailable. 
I would recommend to update the state only once after the slider is released at the desired position. 

**Screenshots**
[Replace with screenshots]

**Comment by estevez-dev** [comment]
Thanks for the report. I noticed this issue but didn't know it will cause such a big issue.

**Comment by InToSSH** [comment]
No problem, thanks for your support. Yea, I guess for most other lights this won't be an issue, since HA can handle it just fine, unfortunatelly these Yeelights present an issue with a lot of other things aswell in HA.

**Comment by estevez-dev** [comment]
Fixed in 0.8.5
