### ISSUE TITLE
Card doesn't display

### ISSUE THREAD

**Issue by JohnGalt1717** [estevez-dev/ha_client#543]
{entity: sensor.x3_m40i_remaining_fuel, max: 16.5, min: 0, severity: {green: 16, red: 2, yellow: 10}, title: Remaining Fuel, type: gauge}

**Comment by estevez-dev** [comment]
Actually according to [Gauge card documentation](https://www.home-assistant.io/lovelace/gauge/) `min` and `max` values should be integer.
Anyway I'll fix that, thanks for reporting, but you can change `max` to 16 or 17 as a workaround.
