### ISSUE TITLE
Support "customize" attributes

### ISSUE THREAD

**Issue by MeanderingCode** [estevez-dev/ha_client#545]
**Is your feature request related to a problem? Please describe.**

I am using `hidden:true` under `customize` for several entities in my setup. Lovelace is respecting that and other properties.

I'm this app, those entities are displaying. 

**Describe the solution you'd like**

Adhere to Lovelace behavior for the `customize` properties, especially `hidden`.

**Comment by estevez-dev** [comment]
Actually it was supported previously. So it looks like an issue. Will fix, thanks!

**Comment by estevez-dev** [comment]
Fix version: 1.0.0

**Comment by MeanderingCode** [comment]
Version 1.0.0 does not fix the issue for me.

Specifically, the app is showing `sensor` and `device_tracker` entities.

I have an automatic / unmanaged Lovelace setup which shows `sensor` entities but not `device_tracker` entities (default behavior). I added the following config in order to not show specific sensors:
```
sensor.sensor1:
  hidden: true
sensor.sensor2:
  hidden: true
```
After applying the above configuration, Lovelace no longer displays those sensors. Both the previous beta release and the new 1.0.0 release show those sensors.

Additionally, Lovelace does not show `device_tracker`s by default. Adding a section to the config for a device tracker to set `hidden: true|false`, or set a `customize` entry for it with no properties, has no effect in the app or in Lovelace (perhaps Lovelace has another property for showing device trackers or is hard-coded not to in automatic mode).

Looking at https://github.com/estevez-dev/ha_client/commit/792c0d0c840612fe57aa6bf0087829bacac9f447, it seems you only updated the code for "cards". Glancing at the repo, perhaps it is entity "badges" that I am referring to?

**Comment by MeanderingCode** [comment]
Which brings up the question: If `HomeAssistant().autoUi`, should `device_trackers` be filtered from badges to maintain [some] behavior parity with Lovelace?

**Comment by estevez-dev** [comment]
Hi @MeanderingCode 
Thanks for your investigation. Indeed I've added `hidden` support only for entities inside a card. Badges are not filtered. I'll fix that.
Also please note that auto UI for Lovelace is not finished in app. It shows all entities in one card actually.
Also Badges config  would be improved is scope of #530

**Comment by MeanderingCode** [comment]
I see. This seems closed, then, and I will follow that issue.

Thank you for this app! I am enjoying using it!
