### ISSUE TITLE
Unable to connect to Home Assistant in webview

### ISSUE THREAD

**Issue by LiJu09** [estevez-dev/ha_client#552]
**HA Client version:** 1.0.0

**Home Assistant version:** 0.109.4

**Device name:** Samsung J3 2016

**Android version:** 5.1.1

**Description**
Can't load anything in webview.
All other things working perfect.

**Screenshots**

![Screenshot_2020-05-06-17-58-09](https://user-images.githubusercontent.com/40698774/81201379-802d4080-8fc5-11ea-8296-da2922d5142d.png)

**Comment by estevez-dev** [comment]
Hi @LiJu09 
Is it still an issue? If yes please tell me:
1. How do you connect the app? Is it local IP, duckdns or Remote UI?
2. Are you able to view your web UI in browser using the same url you are using in the app to connect?

**Comment by LiJu09** [comment]
I am connecting using local IP.
I can view web UI using browser on mobile and through official app.
Also I tried same using Samsung A3 (2017) - Android 8.0, App version 1.0.0 and it works.

**Comment by estevez-dev** [comment]
I'll try to fix this in 1.1.0

**Comment by estevez-dev** [comment]
Possibly [fixed](https://github.com/estevez-dev/ha_client/commit/3468446b5bd20fe0bde87b2ce1a116abc86e5ba5). Will be included in 1.1.0
