### ISSUE TITLE
annoying notification

### ISSUE THREAD

**Issue by chris-kuhr** [estevez-dev/ha_client#554]
any time I open the app it annoys me with a warning!

**Comment by estevez-dev** [comment]
Which warning?

**Comment by wabosh** [comment]
I believe he meant the App integration warning

**Comment by estevez-dev** [comment]
Yes, but it shouldn't be displayed on every app opening. So I wanted to investigate the reason.

**Comment by chris-kuhr** [comment]
hi, sorry I didn't see your message. It was the app integration warning that appeared each time I switched to the app. But I can't provide further info anymore, because I switched to the official home assistent app, for some other reasons as well. E.g. my picture cards are displyed there... but that's off topic...

Best,
Ck
