### ISSUE TITLE
Donation does not work

### ISSUE THREAD

**Issue by Phaiax** [estevez-dev/ha_client#555]
When trying to donate via the link on ha-client.app it forwards to paypal, but after setting the amount and logging in, it says:

`Dieser Empfänger akzeptiert PayPal-Zahlungen nur über seine Website. Um diese Zahlung durchzuführen, besuchen Sie seine Website oder schreiben Sie den Empfänger direkt an.`

or in english:

`This recipient does accept paypal payments only via his website. To make a payment, visit his website or write to the recipient directly`.

**Comment by estevez-dev** [comment]
Thanks, I'll look into it

**Comment by estevez-dev** [comment]
Hey @Phaiax . Could you please try to do it through the website? https://ha-client.app/
The button is in the bottom of the page.
