### ISSUE TITLE
Dark theme

### ISSUE THREAD

**Issue by MK1-1** [estevez-dev/ha_client#565]
**HA Client version:1.1.0-beta2

**Home Assistant version:**

**Device name:Galaxy Tab 2 P5100

**Android version:7.1.2

**Description**
Dark theme dont stay dark after closing and starting app. Still says dark theme in settings, but isnt. Then you have to tap dark theme in drop down and it switch to dark. 

**Screenshots**
![15905254758331373244799668576868](https://user-images.githubusercontent.com/65975300/82948176-98c7bf80-9fa1-11ea-80c9-af1e54db3d82.jpg)

**Comment by estevez-dev** [comment]
Should be fixed in 1.1.0-beta3
