### ISSUE TITLE
Mobile app thermostat values

### ISSUE THREAD

**Issue by kwakkel1000** [estevez-dev/ha_client#569]
**HA Client version:** [Main menu -> About HA Client]
1.1.1

**Home Assistant version:**

**Device name:**
One plus 6

**Android version:**
10

**Description**
The thermostat doesn't show the current and set temperature anymore. Unless I click on it. 
It did do this in the past. 

**Screenshots**
![Screenshot_20200613-131547](https://user-images.githubusercontent.com/480003/84567299-0b91b280-ad78-11ea-873e-8fa02cf8f072.jpg)

![Screenshot_20200613-131900](https://user-images.githubusercontent.com/480003/84567365-79d67500-ad78-11ea-90b3-6d43656a2442.jpg)

**Comment by estevez-dev** [comment]
HA Client was discontinued
