### ISSUE TITLE
Make it work without Google Play services

### ISSUE THREAD

**Issue by estevez-dev** [estevez-dev/ha_client#579]

**Comment by JonnyHaystack** [comment]
What is Google Play services being used for?

**Comment by estevez-dev** [comment]
Notifications, location tracking, crash reporting.

**Comment by JonnyHaystack** [comment]
Location tracking was previously working for me without Google Play services, but it broke a few months ago. Did you switch to depending on Google Play services at some point?

**Comment by estevez-dev** [comment]
There was a lot of changes in location tracking actually. But HA Client was
always depend on Play Services. It was not even tested without it. This is
a big surprise for me that you can even start the app without Play Services
))

ср, 21 окт. 2020 г., 11:23 Jonathan Haylett <notifications@github.com>:

**Comment by JonnyHaystack** [comment]
Ah, well I do use microG and DejaVu location provider, and it used to work well, until it stopped working a few months ago.

**Comment by estevez-dev** [comment]
Unfortunately the development of HA Client was stopped so I don't think it
would be fixed or implemented. I think this is the time to switch to the
official app or some other alternatives.
You can read more here:
https://github.com/estevez-dev/ha_client/blob/master/README.md

ср, 21 окт. 2020 г. в 12:20, Jonathan Haylett <notifications@github.com>:

**Comment by JonnyHaystack** [comment]
The official app has never had working location tracking without Google Play services, even with microG. That's why I was using HA Client for the location. Maybe I'll try older HA Client builds to see if one of them works.

**Comment by estevez-dev** [comment]
HA Client was discontinued
