### ISSUE TITLE
Garage door badges not displayed properly

### ISSUE THREAD

**Issue by kolbyjack** [estevez-dev/ha_client#581]
**HA Client version:** 1.2.0

**Home Assistant version:** 0.113.1

**Device name:** Binary template sensor

**Android version:** 10

**Description**
Badges using the garage door mdi icons aren't displayed properly.  Instead of showing mdi:garage and mdi:garge-open, it just shows a circle.  I can't verify right now, but I'm also fairly certain the sensor didn't turn red when the door was open.

**Screenshots**
![image](https://user-images.githubusercontent.com/271175/89132921-a63f7f80-d4e5-11ea-91a3-1a0fc37ef3d5.png)

**Comment by estevez-dev** [comment]
HA Client was discontinued
