### ISSUE TITLE
Controls are indistinguishable when "Dark mode" is on

### ISSUE THREAD

**Issue by maretodoric** [estevez-dev/ha_client#582]
Hello,

I'm running Home Assistant app ok Xiaomi Redmi note 8 pro on Android 10. Dark mode is enabled in settings (Settings->Display->Dark Mode). Since recent update, app seems to support dark mode and if phone is set to it, app will use dark mode instead of standard blue/white, which is nice. However, controls are not distinguishable when dark mode is active. switch entities in Lovelace dashboard are dark instead of bright, and are barely visible because of it, and not only that, they look inactive. Most confusing is "Cover" entity and up/down arrows. Up arrow when available is dark (and seems inactive) and down arrow when not available (since garage door is already closed) is bright and seems like that one can only be pressed. Check screenshot to see what i mean.

![Screenshot_2020-08-19-19-50-20-783_io homeassistant companion android](https://user-images.githubusercontent.com/42638763/90671870-977ef980-e255-11ea-89cd-8f3d0054417b.jpg)

Can this be fixed somehow?

**Comment by estevez-dev** [comment]
HA Client was discontinued
